from urllib.parse import urlencode

from typing_extensions import override

from zerver.lib.test_classes import WebhookTestCase


class TravisHookTests(WebhookTestCase):
    TOPIC_NAME = "builds"
    EXPECTED_PUSH_MESSAGE = (
        "**Build [#1](https://app.travis-ci.com/sathwikshetty33/travis-test/builds/277712204)** "
        "is **being built** :counterclockwise: for commit: [Add Projects model.](https://github.com/sathwikshetty33/travis-test/commit/193da1b72346) by sathwikshetty33."
    )

    EXPECTED_PULL_REQUEST_MESSAGE = (
        "**Build [#3](https://app.travis-ci.com/sathwikshetty33/travis-test/builds/277712246)** "
        "is **being built** :counterclockwise: for commit: [Add hello header to xyz.txt](https://github.com/sathwikshetty33/travis-test/pull/1) by Sathwik Shetty."
    )

    def test_travis_message(self) -> None:
        """
        Build notifications are generated by Travis after build completes.

        The subject describes the repo and Stash "project". The
        content describes the commits pushed.
        """

        self.check_webhook(
            "push",
            self.TOPIC_NAME,
            self.EXPECTED_PUSH_MESSAGE,
            content_type="application/x-www-form-urlencoded",
        )

    def test_travis_only_pull_request_event(self) -> None:
        self.url = f'{self.build_webhook_url()}&only_events=["pull_request"]'

        self.check_webhook(
            "pull_request",
            self.TOPIC_NAME,
            self.EXPECTED_PULL_REQUEST_MESSAGE,
            content_type="application/x-www-form-urlencoded",
        )

        self.check_webhook(
            "push",
            content_type="application/x-www-form-urlencoded",
            expect_noop=True,
        )

    def test_travis_exclude_pull_request_event(self) -> None:
        self.url = f'{self.build_webhook_url()}&exclude_events=["pull_request"]'

        self.check_webhook(
            "pull_request",
            content_type="application/x-www-form-urlencoded",
            expect_noop=True,
        )

        self.check_webhook(
            "push",
            self.TOPIC_NAME,
            self.EXPECTED_PUSH_MESSAGE,
            content_type="application/x-www-form-urlencoded",
        )

    def test_travis_only_push_event(self) -> None:
        self.url = f'{self.build_webhook_url()}&only_events=["push"]'

        self.check_webhook(
            "push",
            self.TOPIC_NAME,
            self.EXPECTED_PUSH_MESSAGE,
            content_type="application/x-www-form-urlencoded",
        )

        self.check_webhook(
            "pull_request",
            content_type="application/x-www-form-urlencoded",
            expect_noop=True,
        )

    def test_travis_exclude_push_event(self) -> None:
        self.url = f'{self.build_webhook_url()}&exclude_events=["push"]'

        self.check_webhook(
            "push",
            content_type="application/x-www-form-urlencoded",
            expect_noop=True,
        )

        self.check_webhook(
            "pull_request",
            self.TOPIC_NAME,
            self.EXPECTED_PULL_REQUEST_MESSAGE,
            content_type="application/x-www-form-urlencoded",
        )

    def test_travis_include_glob_events(self) -> None:
        self.url = f'{self.build_webhook_url()}&include_events=["*"]'

        self.check_webhook(
            "pull_request",
            self.TOPIC_NAME,
            self.EXPECTED_PULL_REQUEST_MESSAGE,
            content_type="application/x-www-form-urlencoded",
        )

        self.check_webhook(
            "push",
            self.TOPIC_NAME,
            self.EXPECTED_PUSH_MESSAGE,
            content_type="application/x-www-form-urlencoded",
        )

    def test_travis_exclude_glob_events(self) -> None:
        self.url = f'{self.build_webhook_url()}&exclude_events=["*"]'

        self.check_webhook(
            "pull_request",
            content_type="application/x-www-form-urlencoded",
            expect_noop=True,
        )

        self.check_webhook(
            "push",
            content_type="application/x-www-form-urlencoded",
            expect_noop=True,
        )

    def test_travis_noop(self) -> None:
        expected_error_message = """
While no message is expected given expect_noop=True,
your test code triggered an endpoint that did write
one or more new messages.
        """.strip()

        with self.assertRaises(Exception) as exc:
            self.check_webhook(
                "push", content_type="application/x-www-form-urlencoded", expect_noop=True
            )
        self.assertEqual(str(exc.exception), expected_error_message)

    @override
    def get_body(self, fixture_name: str) -> str:
        return urlencode(
            {"payload": self.webhook_fixture_data("travis", fixture_name, file_type="json")}
        )
