#!/usr/bin/env python3
import json
import os

import pytz

ZULIP_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../')
OUT_PATH = os.path.join(ZULIP_PATH, 'static', 'generated', 'timezones.json')

with open(OUT_PATH, 'w') as f:
    json.dump({"timezones": pytz.all_timezones}, f)
