#!/usr/bin/env node

import {writeFile} from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";

import {getUserAgentRegex} from "browserslist-useragent-regexp";

const root_dir = fileURLToPath(new URL("../..", import.meta.url));
const output_path = path.join(root_dir, "web", "generated", "supported_browser_regex.ts");

async function main() {
    const contents =
        `// This file is generated by tools/setup/build_supported_browser_regex.js\n` +
        `// Do not edit this file directly.\n` +
        `export const supportedBrowserRegex = ${getUserAgentRegex().toString()};\n` +
        `export default supportedBrowserRegex;\n`;

    await writeFile(output_path, contents);
}

await main();
