#!/usr/bin/env bash
set -e

cd "$(dirname "$0")"/../..

email=desdemona@zulip.com

mkdir -p var/puppeteer

password=$(./manage.py print_initial_password "$email" | grep -F "$email" | awk '{ print $2 }')
cat >var/puppeteer/test_credentials.json <<EOF
{"default_user": {"username": "$email", "password": "$password"}}
EOF
