#!/usr/bin/env bash
#
# As of 07 December 2022, per https://pkgs.org/download/transifex-cli, only
# Void Linux and KaOS package the new Go-based Transifex CLI officially, so our
# safest bet is to pull the binaries from GitHub Releases directly for now.
#
# These binaries do not dynamically link to anything, and thus should work on
# glibc and musl (Alpine, Void, etc.) systems equally well.
set -euo pipefail

version=1.6.16
arch="$(uname -m)"

case $arch in
    x86_64)
        tarball="tx-linux-amd64.tar.gz"
        sha256=29f5a59b3820adf140f584e9e3aad1fc55a7ed06540a5131eff91259e2db8431
        ;;

    aarch64)
        tarball="tx-linux-arm64.tar.gz"
        sha256=e6d6994016863946a3e1b86d1fd0967236ec40bf034e2dc87bf616056381739f
        ;;
esac

check_version() {
    out="$(tx --version)" && [ "$out" = "TX Client, version=${version}" ]
}

if ! check_version 2>/dev/null; then
    set -x
    tmpdir="$(mktemp -d)"
    trap 'rm -r "$tmpdir"' EXIT
    cd "$tmpdir"
    curl_opts=(-fLO --retry 3)
    curl "${curl_opts[@]}" "https://github.com/transifex/cli/releases/download/v${version}/${tarball}"
    sha256sum -c <<<"$sha256 $tarball"
    tar -xzf "$tarball" --no-same-owner tx
    install -Dm755 tx /usr/local/bin/tx
    check_version
fi
