#!/usr/bin/env bash
#
# As of 07 December 2022, per https://pkgs.org/download/transifex-cli, only
# Void Linux and KaOS package the new Go-based Transifex CLI officially, so our
# safest bet is to pull the binaries from GitHub Releases directly for now.
#
# These binaries do not dynamically link to anything, and thus should work on
# glibc and musl (Alpine, Void, etc.) systems equally well.
set -euo pipefail

version=1.6.11
arch="$(uname -m)"

case $arch in
    x86_64)
        tarball="tx-linux-amd64.tar.gz"
        sha256=f9e3eeb5b7834a3ed84f2742a85afc7f12f99eb37aa5359db46af1623f6747fd
        ;;

    aarch64)
        tarball="tx-linux-arm64.tar.gz"
        sha256=74ea7b07dae1012c16df914a2246671ab2069f4619000bff07e22cfde7fe0f60
        ;;
esac

check_version() {
    out="$(tx --version)" && [ "$out" = "TX Client, version=${version}" ]
}

if ! check_version 2>/dev/null; then
    set -x
    tmpdir="$(mktemp -d)"
    trap 'rm -r "$tmpdir"' EXIT
    cd "$tmpdir"
    curl_opts=(-fLO --retry 3)
    curl "${curl_opts[@]}" "https://github.com/transifex/cli/releases/download/v${version}/${tarball}"
    sha256sum -c <<<"$sha256 $tarball"
    tar -xzf "$tarball" --no-same-owner tx
    install -Dm755 tx /usr/local/bin/tx
    check_version
fi
