#!/usr/bin/env bash
set -e

export NVM_DIR=/usr/local/nvm

if ! [ -s "$NVM_DIR/nvm.sh" ]
 then
    wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | NVM_DIR=/usr/local/nvm bash
fi

source $NVM_DIR/nvm.sh

nvm install stable && nvm alias default stable


n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local



