#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

cat <<EOF
********************************************************************************

If you have any queries visit https://chat.zulip.org to get help from the Zulip community.
For enterprise plans and support mail at support@zulipchat.com.

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f "${0}")
EOF
