# Generated by Django 5.0.6 on 2024-05-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0520_attachment_zerver_attachment_realm_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
