# Generated by Django 5.0.6 on 2024-05-25 23:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0521_message_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="date_deleted_history",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="message",
            name="deleter_history_id",
            field=models.IntegerField(default=-1),
        ),
    ]
