# Generated by Django 5.0.6 on 2024-05-26 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0522_message_date_deleted_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="date_deleted_history",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="archivedmessage",
            name="deleter_history_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="archivedmessage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
