# Generated by Django 5.0.6 on 2024-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0523_archivedmessage_date_deleted_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedmessage",
            name="date_deleted_history",
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name="message",
            name="date_deleted_history",
            field=models.IntegerField(db_index=True, default=-1),
        ),
    ]
