#!/bin/bash

py_version="$(python -c 'import sys; print(sys.version_info[0])')"

if [ "$py_version" == 2 ]; then
    source /srv/zulip-venv/bin/activate
else
    source /srv/zulip-py3-venv/bin/activate
fi

echo "Using $VIRTUAL_ENV"
