#!/bin/bash

source tools/travis/activate-venv

set -e
set -x

./tools/lint --pep8 # Include the slow and thus non-default pep8 linter check
./tools/test-tools
./tools/test-backend --coverage
./tools/test-migrations
# test-run-dev temporarily disabled due to weird Travis CI issues.
#./tools/test-run-dev
./tools/optimize-svg
./tools/test-documentation
./tools/test-help-documentation.py
./tools/test-api
python -W ignore tools/check-capitalization
# Some test suites disabled in CI for being flaky
#./tools/test-queue-worker-reload
