#!/bin/bash

source tools/travis/activate-venv

set -e
set -x

./tools/lint-all
./tools/test-backend --coverage --no-verbose-coverage
./tools/test-management
./tools/test-migrations
netstat -nlp
ps -ef
./tools/test-run-dev
#./tools/test-queue-worker-reload
