#!/bin/bash

echo '+ ./tools/run-mypy --linecoverage-report'
./tools/run-mypy --linecoverage-report
retcode="$?"

if [ "$retcode" == "0" ]; then
    echo "The mypy static type checker for python detected no errors!"
else
    echo
    echo "The mypy static type checker for Python threw some errors,"
    echo "which indicates a bug in your code or incorrect type annotations."
    echo "Please see http://zulip.readthedocs.io/en/latest/mypy.html for details"
    echo "on mypy, how Zulip is using mypy, and how to debug common issues."
    exit "$retcode"
fi
