#!/bin/bash

source tools/travis/activate-venv

echo "+ ./tools/lint-all"
./tools/lint-all
retcode="$?"

echo
if [ "$retcode" == 0 ]; then
    echo "tools/lint-all detected no errors on Python 3!"
else
    cat tools/travis/py3_lint_all_error_msg.txt
    exit 1
fi

tools/test-migrations
