#!/bin/bash
set -e
set -x

# We only need the mypy checker in this build, so we just install that
# directly, skipping provision.

if ! pip install --no-deps -r requirements/mypy.txt; then
    echo "\`pip install --no-deps -r requirements/mypy.txt\`: Failure occured while trying to perform dependancy installation, Retrying..."
    pip install --no-deps -r requirements/mypy.txt
fi
