#!/bin/bash
set -e
set -x

# We only need mypy and the python 3 compatibility checkers in this
# build, so we just install those directly, skipping provision.
pip install --no-deps -r requirements/mypy.txt
pip install --no-deps -r requirements/py3k.txt
