#!/bin/bash
set -e
set -x

# We only need mypy and the python 3 compatibility checkers in this
# build, so we just install those directly, skipping provision.

if ! pip install --no-deps -r requirements/mypy.txt; then
    echo "\`pip install --no-deps -r requirements/mypy.txt\`: Failure occured while trying to perform dependancy installation, Retrying..."
    pip install --no-deps -r requirements/mypy.txt
fi

if ! pip install --no-deps -r requirements/py3k.txt; then
    echo "\`pip install --no-deps -r requirements/py3k.txt\`: Failure occured while trying to perform dependancy installation, Retrying..."
    pip install --no-deps -r requirements/py3k.txt
fi
