#!/bin/bash
set -e
set -x

# This is just a thin wrapper around provision.
# Provisioning may fail due to many issues but most of the times a network
# connection issue is the reason. So we are going to retry entire provisioning
# once again if that fixes our problem.
if ! tools/provision; then
    echo "\`provision\`: Something went wrong with the provisioning, might be a network issue, Retrying to provision..."
    tools/provision
fi
