# Generated by Django 1.10.5 on 2017-02-01 22:28
from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index


class Migration(migrations.Migration):
    atomic = not settings.MIGRATIONS_ADD_REMOVE_INDEXES_CONCURRENTLY
    dependencies = [
        ("zerver", "0050_userprofile_avatar_version"),
        ("analytics", "0007_remove_interval"),
    ]

    operations = [
        add_index(
            model_name="realmcount",
            index=models.Index(
                fields=["property", "end_time"],
                name="analytics_realmcount_property_end_time_3b60396b_idx",
            ),
        ),
        add_index(
            model_name="streamcount",
            index=models.Index(
                fields=["property", "realm", "end_time"],
                name="analytics_streamcount_property_realm_id_end_time_155ae930_idx",
            ),
        ),
        add_index(
            model_name="usercount",
            index=models.Index(
                fields=["property", "realm", "end_time"],
                name="analytics_usercount_property_realm_id_end_time_591dbec1_idx",
            ),
        ),
    ]
