name         'camptocamp-apt'
version      '0.0.2'
source       'https://github.com/camptocamp/puppet-apt'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp Apt Module'
description  'APT Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-apt'
