# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0005_confirmation_realm'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmcreationkey',
            name='presume_email_valid',
            field=models.BooleanField(default=False),
        ),
    ]
