# Generated by Django 3.2.5 on 2021-08-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confirmation", "0009_confirmation_expiry_date_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmation",
            name="expiry_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
