# Generated by Django 5.2.3 on 2025-07-04 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("confirmation", "0016_realmcreationkey_to_realmcreationstatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RealmCreationKey",
        ),
    ]
