# Generated by Django 1.11.20 on 2019-04-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0007_remove_deprecated_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerplan",
            name="next_invoice_date",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
