# Generated by Django 3.2.2 on 2021-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0009_customer_sponsorship_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerplan",
            name="exempt_from_from_license_number_check",
            field=models.BooleanField(default=False),
        ),
    ]
