# Generated by Django 3.2.6 on 2021-09-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0013_alter_zulipsponsorshiprequest_org_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerplan",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
    ]
