# Generated by Django 3.2.9 on 2021-11-27 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0018_remoterealmauditlog"),
        ("zerver", "0370_realm_enable_spectator_access"),
        ("corporate", "0015_event_paymentintent_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="remote_server",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zilencer.remotezulipserver",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="realm",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
            ),
        ),
    ]
