# Generated by Django 4.2 on 2023-04-10 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0016_customer_add_remote_server_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="exempt_from_from_license_number_check",
            new_name="exempt_from_license_number_check",
        ),
    ]
