# Generated by Django 4.2.1 on 2023-05-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "corporate",
            "0017_rename_exempt_from_from_license_number_check_customer_exempt_from_license_number_check",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("realm__isnull", False), ("remote_server__isnull", False), _connector="XOR"
                ),
                name="cloud_xor_self_hosted",
            ),
        ),
    ]
