# Generated by Django 4.2.6 on 2023-11-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0018_customer_cloud_xor_self_hosted"),
    ]

    operations = [
        migrations.AddField(
            model_name="zulipsponsorshiprequest",
            name="expected_total_users",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="zulipsponsorshiprequest",
            name="paid_users_count",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="zulipsponsorshiprequest",
            name="paid_users_description",
            field=models.TextField(default=""),
        ),
    ]
