# Generated by Django 4.2.7 on 2023-11-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0021_remove_session_payment_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_manual_license_management_upgrade_session",
            field=models.BooleanField(default=False),
        ),
    ]
