# Generated by Django 4.2.7 on 2023-11-26 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0025_alter_zulipsponsorshiprequest_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zulipsponsorshiprequest",
            name="realm",
        ),
    ]
