# Generated by Django 4.2.8 on 2023-12-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0027_alter_zulipsponsorshiprequest_requested_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="zulipsponsorshiprequest",
            name="requested_plan",
            field=models.CharField(
                choices=[("", "UNSPECIFIED"), ("Community", "COMMUNITY"), ("Business", "BUSINESS")],
                default="",
                max_length=50,
            ),
        ),
    ]
