# Generated by Django 4.2.8 on 2023-12-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0029_session_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zulipsponsorshiprequest",
            name="requested_plan",
            field=models.CharField(
                choices=[
                    ("", "UNSPECIFIED"),
                    ("Community", "COMMUNITY"),
                    ("Basic", "BASIC"),
                    ("Business", "BUSINESS"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
