# Generated by Django 4.2.8 on 2023-12-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0030_alter_zulipsponsorshiprequest_requested_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="flat_discount",
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name="customer",
            name="flat_discounted_months",
            field=models.IntegerField(default=0),
        ),
    ]
