# Generated by Django 4.2.8 on 2023-12-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0031_customer_flat_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="minimum_licenses",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
