# Generated by Django 4.2.8 on 2024-01-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0032_customer_minimum_licenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerplan",
            name="invoice_overdue_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
