# Generated by Django 4.2.8 on 2024-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0033_customerplan_invoice_overdue_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="required_plan_tier",
            field=models.SmallIntegerField(null=True),
        ),
    ]
