# Generated by Django 4.2.8 on 2024-01-27 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0036_fix_customer_plans_scheduled_after_legacy_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerPlanOffer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fixed_price", models.IntegerField(null=True)),
                ("tier", models.SmallIntegerField()),
                ("status", models.SmallIntegerField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="corporate.customer"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
