# Generated by Django 4.2.9 on 2024-02-02 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0037_customerplanoffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerplanoffer",
            name="sent_invoice_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stripe_invoice_id", models.CharField(max_length=255, unique=True)),
                ("status", models.SmallIntegerField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="corporate.customer"
                    ),
                ),
            ],
        ),
    ]
