# Generated by Django 4.2.9 on 2024-02-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0039_backfill_end_date_for_fixed_price_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerplan",
            name="reminder_to_review_plan_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
