# Generated by Django 4.2.11 on 2024-03-27 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0041_fix_plans_on_free_trial_with_changes_in_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="plan",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corporate.customerplan",
            ),
        ),
    ]
