# Generated by Django 4.2.11 on 2024-04-10 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0041_fix_plans_on_free_trial_with_changes_in_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_created_for_free_trial_upgrade",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="plan",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corporate.customerplan",
            ),
        ),
    ]
