# Generated by Django 5.0.6 on 2024-05-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0043_remove_customer_default_discount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerStripeEmailChangeStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("new_email", models.EmailField(max_length=254)),
                ("old_email", models.EmailField(max_length=254)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.IntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="corporate.customer"
                    ),
                ),
            ],
        ),
    ]
