# Generated by Django 5.1.8 on 2025-05-27 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0045_zulipsponsorshiprequest_plan_to_use_zulip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerplan",
            old_name="invoice_overdue_email_sent",
            new_name="stale_audit_log_data_email_sent",
        ),
    ]
