# Generated by Django 5.2.14 on 2026-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0046_rename_customerplan_invoice_overdue_email_sent"),
    ]

    # CustomerPlanOffer and CustomerPlan status field values
    # that we are setting to be unique for each Customer.
    CONFIGURED = 1
    NEVER_STARTED = 12

    operations = [
        migrations.AddConstraint(
            model_name="customerplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", NEVER_STARTED)),
                fields=("customer",),
                name="unique_never_started_plan_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerplanoffer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", CONFIGURED)),
                fields=("customer",),
                name="unique_configured_plan_offer_customer",
            ),
        ),
    ]
