#!/usr/bin/env python3

"""
Nagios plugin to check that Zephyr mirror forwarding is running.

This script just checks the contents of a file. The forwarding test
itself lives in api/integrations/zephyr/check-mirroring and should be
run out of cron.

See puppet/zulip_ops/files/cron.d/zephyr-mirror for the crontab details.
"""
if False:
    # See https://zulip.readthedocs.io/en/latest/testing/mypy.html#mypy-in-production-scripts
    from typing import Dict

import os
import time

RESULTS_FILE = "/var/lib/nagios_state/check-mirroring-results"

states = {
    "OK": 0,
    "WARNING": 1,
    "CRITICAL": 2,
    "UNKNOWN": 3
}  # type: Dict[str, int]

def report(state, data, last_check):
    # type: (str, str, float) -> None
    print("%s: Last test run completed at %s\n%s" % (
        state, time.strftime("%Y-%m-%d %H:%M %Z", time.gmtime(last_check)),
        data))
    exit(states[state])

data = open(RESULTS_FILE).read().strip()
if data.split("\n")[-1].strip() == "0":
    state = "OK"
else:
    state = "CRITICAL"

last_check = os.stat(RESULTS_FILE).st_mtime
time_since_last_check = time.time() - last_check
if time_since_last_check > 60 * 5:
    state = "UNKNOWN"
    data = "Results file is stale"

report(state, data, last_check)
