#!/usr/bin/env bash
set -e
set -x

rm -rf static/third/gemoji/images
(cd tools/setup/emoji_dump && python ./emoji_dump.py)
mkdir -p static/third/gemoji/images
mv tools/setup/emoji_dump/out static/third/gemoji/images/emoji
cp -RPp assets/zulip-emoji/* static/third/gemoji/images/emoji/
