// These declarations tell the TypeScript compiler about the existence
// of the global variables for our untyped JavaScript modules.  Please
// remove each declaration when the corresponding module is migrated
// to TS.

declare let activity: any;
declare let admin: any;
declare let alert_words_ui: any;
declare let attachments_ui: any;
declare let avatar: any;
declare let blueslip: any;
declare let bot_data: any;
declare let buddy_data: any;
declare let buddy_list: any;
declare let compose_actions: any;
declare let composebox_typeahead: any;
declare let compose_ui: any;
declare let confirm_dialog: any;
declare let csrf_token: any;
declare let current_msg_list: any;
declare let emoji: any;
declare let emoji_picker: any;
declare let favicon: any;
declare let gear_menu: any;
declare let hashchange: any;
declare let hash_util: any;
declare let helpers: any;
declare let home_msg_list: any;
declare let hotkey: any;
declare let hotspots: any;
declare let i18n: any;
declare let input_pill: any;
declare let list_util: any;
declare let message_events: any;
declare let message_fetch: any;
declare let message_flags: any;
declare let message_list: any;
declare let message_store: any;
declare let message_util: any;
declare let narrow: any;
declare let navigate: any;
declare let notifications: any;
declare let overlays: any;
declare let padded_widget: any;
declare let page_params: any;
declare let panels: any;
declare let pointer: any;
declare let popovers: any;
declare let presence: any;
declare let reactions: any;
declare let realm_icon: any;
declare let realm_logo: any;
declare let recent_topics: any;
declare let reminder: any;
declare let scroll_bar: any;
declare let search: any;
declare let search_pill_widget: any;
declare let search_suggestion: any;
declare let server_events: any;
declare let settings: any;
declare let settings_account: any;
declare let settings_bots: any;
declare let settings_display: any;
declare let settings_emoji: any;
declare let settings_exports: any;
declare let settings_invites: any;
declare let settings_linkifiers: any;
declare let settings_notifications: any;
declare let settings_org: any;
declare let settings_profile_fields: any;
declare let settings_sections: any;
declare let settings_streams: any;
declare let settings_user_groups: any;
declare let settings_users: any;
declare let starred_messages: any;
declare let stream_list: any;
declare let stream_popover: any;
declare let subs: any;
declare let message_view_header: any;
declare let timerender: any;
declare let typeahead_helper: any;
declare let typing_events: any;
declare let ui: any;
declare let unread: any;
declare let unread_ops: any;
declare let upload_widget: any;
declare let user_events: any;
declare let widgetize: any;

interface JQuery {
    expectOne(): JQuery;
}
