# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0047_realm_add_emoji_by_admins_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='disallow_disposable_email',
            field=models.BooleanField(default=False),
        ),
    ]
