# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0048_realm_disallow_disposable_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realm',
            old_name='disallow_disposable_email',
            new_name='disallow_disposable_email_id',
        ),
    ]
