# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:52
from __future__ import unicode_literals

import bitfield.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0050_userprofile_avatar_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_pieces', bitfield.models.BitField([b'welcome', b'streams', b'topics', b'narrowing', b'replying', b'get_started'], default=0)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
