# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0051_auto_20170101_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realm',
            name='disallow_disposable_email_id',
        ),
    ]
