# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0052_remove_realm_disallow_disposable_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='disallow_disposable_email_id',
            field=models.BooleanField(default=False),
        ),
    ]
