# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0053_userprofile_emoji_alt_code'),
        ('zerver', '0054_realm_icon'),
    ]

    operations = [
    ]
