# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0056_userprofile_emoji_alt_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='email_changes_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
