# Generated by Django 1.10.5 on 2017-02-27 14:34
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0057_realmauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="email_changes_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
