# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:22

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0061_userprofile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='', max_length=40),
        ),
    ]
