# Generated by Django 1.10.5 on 2017-03-21 15:58
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0065_realm_inline_image_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="inline_url_embed_preview",
            field=models.BooleanField(default=True),
        ),
    ]
