# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0066_realm_inline_url_embed_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmauditlog',
            name='extra_data',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
