# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0068_remove_realm_domain'),
        ('zerver', '0067_realmauditlog_extra_data'),
    ]
