# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0072_realmauditlog_add_index_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='should_animate_emoji_on_hover',
            field=models.BooleanField(default=False),
        ),
    ]
