# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 21:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
from django.db.backends.postgresql_psycopg2.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0078_service'),
    ]

    def emoji_to_lowercase(apps, schema_editor):
        # type: (StateApps, DatabaseSchemaEditor) -> None
        RealmEmoji = apps.get_model("zerver", "RealmEmoji")
        emoji = RealmEmoji.objects.all()
        for e in emoji:
            e.name = e.name.lower()
            e.save()

    operations = [
        migrations.RunPython(emoji_to_lowercase),
        migrations.AlterField(
            model_name='realmemoji',
            name='name',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator(message='Invalid characters in emoji name', regex=b'^[0-9a-z.\\-_]+(?<![.\\-_])$')]),
        ),
    ]
