# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0081_make_emoji_lowercase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('user_profile', 'name')]),
        ),
    ]
