# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0085_fix_bots_with_none_bot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='require_topics_message',
            field=models.BooleanField(default=False),
        ),
    ]
