# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0086_realm_require_topics_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realm',
            name='mandatory_topics',
        ),
    ]
