# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 08:34

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0087_remove_old_scheduled_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='invites_granted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='invites_used',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
