# Generated by Django 1.11.2 on 2017-07-22 13:44

from typing import List

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0093_subscription_event_log_backfill"),
    ]

    operations: List[migrations.operations.base.Operation] = []
