# Generated by Django 1.11.2 on 2017-08-09 04:21
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0095_index_unread_user_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationuser",
            name="password_required",
            field=models.BooleanField(default=True),
        ),
    ]
