# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0096_add_password_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedusermessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
