# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0097_reactions_emoji_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_config',
            field=models.TextField(default='{}'),
        ),
    ]
