# Generated by Django 1.11.5 on 2017-10-18 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0110_stream_is_in_zephyr_realm"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotUserStateData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.TextField(db_index=True)),
                ("value", models.TextField()),
                (
                    "bot_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="botuserstatedata",
            unique_together={("bot_profile", "key")},
        ),
    ]
