# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0118_defaultstreamgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='night_mode',
            field=models.BooleanField(default=False),
        ),
    ]
