# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0121_realm_signup_notifications_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_stream_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
