# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0122_userprofile_enable_stream_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
