# Generated by Django 1.11.6 on 2017-11-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0122_rename_botuserstatedata_botstoragedata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="userprofile",
            unique_together={("realm", "email")},
        ),
    ]
