# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0123_userprofile_make_realm_email_pair_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_stream_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
