# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0128_scheduledemail_realm'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='listening_bots_str',
            field=models.TextField(null=True),
        ),
    ]
