# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0130_text_choice_in_emojiset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emoji_conversion',
            field=models.BooleanField(default=False),
        ),
    ]
