# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0130_text_choice_in_emojiset'),
        ('zerver', '0129_userprofile_emoji_conversion'),
    ]

    operations = [
    ]
