# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0132_realm_message_visibility_limit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BotUserConfigData',
            new_name='BotConfigData',
        ),
    ]
