# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0134_scheduledmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='logo_source',
            field=models.CharField(choices=[('G', 'Hosted by Gravatar'), ('U', 'Uploaded by administrator')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='realm',
            name='logo_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
