# Generated by Django 1.11.6 on 2018-01-24 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0135_scheduledmessage_delivery_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="quota",
        ),
    ]
