# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0135_scheduledmessage_delivery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='muteduser',
            unique_together=set([('user_profile', 'muted_user_profile')]),
        ),
    ]
