# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-18 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0139_fill_last_message_id_in_subscription_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='send_welcome_emails',
            field=models.BooleanField(default=True),
        ),
    ]
