# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0139_fill_last_message_id_in_subscription_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_stream_admin',
            field=models.BooleanField(default=False),
        ),
    ]
