# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0142_userprofile_translate_emoticons'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='message_content_delete_limit_seconds',
            field=models.IntegerField(default=600),
        ),
    ]
