# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0142_userprofile_translate_emoticons'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='message_content_in_email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
