# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0142_userprofile_translate_emoticons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realm',
            old_name='allow_message_deleting',
            new_name='allow_message_deleting_by_user',
        ),
    ]
