# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0143_auto_20180307_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='allow_message_deleting_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
