# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0143_realm_bot_creation_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realm',
            name='create_generic_bot_by_admins_only',
        ),
    ]
