# Generated by Django 1.11.6 on 2018-03-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0146_userprofile_message_content_in_email_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="disallow_disposable_email_addresses",
            field=models.BooleanField(default=True),
        ),
    ]
