# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0148_max_invites_forget_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='guidelines_url',
            field=models.URLField(null=True),
        ),
    ]
