# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0149_realm_emoji_drop_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=60)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.Stream')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lockedtopic',
            unique_together=set([('stream', 'topic_name')]),
        ),
    ]
