# Generated by Django 1.11.6 on 2018-03-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0151_last_reminder_default_none"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="default_twenty_four_hour_time",
            field=models.BooleanField(default=False),
        ),
    ]
