# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0155_change_default_realm_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofilefield',
            name='hint',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
