# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0167_custom_profile_fields_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_web_public',
            field=models.BooleanField(default=False),
        ),
    ]
