# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 17:40
from __future__ import unicode_literals

from django.db import migrations
from django.db.backends.postgresql_psycopg2.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps
from unicodedata import category

# cannot pull these from UserProfile
NAME_INVALID_CHARS = ['*', '`', '"', '@',
                      '(', ')', '<', '>',
                      '[', ']', ':', ';',
                      '@', '\\', ',', '.']

def strip_full_names(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:

    UserProfile = apps.get_model('zerver', 'UserProfile')
    for user in UserProfile.objects.all():
        temp_name = user.full_name
        new_name = ""
        for i in temp_name:
            if (i not in NAME_INVALID_CHARS) and (category(i)[0] != 'C'):
                new_name += i
        user.full_name = new_name
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0168_stream_is_web_public'),
    ]

    operations = [
        migrations.RunPython(strip_full_names)
    ]
