# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0172_add_user_type_of_custom_profile_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='display_email',
            field=models.BooleanField(default=True),
        ),
    ]
