# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0172_add_user_type_of_custom_profile_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='logo_source',
            field=models.CharField(choices=[('G', 'Hosted by Gravatar'), ('U', 'Uploaded by administrator')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='realm',
            name='logo_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
