# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0172_add_user_type_of_custom_profile_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_stream_admin',
            field=models.BooleanField(default=False),
        ),
    ]
