# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0174_userprofile_delivery_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='start')),
                ('end', models.DateTimeField(db_index=True, null=True, verbose_name='start')),
                ('file_path', models.TextField(db_index=True, null=True, unique=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
