# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0175_change_realm_audit_log_event_type_tense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='notifications',
        ),
    ]
