# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0176_spam_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='spam_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'spam_not_reported'), (1, 'spam_reported'), (2, 'spam_confirmed')], default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='spam_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'spam_not_reported'), (1, 'spam_reported'), (2, 'spam_confirmed')], default=0),
        ),
    ]
