# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 14:45
from __future__ import unicode_literals
import base64
import os
import string

from django.conf import settings
from django.db import migrations, models
from django.db.migrations.state import StateApps
from django.db.models import Max
from django.db.backends.postgresql_psycopg2.schema import DatabaseSchemaEditor
from django.utils.timezone import now as timezone_now
import django.db.models.deletion

import zerver.lib.utils

def copy_api_keys(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    RealmAuditLog = apps.get_model('zerver', 'RealmAuditLog')
    UserProfile = apps.get_model('zerver', 'UserProfile')
    UserAPIKey = apps.get_model('zerver', 'UserAPIKey')
    users = UserProfile.objects.all()

    for user in users:
        date_last_key_regen = RealmAuditLog.objects.filter(
            modified_user_id=user.id,
            event_type='user_api_key_changed'
        ).aggregate(Max('event_time'))['event_time__max']

        if date_last_key_regen is None:
            date_created = user.date_joined
        else:
            # The key may have never been regenerated after RealmAuditLogs
            # were implemented, so if there are no records of the API key
            # changing, for this user, we asume it was created the same time
            # as the user
            date_created = max(date_last_key_regen, user.date_joined)

        UserAPIKey.objects.create(user_profile_id=user.id,
                                  api_key=user.api_key,
                                  description='Default API key',
                                  date_created=date_created)

class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0182_set_initial_value_is_private_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=timezone_now)),
                ('api_key', models.CharField(max_length=32,
                                             default=zerver.lib.utils.generate_api_key)),
            ],
        ),
        migrations.AddField(
            model_name='userapikey',
            name='user_profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_api_keys,
                             reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userprofile',
            name='api_key',
        ),
    ]
