# Generated by Django 1.11.14 on 2018-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0182_set_initial_value_is_private_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customprofilefield",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
