# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0183_change_custom_field_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='starred_message_counts',
            field=models.BooleanField(default=False),
        ),
    ]
