# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 17:57
from __future__ import unicode_literals

from django.db import migrations, models
from django.apps import apps
from django.db.models import F, Value as V
from django.db.models.functions import Concat

from django.db.backends.postgresql_psycopg2.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps

def populate_short_name(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    UserProfile = apps.get_model('zerver', 'UserProfile')
    UserProfile.objects.all().update(short_name=(Concat(V('user'), F('id'))))


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0183_realm_delivery_email_hidden'),
    ]

    operations = [
        migrations.RunPython(populate_short_name,
                             reverse_code=migrations.RunPython.noop),
    ]
