# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0186_userprofile_starred_message_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_login_emails',
            field=models.BooleanField(default=True),
        ),
    ]
