# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0189_userprofile_add_some_emojisets'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedDocArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.TextField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
