# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 00:55
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.backends.postgresql_psycopg2.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps

def backfill_first_message_id(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    Stream = apps.get_model('zerver', 'Stream')
    Message = apps.get_model('zerver', 'Message')
    Recipient = apps.get_model('zerver', 'Recipient')
    all_streams = Stream.objects.all()
    for s in all_streams:
        try:
            s.first_message_id = Message.objects.filter(
                recipient_id=Recipient.objects.get(type_id=s.id, type=2).id).first().id
        except AttributeError:
            continue
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0189_userprofile_add_some_emojisets'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='first_message_id',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(backfill_first_message_id,
                             reverse_code=migrations.RunPython.noop),
    ]
