# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0190_cleanup_pushdevicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofilefieldvalue',
            name='rendered_value',
            field=models.TextField(default=None, null=True),
        ),
    ]
