# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0190_embeddeddocarticle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='embeddeddocarticle',
            unique_together=set([('directory', 'title')]),
        ),
    ]
