# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0190_cleanup_pushdevicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='no_topic_counter',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
