# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-11 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0191_realm_seat_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedmessage',
            old_name='subject',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='subject',
            new_name='topic',
        ),
    ]
