# Generated by Django 1.11.16 on 2018-11-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0191_realm_seat_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="customprofilefieldvalue",
            name="rendered_value",
            field=models.TextField(default=None, null=True),
        ),
    ]
