# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0192_customprofilefieldvalue_rendered_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stream_sorted_by_recency',
            field=models.BooleanField(default=False),
        ),
    ]
