# Generated by Django 1.11.16 on 2018-12-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0194_userprofile_notification_sound"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="first_visible_message_id",
            field=models.IntegerField(default=0),
        ),
    ]
