# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 14:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0195_realm_first_visible_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmfilter',
            name='is_stream_filter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realmfilter',
            name='stream_ids',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterUniqueTogether(
            name='realmfilter',
            unique_together=set([('realm', 'pattern', 'stream_ids')]),
        ),
    ]
