# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0195_realm_first_visible_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevicetoken',
            name='notification_encryption_key',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
