# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0203_realm_message_content_allowed_in_email_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamUserGroupAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.Stream')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.UserGroup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='streamusergroupaccess',
            unique_together=set([('user_group', 'stream')]),
        ),
    ]
