# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0204_stream_user_group_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='sending_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
