# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0206_stream_rendered_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiuseinvite',
            name='invited_as',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='needs_to_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
