# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0207_multiuseinvite_invited_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='needs_to_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
