# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0208_add_realm_night_logo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPGP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='want_encrypted_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='want_signed_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpgp',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
