# Generated by Django 1.11.20 on 2019-03-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0212_make_stream_email_token_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="digest_weekday",
            field=models.SmallIntegerField(default=1),
        ),
    ]
