# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0212_make_stream_email_token_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='demote_inactive_streams',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
