# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0212_make_stream_email_token_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='no_topic_counter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
