# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0214_realm_invite_to_stream_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedmessage',
            old_name='pub_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='pub_date',
            new_name='timestamp',
        ),
    ]
