# Generated by Django 1.11.20 on 2019-05-06 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0217_migrate_create_stream_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="create_stream_by_admins_only",
        ),
    ]
