# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0224_alter_field_realm_video_chat_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
