# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 15:54
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.backends.postgresql_psycopg2.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps

def set_oldest_user_primary_admin(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    Realm = apps.get_model('zerver', 'Realm')
    UserProfile = apps.get_model('zerver', 'Realm')
    for realm in Realm.objects.all():
        primary_admin_exists = UserProfile.objects.filter(realm=realm, is_primary_admin=True)
        if not primary_admin_exists:
            realm_admins = UserProfile.objects.filter(realm=realm, is_active=True,
                                                      is_realm_admin=True)
            oldest_realm_admin = realm_admins.order_by('date_joined').first()
            oldest_realm_admin.is_primary_admin = True
            oldest_realm_admin.save(update_fields=["is_primary_admin"])

class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0227_inline_url_embed_preview_default_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_primary_admin',
            field=models.BooleanField(default=False),
        ),

        migrations.RunPython(set_oldest_user_primary_admin,
                             reverse_code=migrations.RunPython.noop),
    ]
