# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0230_rename_to_enable_stream_audible_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofilefield',
            name='display_on_small_profile',
            field=models.BooleanField(default=False),
        ),
    ]
