# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0231_add_archive_transaction_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
