# Generated by Django 1.11.20 on 2019-06-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0232_make_archive_transaction_field_not_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_hash",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
