# Generated by Django 1.11.20 on 2019-05-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0233_userprofile_avatar_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customprofilefield",
            name="field_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Short text"),
                    (2, "Long text"),
                    (4, "Date picker"),
                    (5, "Link"),
                    (7, "External account"),
                    (3, "List of options"),
                    (6, "Person picker"),
                ],
                default=1,
            ),
        ),
    ]
