# Generated by Django 1.11.25 on 2019-10-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0250_saml_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationuser",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="full_name_validated",
            field=models.BooleanField(default=False),
        ),
    ]
