# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-16 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0250_saml_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='user_group_edit_policy',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
