# Generated by Django 1.11.26 on 2019-11-21 01:47

from typing import Any, List

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0253_userprofile_wildcard_mentions_notify"),
        ("zerver", "0209_user_profile_no_empty_password"),
    ]

    operations: List[Any] = []
