# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0256_userprofile_stream_set_recipient_column_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='alert_word_notify',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alert_word_notify',
            field=models.BooleanField(default=True),
        ),
    ]
