# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-15 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0258_enable_online_push_notifications_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
