# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0258_enable_online_push_notifications_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='description',
            field=models.TextField(default='The coolest place in the universe'),
        ),
    ]
