# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-15 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0260_missed_message_addresses_from_redis_to_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('color', models.TextField(default='hsla(102, 85%, 57%, 0.5)')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
