# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0261_realm_private_message_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='announcement_only_stream_post_policy',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
