# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-15 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0262_migrate_alert_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='alert_words',
        ),
    ]
