# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-07 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0265_remove_stream_is_announcement_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='', max_length=128),
        ),
    ]
