# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-08 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0265_remove_stream_is_announcement_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpresence',
            name='realm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zerver.Realm'),
        ),
    ]
