# Generated by Django 1.11.28 on 2020-02-08 20:34
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index


class Migration(migrations.Migration):
    atomic = not settings.MIGRATIONS_ADD_REMOVE_INDEXES_CONCURRENTLY
    dependencies = [
        ("zerver", "0267_backfill_userpresence_realm_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpresence",
            name="realm",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zerver.Realm"),
        ),
        add_index(
            model_name="userpresence",
            index=models.Index(
                fields=["realm", "timestamp"],
                name="zerver_userpresence_realm_id_timestamp_25f410da_idx",
            ),
        ),
    ]
