# Generated by Django 2.2.10 on 2020-03-15 17:25
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0269_gitlab_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="huddle",
            name="recipient",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="zerver.Recipient"
            ),
        ),
    ]
