# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-07 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0269_gitlab_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='persistent_edit',
            field=models.BooleanField(default=False),
        ),
    ]
