# Generated by Django 2.2.10 on 2020-03-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0271_huddle_set_recipient_column_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmfilter',
            name='stream_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='realmfilter',
            unique_together={('realm', 'pattern', 'stream_id')},
        ),
    ]
