# Generated by Django 2.2.10 on 2020-03-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0271_huddle_set_recipient_column_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='description',
            field=models.TextField(default='The coolest place in the universe'),
        ),
    ]
