# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0272_realm_default_code_block_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPreviewRemoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.ArchivedMessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreviewRemoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='previewremoved',
            unique_together=set([('message', 'url')]),
        ),
        migrations.AlterUniqueTogether(
            name='archivedpreviewremoved',
            unique_together=set([('message', 'url')]),
        ),
    ]
