# Generated by Django 2.2.12 on 2020-04-30 00:35

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Upper
from django.conf import settings

from . import add_index


class Migration(migrations.Migration):
    atomic = settings.ATOMIC_PG_MIGRATIONS

    dependencies = [
        ("zerver", "0278_remove_userprofile_alert_words"),
    ]

    operations = [
        add_index(
            model_name="message",
            index=models.Index(
                "recipient",
                Upper("subject"),
                F("id").desc(nulls_last=True),
                name="zerver_message_recipient_upper_subject",
            ),
        ),
        add_index(
            model_name="message",
            index=models.Index(
                "recipient",
                "subject",
                F("id").desc(nulls_last=True),
                name="zerver_message_recipient_subject",
            ),
        ),
    ]
