# Generated by Django 2.2.12 on 2020-04-30 00:35

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Upper


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0278_remove_userprofile_alert_words"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="message",
            index=models.Index(
                "recipient",
                Upper("subject"),
                F("id").desc(nulls_last=True),
                name="zerver_message_recipient_upper_subject",
            ),
        ),
        AddIndexConcurrently(
            model_name="message",
            index=models.Index(
                "recipient",
                "subject",
                F("id").desc(nulls_last=True),
                name="zerver_message_recipient_subject",
            ),
        ),
    ]
