# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0280_userprofile_presence_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='buddy_list_mode',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
