# Generated by Django 2.2.12 on 2020-04-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0280_userprofile_presence_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='add_custom_emoji_policy',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
