# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-25 23:47
from __future__ import unicode_literals

from django.db import migrations
from django.db.backends.postgresql_psycopg2.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def upgrade_add_custom_emoji_policy(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    Realm = apps.get_model('zerver', 'Realm')
    Realm.POLICY_MEMBERS_ONLY = 1
    Realm.POLICY_ADMINS_ONLY = 2
    Realm.objects.filter(add_emoji_by_admins_only=False) \
        .update(add_custom_emoji_policy=Realm.POLICY_MEMBERS_ONLY)
    Realm.objects.filter(add_emoji_by_admins_only=True) \
        .update(add_custom_emoji_policy=Realm.POLICY_ADMINS_ONLY)

class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0281_realm_add_custom_emoji_policy'),
    ]

    operations = [
        migrations.RunPython(upgrade_add_custom_emoji_policy,
                             reverse_code=migrations.RunPython.noop),
    ]
