# Generated by Django 2.2.12 on 2020-04-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0282_migrate_add_emoji_by_admins_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realm',
            name='add_emoji_by_admins_only',
        ),
    ]
