# Generated by Django 2.2.12 on 2020-05-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0282_remove_zoom_video_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_stream_admin',
            field=models.BooleanField(default=False),
        ),
    ]
