# Generated by Django 2.2.10 on 2020-04-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0284_convert_realm_admins_to_realm_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_topic_follow_audible_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_topic_follow_desktop_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_topic_follow_email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_topic_follow_push_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_topic_follow_wildcard_mentions_notify',
            field=models.BooleanField(default=True),
        ),
    ]
