# Generated by Django 2.2.13 on 2020-06-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0284_convert_realm_admins_to_realm_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sort_streams_by_activity',
            field=models.BooleanField(default=False),
        ),
    ]
