# Generated by Django 2.2.13 on 2020-06-17 06:26

from typing import Any, List

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0261_pregistrationuser_clear_invited_as_admin"),
        ("zerver", "0285_remove_realm_google_hangouts_domain"),
    ]

    operations: List[Any] = []
