# Generated by Django 2.2.13 on 2020-06-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0291_realm_retention_days_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiuseinvite",
            name="invited_as",
            field=models.PositiveSmallIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name="preregistrationuser",
            name="invited_as",
            field=models.PositiveSmallIntegerField(default=400),
        ),
    ]
