# Generated by Django 2.2.13 on 2020-07-03 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0293_update_invite_as_dict_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="pointer",
        ),
    ]
