# Generated by Django 2.2.14 on 2020-07-16 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0295_case_insensitive_email_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="short_name",
        ),
    ]
