# Generated by Django 2.2.13 on 2020-06-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0298_fix_realmauditlog_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="role",
            field=models.PositiveSmallIntegerField(db_index=True, default=50),
        ),
    ]
