# Generated by Django 2.2.14 on 2020-07-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0299_subscription_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedattachment",
            name="is_web_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attachment",
            name="is_web_public",
            field=models.BooleanField(default=False),
        ),
    ]
