# Generated by Django 2.2.14 on 2020-08-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0300_add_attachment_is_web_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='inline_url_embed_preview',
            field=models.BooleanField(default=True),
        ),
    ]
