# Generated by Django 2.2.10 on 2020-04-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0300_add_attachment_is_web_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistrationuser',
            name='user_avatar_url',
            field=models.TextField(null=True),
        ),
    ]
