# Generated by Django 2.2.14 on 2020-09-02 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0301_fix_unread_messages_in_deactivated_streams'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewRemoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.Message')),
            ],
            options={
                'abstract': False,
                'unique_together': {('message', 'url')},
            },
        ),
        migrations.CreateModel(
            name='ArchivedPreviewRemoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.ArchivedMessage')),
            ],
            options={
                'abstract': False,
                'unique_together': {('message', 'url')},
            },
        ),
    ]
