# Generated by Django 2.2.16 on 2020-10-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0303_realm_wildcard_mention_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='wildcard_mention_policy',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
