# Generated by Django 2.2.16 on 2020-10-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0303_realm_wildcard_mention_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_inline_image_preview',
            field=models.BooleanField(default=False),
        ),
    ]
