# Generated by Django 2.2.16 on 2020-10-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0303_realm_wildcard_mention_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realmfilter',
            name='url_format_string',
            field=models.TextField(),
        ),
    ]
