# Generated by Django 2.2.16 on 2020-11-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0304_remove_default_status_of_default_private_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='has_widget',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='has_widget',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
