# Generated by Django 2.2.16 on 2020-10-30 01:49

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0304_remove_default_status_of_default_private_streams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='authentication_methods',
            field=bitfield.models.BitField(['Google', 'Email', 'GitHub', 'LDAP', 'Dev', 'RemoteUser', 'AzureAD', 'SAML', 'GitLab', 'Apple', 'Facebook'], default=2147483647),
        ),
    ]
