# Generated by Django 2.2.14 on 2020-08-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0304_auto_20200826_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='inline_url_embed_preview',
            field=models.BooleanField(default=True),
        ),
    ]
