# Generated by Django 2.2.16 on 2020-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0304_remove_default_status_of_default_private_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevicetoken',
            name='notification_encryption_key',
            field=models.TextField(null=True),
        ),
    ]
