# Generated by Django 2.2.16 on 2020-10-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0304_remove_default_status_of_default_private_streams"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="deactivated_redirect",
            field=models.URLField(max_length=128, null=True),
        ),
    ]
