# Generated by Django 2.2.17 on 2020-12-20 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0307_rename_api_super_user_to_can_forge_sender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realm",
            options={},
        ),
    ]
