# Generated by Django 3.1.5 on 2021-01-10 11:30


from django.db import migrations


class Migration(migrations.Migration):
    """
    This empty migration is only retained for Django's tracking.
    """

    dependencies = [
        ("zerver", "0309_userprofile_can_create_users"),
    ]

    operations = []
