# Generated by Django 3.1.7 on 2021-03-05 07:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0310_jsonfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserExportConsent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("response", models.SmallIntegerField(default=0)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "export_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realmauditlog"
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "export_id")},
            },
        ),
    ]
