# Generated by Django 3.1.7 on 2021-03-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0310_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_view",
            field=models.TextField(default="recent_topics"),
        ),
    ]
