# Generated by Django 3.1.6 on 2021-02-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0310_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmauditlog",
            name="invite_only",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
