# Generated by Django 3.1.7 on 2021-03-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0310_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="final_escape_narrow",
            field=models.TextField(default=""),
        ),
    ]
