# Generated by Django 3.1.6 on 2021-03-03 15:29

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0311_userprofile_default_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="online_mention_policy",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="archivedusermessage",
            name="flags",
            field=bitfield.models.BitField(
                [
                    "read",
                    "starred",
                    "collapsed",
                    "mentioned",
                    "wildcard_mentioned",
                    "online_mentioned",
                    "summarize_in_home",
                    "summarize_in_stream",
                    "force_expand",
                    "force_collapse",
                    "has_alert_word",
                    "historical",
                    "is_private",
                    "active_mobile_push_notification",
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="flags",
            field=bitfield.models.BitField(
                [
                    "read",
                    "starred",
                    "collapsed",
                    "mentioned",
                    "wildcard_mentioned",
                    "online_mentioned",
                    "summarize_in_home",
                    "summarize_in_stream",
                    "force_expand",
                    "force_collapse",
                    "has_alert_word",
                    "historical",
                    "is_private",
                    "active_mobile_push_notification",
                ],
                default=0,
            ),
        ),
    ]
