# Generated by Django 3.1.5 on 2021-01-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0311_userprofile_default_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_user_active",
            field=models.BooleanField(null=True),
        ),
    ]
