# Generated by Django 3.1.7 on 2021-03-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0311_userprofile_default_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bot_description",
            field=models.TextField(default="", null=True),
        ),
    ]
