# Generated by Django 3.1.7 on 2021-03-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0311_userprofile_default_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="enable_notification_on_unsubscribe_stream",
            field=models.BooleanField(default=False),
        ),
    ]
