# Generated by Django 3.1.7 on 2021-04-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0313_finish_is_user_active_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bot_description",
            field=models.TextField(default="", null=True),
        ),
    ]
