# Generated by Django 3.1.6 on 2021-03-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0313_finish_is_user_active_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatus",
            name="status_emoji",
            field=models.CharField(default="", max_length=255),
        ),
    ]
