# Generated by Django 3.1.7 on 2021-04-01 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0317_migrate_to_invite_to_realm_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="invite_by_admins_only",
        ),
    ]
