# Generated by Django 3.1.7 on 2021-04-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0318_remove_realm_invite_by_admins_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="is_editable_for_all",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_editable_for_all",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
