# Generated by Django 3.1.7 on 2021-04-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0319_stream_default_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="color",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
