# Generated by Django 3.1.8 on 2021-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0321_userprofile_enable_marketing_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterUniqueTogether(
            name="usergroup",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="usergroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(active=True),
                fields=("name", "realm"),
                name="unique active user group per realm",
            ),
        ),
    ]
