# Generated by Django 3.2 on 2021-05-05 09:32

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0323_show_starred_message_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="authentication_methods",
            field=bitfield.models.BitField(
                [
                    "Google",
                    "Email",
                    "GitHub",
                    "LDAP",
                    "Dev",
                    "RemoteUser",
                    "AzureAD",
                    "SAML",
                    "GitLab",
                    "Apple",
                    "Facebook",
                ],
                default=2147483647,
            ),
        ),
    ]
