# Generated by Django 3.2.2 on 2021-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0324_fix_deletion_cascade_behavior"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="edit_history_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="message",
            name="edit_history_json",
            field=models.JSONField(default=list),
        ),
    ]
