# Generated by Django 3.2 on 2021-05-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0324_fix_deletion_cascade_behavior"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmauditlog",
            name="extra_data_json",
            field=models.JSONField(default=dict),
        ),
    ]
