# Generated by Django 3.2.2 on 2021-05-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0324_fix_deletion_cascade_behavior"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE zerver_scheduledemail ALTER COLUMN data TYPE jsonb USING data::jsonb;
            """,
            reverse_sql="ALTER TABLE zerver_scheduledemail ALTER COLUMN data TYPE TEXT USING data::TEXT;",
            state_operations=[
                migrations.AlterField(
                    model_name="scheduledemail",
                    name="data",
                    field=models.JSONField(default=dict),
                ),
            ],
        )
    ]
