# Generated by Django 3.2.2 on 2021-05-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0324_fix_deletion_cascade_behavior"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="customer_showcase_policy",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
