# Generated by Django 3.2.2 on 2021-05-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0324_fix_deletion_cascade_behavior"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                condition=models.Q(("active", True), ("is_user_active", True)),
                fields=["role", "recipient"],
                name="zerver_subscription_role_recipient_id_idx",
            ),
        ),
    ]
