# Generated by Django 3.2.2 on 2021-05-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0324_fix_deletion_cascade_behavior"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="jitsi_server_url",
            field=models.TextField(default=""),
        ),
    ]
