# Generated by Django 3.2.2 on 2021-05-11 10:00
import orjson
from django.db import migrations
from django.db.backends.postgresql.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def backfill_edit_messages(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    Message = apps.get_model("zerver", "Message")
    ArchivedMessage = apps.get_model("zerver", "ArchivedMessage")
    msg_models = [Message, ArchivedMessage]

    for model in msg_models:
        for message in model.objects.filter(edit_history__isnull=False):
            edit_history = orjson.loads(message.edit_history)

            edit_history_json = []

            for edit in edit_history:
                edit_history_json.append(edit)

            message.edit_history_json = edit_history_json
            message.save(update_fields=["edit_history_json"])


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0325_edit_history_json"),
    ]

    operations = [
        migrations.RunPython(
            backfill_edit_messages, reverse_code=migrations.RunPython.noop, elidable=True
        ),
    ]
