# Generated by Django 3.2 on 2021-05-07 14:43
import orjson
import yaml
from django.db import migrations
from django.db.backends.postgresql.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def backfill_extra_data(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    RealmAuditLog = apps.get_model("zerver", "RealmAuditLog")

    for data in RealmAuditLog.objects.filter(extra_data__isnull=False):
        try:
            extra_data_json = orjson.loads(data.extra_data)
        except orjson.JSONDecodeError:
            # There are a few places in the codebase where the extra_data dict
            # has not been serialized. One such example is in do_change_plan_type.
            # On executing orjson.loads on such values results in JSONDecodeError,
            # hence, we need to do the following to get the dict.
            extra_data_json = yaml.safe_load(data.extra_data)
        data.extra_data_json = extra_data_json
        data.save(update_fields=["extra_data_json"])


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0325_realmauditlog_extra_data_json"),
    ]

    operations = [
        migrations.RunPython(
            backfill_extra_data, reverse_code=migrations.RunPython.noop, elidable=True
        ),
    ]
