# Generated by Django 3.2.2 on 2021-05-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0326_backfill_edit_history_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivedmessage",
            name="edit_history",
        ),
        migrations.RemoveField(
            model_name="message",
            name="edit_history",
        ),
    ]
