# Generated by Django 3.2 on 2021-05-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0326_backfill_realmauditlog_extradata_to_json_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realmauditlog",
            name="extra_data",
        ),
    ]
