# Generated by Django 3.2.2 on 2021-06-03 15:06

from typing import Any, List

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0325_realm_jitsi_server_url"),
        ("zerver", "0326_alter_realm_authentication_methods"),
    ]

    operations: List[Any] = []
