# Generated by Django 3.2.2 on 2021-05-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0327_remove_edit_history_field_from_abstract_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="archivedmessage",
            old_name="edit_history_json",
            new_name="edit_history",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="edit_history_json",
            new_name="edit_history",
        ),
    ]
