# Generated by Django 3.1.8 on 2021-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0329_remove_realm_allow_community_topic_editing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmfilter",
            name="pattern",
            field=models.TextField(),
        ),
    ]
