# Generated by Django 3.2.4 on 2021-06-17 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0330_linkifier_pattern_validator"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmfilter",
            name="render_format_string",
            field=models.TextField(
                blank=True,
                default="",
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid render format string.",
                        regex="^([\\.\\/:\\w#?=&;!@~-]*%\\(([\\w-]+)\\)s)*[/\\w#?=&;~@-]*$",
                    )
                ],
            ),
        ),
    ]
