# Generated by Django 3.2.5 on 2021-07-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0333_alter_realm_org_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="email_notifications_batching_period_seconds",
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_notifications_batching_period_seconds",
            field=models.IntegerField(default=120),
        ),
    ]
