# Generated by Django 3.2.5 on 2021-07-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0334_email_notifications_batching_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_drafts_synchronization",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_drafts_synchronization",
            field=models.BooleanField(default=True),
        ),
    ]
