# Generated by Django 3.2.2 on 2021-05-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0336_userstatus_status_emoji"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="add_custom_emoji_policy",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
