# Generated by Django 3.2.5 on 2021-07-23 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0339_remove_realm_add_emoji_by_admins_only"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MutedTopic",
            new_name="UserTopic",
        ),
        migrations.AlterModelTable(
            name="usertopic",
            table="zerver_mutedtopic",
        ),
    ]
