# Generated by Django 3.2.5 on 2021-08-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0340_rename_mutedtopic_to_usertopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="is_system_group",
            field=models.BooleanField(default=False),
        ),
    ]
