# Generated by Django 3.2.5 on 2021-08-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0341_usergroup_is_system_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="demo_organization_scheduled_deletion_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
