# Generated by Django 3.2.6 on 2021-08-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0342_realm_demo_organization_scheduled_deletion_date"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="useractivityinterval",
            index=models.Index(
                fields=["user_profile", "end"],
                name="zerver_useractivityinterval_user_profile_id_end_bb3bfc37_idx",
            ),
        ),
    ]
