# Generated by Django 3.2.6 on 2021-08-31 19:17

from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index


class Migration(migrations.Migration):
    atomic = not settings.MIGRATIONS_ADD_REMOVE_INDEXES_CONCURRENTLY
    dependencies = [
        ("zerver", "0342_realm_demo_organization_scheduled_deletion_date"),
    ]

    operations = [
        add_index(
            model_name="useractivityinterval",
            index=models.Index(
                fields=["user_profile", "end"],
                name="zerver_useractivityinterval_user_profile_id_end_bb3bfc37_idx",
            ),
        ),
    ]
