# Generated by Django 3.2.6 on 2021-08-31 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0342_realm_demo_organization_scheduled_deletion_date"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="useractivityinterval",
            index_together={("user_profile", "end")},
        ),
    ]
