# Generated by Django 3.2.6 on 2021-09-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0344_alter_emojiset_default_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
