# Generated by Django 3.2.5 on 2021-07-29 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0347_realm_emoji_animated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertopic",
            old_name="date_muted",
            new_name="last_updated",
        ),
    ]
