# Generated by Django 3.2.5 on 2021-07-31 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0348_rename_date_muted_usertopic_last_updated"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="UserTopic",
            table=None,
        ),
    ]
