# Generated by Django 3.2.5 on 2021-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0349_alter_usertopic_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertopic",
            name="visibility_policy",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Muted topic"),
                    (2, "Unmuted topic in muted stream"),
                    (3, "Followed topic"),
                ],
                default=1,
            ),
        ),
    ]
