# Generated by Django 3.2.6 on 2021-09-17 18:34

from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index


class Migration(migrations.Migration):
    atomic = not settings.MIGRATIONS_ADD_REMOVE_INDEXES_CONCURRENTLY
    dependencies = [
        ("zerver", "0350_usertopic_visibility_policy"),
    ]

    operations = [
        add_index(
            model_name="usertopic",
            index=models.Index(
                fields=["stream", "topic_name", "visibility_policy", "user_profile"],
                name="zerver_usertopic_stream_topic_user_visibility_idx",
            ),
        ),
        add_index(
            model_name="usertopic",
            index=models.Index(
                fields=["user_profile", "visibility_policy", "stream", "topic_name"],
                name="zerver_usertopic_user_visibility_idx",
            ),
        ),
    ]
