# Generated by Django 3.2.6 on 2021-09-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0350_usertopic_visibility_policy"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="usertopic",
            index=models.Index(
                fields=["stream", "topic_name", "visibility_policy", "user_profile"],
                name="zerver_usertopic_stream_topic_user_visibility_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usertopic",
            index=models.Index(
                fields=["user_profile", "visibility_policy", "stream", "topic_name"],
                name="zerver_usertopic_user_visibility_idx",
            ),
        ),
    ]
