# Generated by Django 3.2.6 on 2021-09-17 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0352_migrate_twenty_four_hour_time_to_realmuserdefault"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="default_twenty_four_hour_time",
        ),
    ]
