# Generated by Django 3.2.4 on 2021-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0354_alter_realm_message_content_delete_limit_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="delete_own_message_policy",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
