# Generated by Django 3.2.7 on 2021-10-04 17:49

from typing import Any, List

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0358_split_create_stream_policy"),
        ("zerver", "0359_re2_linkifiers"),
    ]

    operations: List[Any] = []
