# Generated by Django 3.2.7 on 2021-10-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0360_merge_0358_0359"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="create_web_public_stream_policy",
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
