# Generated by Django 3.2.7 on 2021-10-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0361_realm_create_web_public_stream_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="send_private_typing_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="send_stream_typing_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="send_private_typing_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="send_stream_typing_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
