# Generated by Django 3.2.7 on 2021-10-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0362_send_typing_notifications_user_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="send_read_receipts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="send_read_receipts",
            field=models.BooleanField(default=True),
        ),
    ]
