# Generated by Django 3.2.8 on 2021-10-20 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0367_scimclient"),
    ]

    operations = []
