# Generated by Django 3.2.8 on 2021-11-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0368_alter_realmfilter_url_format_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="signup_notifications_include_referrer",
            field=models.BooleanField(default=True),
        ),
    ]
