# Generated by Django 3.2.9 on 2021-11-09 15:23

from typing import Any, List

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0369_add_escnav_default_display_user_setting"),
        ("zerver", "0369_realm_signup_notifications_include_referrer"),
    ]

    operations: List[Any] = []
