# Generated by Django 3.2.7 on 2021-10-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0369_add_escnav_default_display_user_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="enable_spectator_access",
            field=models.BooleanField(default=False),
        ),
    ]
