# Generated by Django 3.2.8 on 2021-11-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0369_add_escnav_default_display_user_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='muted_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usertopic',
            name='remind_datetime',
            field=models.DateField(null=True),
        ),
    ]
