# Generated by Django 3.2.9 on 2021-12-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0370_realm_guidelines_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='guidelines_url',
            field=models.TextField(default=''),
        ),
    ]
