# Generated by Django 3.2.9 on 2021-11-23 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0370_realm_enable_spectator_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preregistrationuser",
            name="invited_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
