# Generated by Django 3.2.9 on 2021-11-30 04:42

from typing import Any, List

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0370_merge_20211109_1523"),
        ("zerver", "0370_realm_enable_spectator_access"),
    ]

    operations: List[Any] = []
