# Generated by Django 3.2.9 on 2022-02-26 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0370_realm_enable_spectator_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realmuserdefault',
            name='realm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zerver.realm'),
        ),
    ]
