# Generated by Django 3.2.9 on 2021-12-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0371_alter_realm_guidelines_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='guidelines_url',
            field=models.URLField(null=True),
        ),
    ]
