# Generated by Django 3.2.9 on 2021-12-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0371_invalid_characters_in_topics"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="realmemoji",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deactivated", False)),
                fields=("realm", "name"),
                name="unique_realm_emoji_when_false_deactivated",
            ),
        ),
    ]
