# Generated by Django 3.2.10 on 2022-01-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0374_backfill_user_delete_realmauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='allow_invite_signup_private_msg',
            field=models.BooleanField(default=False),
        ),
    ]
