# Generated by Django 3.2.10 on 2022-01-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0375_realm_allow_invite_signup_private_msg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="allow_invite_signup_private_msg",
        ),
        migrations.AddField(
            model_name="realm",
            name="send_invite_signup_private_message",
            field=models.BooleanField(default=True),
        ),
    ]
