# Generated by Django 3.2.10 on 2022-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0375_invalid_characters_in_stream_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="receive_private_message_on_invitee_signup",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_private_message_on_invitee_signup",
            field=models.BooleanField(default=True),
        ),
    ]
