# Generated by Django 3.2.11 on 2022-02-19 17:33

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0376_set_realmemoji_author_and_reupload_realmemoji"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="message",
            index=GinIndex(
                fields=["subject"],
                name="zerver_message_subject_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
