# Generated by Django 3.2.10 on 2022-01-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0376_realm_allow_invite_signup_private_msg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="send_invite_signup_private_message",
        ),
    ]
