# Generated by Django 3.2.10 on 2022-01-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0377_remove_realm_send_invite_signup_private_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmuserdefault',
            name='send_invite_signup_private_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='send_invite_signup_private_message',
            field=models.BooleanField(default=True),
        ),
    ]
