# Generated by Django 3.2.12 on 2022-03-05 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0377_message_edit_history_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmuserdefault",
            name="realm",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
            ),
        ),
    ]
