# Generated by Django 3.2.12 on 2022-03-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0378_alter_realmuserdefault_realm"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnedTopic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("topic_name", models.CharField(max_length=60)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.stream"
                    ),
                ),
            ],
        ),
    ]
