# Generated by Django 3.2.12 on 2022-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0378_alter_realmuserdefault_realm"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
