# Generated by Django 3.2.11 on 2022-03-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0382_create_role_based_system_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="signup_notifications_include_referrer",
            field=models.BooleanField(default=True),
        ),
    ]
