# Generated by Django 3.2.12 on 2022-03-17 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0383_revoke_invitations_from_deactivated_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedattachment",
            name="realm",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="realm",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"),
        ),
    ]
