# Generated by Django 3.2.12 on 2022-04-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0387_reupload_realmemoji_again"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="jitsi_server_url",
            field=models.TextField(default=None, null=True),
        ),
    ]
