# Generated by Django 3.2.12 on 2022-04-09 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0387_reupload_realmemoji_again"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationuser",
            name="created_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
