# Generated by Django 3.2.12 on 2022-04-03 17:22

from django.db import migrations, models
from django.db.backends.postgresql.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def update_null_fields_to_false(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    Stream = apps.get_model("zerver", "Stream")
    Stream.objects.filter(invite_only=None).update(invite_only=False)


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0387_reupload_realmemoji_again"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="invite_only",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_null_fields_to_false),
    ]
