# Generated by Django 3.2.12 on 2022-03-25 16:50

from django.db import migrations, models
from django.db.backends.postgresql.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def update_null_fields_to_false(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    Subscription = apps.get_model("zerver", "Subscription")
    Subscription.objects.filter(is_muted=None).update(is_muted=False)


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0388_alter_stream_invite_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="is_muted",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_null_fields_to_false),
    ]
