# Generated by Django 3.2.12 on 2022-03-23 01:45

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0393_realm_want_advertise_in_communities_directory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedusermessage",
            name="flags",
            field=bitfield.models.BitField(
                [
                    "read",
                    "starred",
                    "collapsed",
                    "mentioned",
                    "wildcard_mentioned",
                    "summarize_in_home",
                    "summarize_in_stream",
                    "force_expand",
                    "force_collapse",
                    "has_alert_word",
                    "historical",
                    "is_private",
                    "active_mobile_push_notification",
                    "embed_hidden",
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="flags",
            field=bitfield.models.BitField(
                [
                    "read",
                    "starred",
                    "collapsed",
                    "mentioned",
                    "wildcard_mentioned",
                    "summarize_in_home",
                    "summarize_in_stream",
                    "force_expand",
                    "force_collapse",
                    "has_alert_word",
                    "historical",
                    "is_private",
                    "active_mobile_push_notification",
                    "embed_hidden",
                ],
                default=0,
            ),
        ),
    ]
