# Generated by Django 3.2.13 on 2022-05-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0393_realm_want_advertise_in_communities_directory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="want_advertise_in_communities_directory",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
