# Generated by Django 3.2.13 on 2022-05-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0393_realm_want_advertise_in_communities_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="display_organization_name",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="display_organization_name",
            field=models.BooleanField(default=True),
        ),
    ]
