# Generated by Django 4.0.6 on 2022-07-21 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0398_tsvector_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationuser",
            name="multiuse_invite",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="zerver.multiuseinvite"
            ),
        ),
    ]
