# Generated by Django 4.0.6 on 2022-07-25 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0399_preregistrationuser_multiuse_invite"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealmReactivationStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
    ]
