# Generated by Django 4.0.6 on 2022-08-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0401_migrate_old_realm_reactivation_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertopic",
            name="visibility_policy",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Muted topic"),
                    (2, "Unmuted topic in muted stream"),
                    (3, "Followed topic"),
                    (0, "User's default policy for the stream."),
                ],
                default=1,
            ),
        ),
    ]
