# Generated by Django 4.0.6 on 2022-08-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0403_create_role_based_groups_for_internal_realms"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="enable_read_receipts",
            field=models.BooleanField(default=False),
        ),
    ]
