# Generated by Django 4.0.6 on 2022-08-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0405_alter_archivedmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
