# Generated by Django 4.0.6 on 2022-08-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0406_alter_message_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='topic',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
