# Generated by Django 4.0.6 on 2022-08-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0407_alter_draft_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
