# Generated by Django 3.2.13 on 2022-06-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0407_userprofile_user_list_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="can_remove_subscribers_group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.RESTRICT, to="zerver.usergroup"
            ),
        ),
    ]
