# Generated by Django 4.0.6 on 2022-07-22 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0409_set_default_for_can_remove_subscribers_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="can_remove_subscribers_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="zerver.usergroup"
            ),
        ),
    ]
