# Generated by Django 4.0.7 on 2022-09-22 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0413_set_presence_enabled_false_for_user_status_away"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstatus",
            name="status",
        ),
    ]
