# Generated by Django 4.0.7 on 2022-09-24 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0414_remove_userstatus_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SCIMClient",
        ),
    ]
