# Generated by Django 4.0.7 on 2022-09-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0419_backfill_message_realm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedmessage",
            name="realm",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"),
        ),
        migrations.AlterField(
            model_name="message",
            name="realm",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"),
        ),
    ]
