# Generated by Django 4.0.7 on 2022-09-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0420_alter_archivedmessage_realm_alter_message_realm"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
