# Generated by Django 3.2.9 on 2021-11-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0422_multiuseinvite_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="realm_icon_as_favicon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="realm_icon_as_favicon",
            field=models.BooleanField(default=False),
        ),
    ]
