# Generated by Django 4.1.3 on 2022-12-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0422_multiuseinvite_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamTopic",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("topic_name", models.CharField(max_length=60)),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.stream"
                    ),
                ),
            ],
            options={
                "unique_together": {("stream", "topic_name")},
            },
        ),
    ]
