# Generated by Django 3.2.5 on 2021-07-26 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0422_multiuseinvite_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtAuthId",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ldap", models.TextField(null=True)),
                ("saml", models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ext_auth_id",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="zerver.extauthid"
            ),
        ),
    ]
