# Generated by Django 4.1.2 on 2022-11-01 12:55

from django.db import migrations
from django.db.backends.postgresql.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def rename_no_topic_to_general_chat(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Message = apps.get_model("zerver", "Message")
    Message.objects.filter(subject="(no topic)").update(subject="general chat")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0422_multiuseinvite_status"),
    ]

    operations = [
        migrations.RunPython(
            rename_no_topic_to_general_chat,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
