# Generated by Django 4.1.5 on 2023-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0424_realm_move_messages_within_stream_limit_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="move_messages_between_streams_limit_seconds",
            field=models.PositiveIntegerField(default=604800, null=True),
        ),
    ]
