# Generated by Django 3.2.8 on 2021-10-28 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0427_migrate_to_user_level_email_address_visibility_setting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="email_address_visibility",
        ),
    ]
