# Generated by Django 4.1.7 on 2023-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0432_alter_and_migrate_realm_name_in_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationuser",
            name="send_notification",
            field=models.BooleanField(default=True),
        ),
    ]
