# Generated by Django 4.1.7 on 2023-03-22 08:15

from django.db import migrations, models

drop_trigger_sql = """DROP TRIGGER zerver_message_update_search_tsvector_async ON zerver_message;"""
create_trigger_sql = """ CREATE TRIGGER zerver_message_update_search_tsvector_async
BEFORE INSERT OR UPDATE OF subject, rendered_content ON zerver_message
FOR EACH ROW EXECUTE PROCEDURE append_to_fts_update_log(); """


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0432_alter_and_migrate_realm_name_in_notifications"),
    ]

    operations = [
        migrations.RunSQL(sql=drop_trigger_sql),
        migrations.AlterField(
            model_name="archivedmessage",
            name="subject",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="draft",
            name="topic",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="scheduledmessage",
            name="subject",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="usertopic",
            name="topic_name",
            field=models.CharField(max_length=200),
        ),
        migrations.RunSQL(sql=create_trigger_sql),
    ]
