# Generated by Django 3.2.11 on 2022-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0432_alter_and_migrate_realm_name_in_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="emoji_animation_config",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emoji_animation_config",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
