# Generated by Django 4.1.7 on 2023-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0433_preregistrationrealm"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationuser",
            name="send_notification",
            field=models.BooleanField(default=True),
        ),
    ]
