# Generated by Django 4.1.7 on 2023-03-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0434_create_nobody_system_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationuser",
            name="send_notification",
            field=models.BooleanField(default=True),
        ),
    ]
