# Generated by Django 4.2 on 2023-04-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0434_create_nobody_system_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="default_topic",
            field=models.TextField(default=""),
        ),
    ]
