# Generated by Django 4.1.7 on 2023-03-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0434_create_nobody_system_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="scheduled_deletion_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
