# Generated by Django 4.1.5 on 2023-01-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0434_create_nobody_system_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="rendered_content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
