# Generated by Django 4.1.7 on 2023-04-05 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0434_create_nobody_system_group"),
        ("zerver", "0435_userprofile_deactivation_reason"),
    ]

    operations = []
