# Generated by Django 4.2 on 2023-04-16 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0436_realmauthenticationmethods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="authentication_methods",
        ),
    ]
