# Generated by Django 4.1.7 on 2023-04-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0437_remove_realm_authentication_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_mark_read_on_scroll_policy",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_mark_read_on_scroll_policy",
            field=models.SmallIntegerField(default=1),
        ),
    ]
