# Generated by Django 4.0.7 on 2022-10-02 20:50

from django.db import migrations, models

from zerver.models import url_template_validator


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0439_fix_deleteduser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmfilter",
            name="url_template",
            field=models.TextField(validators=[url_template_validator], null=True),
        ),
        migrations.AlterField(
            model_name="realmfilter",
            name="url_format_string",
            field=models.TextField(null=True, blank=True),
        ),
    ]
