# Generated by Django 4.1.6 on 2023-02-09 17:00

from typing import Any, Dict, Optional

import django.contrib.postgres.fields
from django.db import migrations, models
from django.db.backends.postgresql.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

import zerver.models

# We include a copy of this structure as it was at the time this
# migration was merged, since future should not impact the migration.
VIDEO_CHAT_PROVIDERS = {
    "disabled": {
        "name": "None",
        "id": 0,
    },
    "jitsi_meet": {
        "name": "Jitsi Meet",
        "id": 1,
    },
    # ID 2 was used for the now-deleted Google Hangouts.
    # ID 3 reserved for optional Zoom, see below.
    # ID 4 reserved for optional BigBlueButton, see below.
}


def get_video_chat_provider_detail(
    providers_dict: Dict[str, Dict[str, Any]],
    p_name: Optional[str] = None,
    p_id: Optional[int] = None,
) -> Dict[str, Any]:
    for provider in providers_dict.values():
        if p_name and provider["name"] == p_name:
            return provider
        if p_id and provider["id"] == p_id:
            return provider
    return {}


def update_existing_video_chat_provider_values(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Realm = apps.get_model("zerver", "Realm")

    for realm in Realm.objects.all():
        realm.video_chat_provider = get_video_chat_provider_detail(
            VIDEO_CHAT_PROVIDERS, p_name=realm.old_video_chat_provider
        )["id"]
        realm.save(update_fields=["video_chat_provider"])


def reverse_code(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Realm = apps.get_model("zerver", "Realm")

    for realm in Realm.objects.all():
        realm.old_video_chat_provider = get_video_chat_provider_detail(
            VIDEO_CHAT_PROVIDERS, p_id=realm.video_chat_provider
        )["name"]
        realm.save(update_fields=["old_video_chat_provider"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0442_remove_realmfilter_url_format_string"),
    ]

    operations = [
        migrations.RenameField(
            model_name="realm",
            old_name="video_chat_provider",
            new_name="old_video_chat_provider",
        ),
        migrations.AddField(
            model_name="realm",
            name="video_chat_provider",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                default=zerver.models.Realm.get_video_chat_provider_default,
                size=None,
            ),
        ),
        migrations.RunPython(
            update_existing_video_chat_provider_values, reverse_code=reverse_code, elidable=True
        ),
        migrations.RemoveField(
            model_name="realm",
            name="old_video_chat_provider",
        ),
    ]
