# Generated by Django 4.2 on 2023-04-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0445_drop_userpresenceold"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="default_topic",
            field=models.TextField(default=""),
        ),
    ]
