# Generated by Django 4.2 on 2023-05-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0446_realmauditlog_zerver_realmauditlog_user_subscriptions_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="scheduled_messages",
            field=models.ManyToManyField(to="zerver.scheduledmessage"),
        ),
        migrations.AddField(
            model_name="scheduledmessage",
            name="has_attachment",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
