# Generated by Django 4.2 on 2023-05-09 00:58

from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index


class Migration(migrations.Migration):
    atomic = not settings.MIGRATIONS_ADD_REMOVE_INDEXES_CONCURRENTLY
    dependencies = [
        ("zerver", "0448_scheduledmessage_new_fields"),
    ]

    operations = [
        add_index(
            model_name="scheduledmessage",
            index=models.Index(
                condition=models.Q(("delivered", False), ("failed", False)),
                fields=["scheduled_timestamp"],
                name="zerver_unsent_scheduled_messages_by_time",
            ),
        ),
        add_index(
            model_name="scheduledmessage",
            index=models.Index(
                condition=models.Q(("delivered", False)),
                fields=["sender", "delivery_type", "scheduled_timestamp"],
                name="zerver_unsent_scheduled_messages_by_user",
            ),
        ),
    ]
