# Generated by Django 4.2 on 2023-05-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0449_scheduledmessage_zerver_unsent_scheduled_messages_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="direct_message_initiator_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="direct_message_permission_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
