# Generated by Django 4.2.1 on 2023-05-18 15:20


from django.db import migrations, models

from zerver.lib.utils import generate_api_key


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0450_backfill_subscription_auditlogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="api_key",
            field=models.CharField(default=generate_api_key, max_length=32, unique=True),
        ),
    ]
