# Generated by Django 4.2.1 on 2023-05-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0451_add_userprofile_api_key_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="customprofilefield",
            name="editable_by_user",
            field=models.BooleanField(default=True),
        ),
    ]
