# Generated by Django 4.0.7 on 2022-09-30 20:25

import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0451_add_userprofile_api_key_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmauditlog",
            name="extra_data_json",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
