# Generated by Django 4.2.1 on 2023-06-10 09:42

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0453_alter_archivedmessage_subject_alter_draft_topic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tagulous_Message_topic_tags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(
                        default=0, help_text="Internal counter of how many times this tag is in use"
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False, help_text="Will not be deleted when the count reaches 0"
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("slug",)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name="message",
            name="topic_tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                help_text="Enter a comma-separated tag string",
                to="zerver.tagulous_message_topic_tags",
            ),
        ),
    ]
