# Generated by Django 4.2.1 on 2023-06-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0455_set_default_for_can_mention_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergroup",
            name="can_mention_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="zerver.usergroup"
            ),
        ),
    ]
