# Generated by Django 4.2.2 on 2023-07-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0457_backfill_scheduledmessagenotificationemail_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="create_multiuse_invite_to_realm_policy",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
