# Generated by Django 4.1.3 on 2022-11-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0457_backfill_scheduledmessagenotificationemail_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmauditlog",
            name="modified_user_group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="zerver.usergroup"
            ),
        ),
    ]
