# Generated by Django 4.2.2 on 2023-06-28 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0457_backfill_scheduledmessagenotificationemail_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealmExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("type", models.PositiveSmallIntegerField(default=1)),
                ("success", models.BooleanField(default=None, null=True)),
                ("export_path", models.TextField(default=None, null=True)),
                ("date_started", models.DateTimeField(default=None, null=True)),
                ("date_finished", models.DateTimeField(default=None, null=True)),
                ("date_expires", models.DateTimeField(default=None, null=True)),
                ("date_deleted", models.DateTimeField(default=None, null=True)),
                ("version", models.CharField(max_length=100)),
                ("sha256sum_hex", models.CharField(default=None, max_length=64, null=True)),
                ("compressed_size_bytes", models.PositiveIntegerField(default=None, null=True)),
                (
                    "acting_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consent_message",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="zerver.message"
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
    ]
