# Generated by Django 4.2.2 on 2023-07-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0459_remove_invalid_characters_from_user_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushdevicetoken",
            name="notification_encryption_key",
            field=models.BinaryField(max_length=16, null=True),
        ),
    ]
