# Generated by Django 4.2.3 on 2023-08-04 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0464_remove_realmplayground_url_prefix"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE zerver_scheduledmessagenotificationemail
            SET trigger = 'direct_message'
            WHERE trigger = 'private_message';
            """,
            reverse_sql="""
            UPDATE zerver_scheduledmessagenotificationemail
            SET trigger = 'private_message'
            WHERE trigger = 'direct_message';
            """,
        ),
    ]
