# Generated by Django 4.2.1 on 2023-05-31 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0468_rename_followup_day_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="create_multiuse_invite_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
