# Generated by Django 4.2.3 on 2023-08-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0468_rename_followup_day_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="edit_history_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="message",
            name="edit_history_json",
            field=models.JSONField(default=list),
        ),
    ]
