# Generated by Django 4.2.4 on 2023-08-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0473_remove_message_non_realm_id_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_stream_unreads_count_display_policy",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_stream_unreads_count_display_policy",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
