# Generated by Django 4.2.2 on 2023-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0474_realmuserdefault_web_stream_unreads_count_display_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="scheduled_deletion_date",
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
