# Generated by Django 4.2.4 on 2023-08-21 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0474_realmuserdefault_web_stream_unreads_count_display_policy_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userprofile",
            managers=[],
        ),
    ]
