# Generated by Django 4.2.5 on 2023-10-02 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0476_realmuserdefault_automatically_follow_topics_policy_and_more"),
    ]
