# Generated by Django 4.2.5 on 2023-10-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0477_alter_realmuserdefault_automatically_follow_topics_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="edit_history_entries",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="message",
            name="edit_history_entries",
            field=models.JSONField(default=list),
        ),
    ]
