# Generated by Django 4.2.5 on 2023-09-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0477_alter_realmuserdefault_automatically_follow_topics_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
