# Generated by Django 4.2.5 on 2023-09-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0477_alter_realmuserdefault_automatically_follow_topics_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="enable_guest_user_indicator",
            field=models.BooleanField(default=True),
        ),
    ]
