# Generated by Django 4.2.5 on 2023-10-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0478_realm_enable_guest_user_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="uuid",
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="realm",
            name="uuid_owner_secret",
            field=models.TextField(null=True),
        ),
    ]
