# Generated by Django 4.2.5 on 2023-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0478_realm_enable_guest_user_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="signup_notifications_include_referrer",
            field=models.BooleanField(default=True),
        ),
    ]
