# Generated by Django 4.2.5 on 2023-10-06 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0479_backfill_edit_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivedmessage",
            name="edit_history",
        ),
        migrations.RemoveField(
            model_name="message",
            name="edit_history",
        ),
    ]
