# Generated by Django 4.2.6 on 2023-10-20 23:43

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

AUTOMATICALLY_CHANGE_VISIBILITY_POLICY_ON_SEND = 2
AUTOMATICALLY_CHANGE_VISIBILITY_POLICY_ON_INITIATION = 3


def set_default_user_topic_policies(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    RealmUserDefault = apps.get_model("zerver", "RealmUserDefault")
    UserProfile = apps.get_model("zerver", "UserProfile")

    RealmUserDefault.objects.update(
        automatically_follow_topics_policy=AUTOMATICALLY_CHANGE_VISIBILITY_POLICY_ON_INITIATION
    )
    UserProfile.objects.update(
        automatically_follow_topics_policy=AUTOMATICALLY_CHANGE_VISIBILITY_POLICY_ON_INITIATION
    )

    RealmUserDefault.objects.update(
        automatically_unmute_topics_in_muted_streams_policy=AUTOMATICALLY_CHANGE_VISIBILITY_POLICY_ON_SEND
    )
    UserProfile.objects.update(
        automatically_unmute_topics_in_muted_streams_policy=AUTOMATICALLY_CHANGE_VISIBILITY_POLICY_ON_SEND
    )


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0481_alter_realm_uuid_alter_realm_uuid_owner_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmuserdefault",
            name="automatically_follow_topics_policy",
            field=models.PositiveSmallIntegerField(
                default=AUTOMATICALLY_CHANGE_VISIBILITY_POLICY_ON_INITIATION
            ),
        ),
        migrations.AlterField(
            model_name="realmuserdefault",
            name="automatically_unmute_topics_in_muted_streams_policy",
            field=models.PositiveSmallIntegerField(
                default=AUTOMATICALLY_CHANGE_VISIBILITY_POLICY_ON_SEND
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="automatically_follow_topics_policy",
            field=models.PositiveSmallIntegerField(
                default=AUTOMATICALLY_CHANGE_VISIBILITY_POLICY_ON_INITIATION
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="automatically_unmute_topics_in_muted_streams_policy",
            field=models.PositiveSmallIntegerField(
                default=AUTOMATICALLY_CHANGE_VISIBILITY_POLICY_ON_SEND
            ),
        ),
        migrations.RunPython(
            set_default_user_topic_policies,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
