# Generated by Django 4.2.6 on 2023-10-12 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0481_alter_realm_uuid_alter_realm_uuid_owner_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="creation_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
