# Generated by Django 4.2.6 on 2023-10-23 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0481_alter_realm_uuid_alter_realm_uuid_owner_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("topic_name", models.CharField(max_length=60)),
                ("locked", models.BooleanField(default=False)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.stream"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                models.F("realm_id"),
                models.F("stream_id"),
                django.db.models.functions.text.Lower("topic_name"),
                name="zerver_topic_unique",
            ),
        ),
    ]
