# Generated by Django 4.2.6 on 2023-10-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0482_automatically_follow_unmute_topics_policy_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="signup_notifications_include_referrer",
            field=models.BooleanField(default=True),
        ),
    ]
