# Generated by Django 4.2.6 on 2023-10-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0482_scheduledmessage_creation_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="reminder_target_message_id",
            field=models.IntegerField(null=True),
        ),
    ]
