# Generated by Django 4.1.7 on 2023-03-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0486_clear_old_data_for_unused_usermessage_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_access_all_users_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
