# Generated by Django 4.2.7 on 2023-11-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0490_renumber_options_desktop_icon_count_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmuserdefault",
            name="web_home_view",
            field=models.TextField(default="inbox"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="web_home_view",
            field=models.TextField(default="inbox"),
        ),
    ]
