# Generated by Django 4.2.7 on 2023-11-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0491_alter_realmuserdefault_web_home_view_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="signup_notifications_include_referrer",
            field=models.BooleanField(default=True),
        ),
    ]
