# Generated by Django 4.2.7 on 2023-11-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0491_alter_realmuserdefault_web_home_view_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="push_notifications_enabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="realm",
            name="push_notifications_enabled_end_timestamp",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
