# Generated by Django 4.2.7 on 2023-12-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0491_alter_realmuserdefault_web_home_view_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="add_custom_welcome_message_for_new_users",
            field=models.BooleanField(default=False),
        ),
    ]
