# Generated by Django 4.2.7 on 2023-12-01 06:55

from django.db import migrations

from zerver.lib.migrate import rename_indexes_constraints


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0492_realm_push_notifications_enabled_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RenameField(
                    model_name="UserHotspot", old_name="hotspot", new_name="onboarding_step"
                ),
                migrations.RunPython(
                    rename_indexes_constraints(
                        "zerver_userhotspot",
                        "zerver_onboardingstep",
                    ),
                    reverse_code=rename_indexes_constraints(
                        "zerver_onboardingstep",
                        "zerver_userhotspot",
                    ),
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name="UserHotspot", old_name="hotspot", new_name="onboarding_step"
                ),
                migrations.RenameModel(old_name="UserHotspot", new_name="OnboardingStep"),
            ],
        ),
    ]
