# Generated by Django 4.2.7 on 2023-12-08 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0492_realm_add_custom_welcome_message_for_new_users"),
        ("zerver", "0493_rename_userhotspot_to_onboardingstep"),
    ]

    operations = []
