# Generated by Django 4.2.8 on 2023-12-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0494_realmuserdefault_automatically_follow_topics_where_mentioned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="read_by_sender",
            field=models.BooleanField(null=True),
        ),
    ]
