# Generated by Django 4.2.5 on 2023-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0496_alter_scheduledmessage_read_by_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="user_groups",
            field=models.ManyToManyField(to="zerver.usergroup"),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="user_groups",
            field=models.ManyToManyField(to="zerver.usergroup"),
        ),
    ]
