# Generated by Django 4.2.8 on 2024-01-10 13:38

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0496_alter_scheduledmessage_read_by_sender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("pinned", models.BooleanField(default=False)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.stream"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        models.F("realm"),
                        models.F("stream"),
                        django.db.models.functions.text.Upper("name"),
                        name="zerver_pinnedtopic_stream_topic",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                models.F("realm"),
                models.F("stream"),
                django.db.models.functions.text.Lower("name"),
                name="case_insensitive_topic_uniq",
            ),
        ),
    ]
