# Generated by Django 4.2.9 on 2024-02-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0496_alter_scheduledmessage_read_by_sender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="realm",
            old_name="notifications_stream",
            new_name="new_stream_announcements_stream",
        ),
    ]
