# Generated by Django 4.2.10 on 2024-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0500_realm_zulip_update_announcements_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertword",
            name="follow_topic_containing_alert_word",
            field=models.BooleanField(default=False),
        ),
    ]
