# Generated by Django 4.2.10 on 2024-03-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0500_realm_zulip_update_announcements_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_left_sidebar_unreads_count_summary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_left_sidebar_unreads_count_summary",
            field=models.BooleanField(default=False),
        ),
    ]
