# Generated by Django 4.2.10 on 2024-03-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0501_mark_introduce_zulip_view_modals_as_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_dm_reaction_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="streams_reaction_notification",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_dm_reaction_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="streams_reaction_notification",
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
