# Generated by Django 4.2.10 on 2024-03-19 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0501_delete_dangling_usermessages"),
        ("zerver", "0501_mark_introduce_zulip_view_modals_as_read"),
    ]

    operations = []
