# Generated by Django 4.2.9 on 2024-02-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0502_merge_20240319_2236"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="zulip_update_announcements_level",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
