# Generated by Django 4.2.10 on 2024-03-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0503_realm_zulip_update_announcements_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="customprofilefield",
            name="required",
            field=models.BooleanField(default=False),
        ),
    ]
