# Generated by Django 4.2.11 on 2024-03-26 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0504_customprofilefield_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatus",
            name="status_end_time",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="ScheduledUserStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scheduled_timestamp", models.DateTimeField(db_index=True)),
                ("data", models.TextField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.client"
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scheduled_timestamp"], name="zerver_scheduled_status_removal"
                    )
                ],
            },
        ),
    ]
