# Generated by Django 4.2.11 on 2024-03-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0504_customprofilefield_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="custom_welcome_message_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="realm",
            name="custom_welcome_message_text",
            field=models.TextField(default=""),
        ),
    ]
