# Generated by Django 4.2.11 on 2024-03-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0504_customprofilefield_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="customprofilefield",
            name="rendered_hint",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="customprofilefield",
            name="rendered_name",
            field=models.TextField(default=None, null=True),
        ),
    ]
