# Generated by Django 4.2.10 on 2024-03-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0504_customprofilefield_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="subscribe_to_default_streams",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="subscribe_to_default_streams",
            field=models.BooleanField(default=True),
        ),
    ]
