# Generated by Django 4.2.11 on 2024-03-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0504_customprofilefield_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_font_size_px",
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_line_height_percent",
            field=models.PositiveSmallIntegerField(default=122),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_font_size_px",
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_line_height_percent",
            field=models.PositiveSmallIntegerField(default=122),
        ),
    ]
