# Generated by Django 4.2.11 on 2024-03-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0504_customprofilefield_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationuser",
            name="send_notification",
            field=models.BooleanField(default=True),
        ),
    ]
