# Generated by Django 4.2.11 on 2024-03-22 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0504_customprofilefield_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="creator",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
