# Generated by Django 4.2.11 on 2024-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0505_realmuserdefault_web_font_size_px_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ban_reason",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
    ]
