# Generated by Django 4.2.11 on 2024-03-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0505_realmuserdefault_web_font_size_px_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="require_unique_names",
            field=models.BooleanField(default=False),
        ),
    ]
