# Generated by Django 4.2.10 on 2024-03-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0506_realm_require_unique_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="upload_quota_gb",
        ),
        migrations.AddField(
            model_name="realm",
            name="custom_upload_quota_gb",
            field=models.IntegerField(null=True),
        ),
    ]
