# Generated by Django 4.2.12 on 2024-04-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0509_fix_emoji_metadata"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="realmauditlog",
            index=models.Index(
                fields=["realm", "event_type", "event_time"],
                name="zerver_realmauditlog_realm__event_type__event_time",
            ),
        ),
    ]
