# Generated by Django 4.2.12 on 2024-04-17 10:33

from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index


class Migration(migrations.Migration):
    atomic = not settings.MIGRATIONS_ADD_REMOVE_INDEXES_CONCURRENTLY

    dependencies = [
        ("zerver", "0509_fix_emoji_metadata"),
    ]

    operations = [
        add_index(
            model_name="realmauditlog",
            index=models.Index(
                fields=["realm", "event_type", "event_time"],
                name="zerver_realmauditlog_realm__event_type__event_time",
            ),
        ),
    ]
