# Generated by Django 5.0.5 on 2024-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0511_stream_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="signup_notifications_include_referrer",
            field=models.BooleanField(default=True),
        ),
    ]
