# Generated by Django 4.2.12 on 2024-04-17 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0513_copy_groups_data_to_named_user_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmauditlog",
            name="modified_user_group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="zerver.namedusergroup"
            ),
        ),
    ]
