# Generated by Django 4.2.12 on 2024-04-19 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0514_update_usergroup_foreign_keys_to_namedusergroup"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usergroup",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="can_mention_group",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="description",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="is_system_group",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="name",
        ),
        migrations.RenameField(
            model_name="namedusergroup",
            old_name="named_group_can_mention_group",
            new_name="can_mention_group",
        ),
        migrations.RenameField(
            model_name="namedusergroup",
            old_name="named_group_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="namedusergroup",
            old_name="named_group_is_system_group",
            new_name="is_system_group",
        ),
        migrations.RenameField(
            model_name="namedusergroup",
            old_name="named_group_name",
            new_name="name",
        ),
        migrations.AlterUniqueTogether(
            name="namedusergroup",
            unique_together={("realm_for_sharding", "name")},
        ),
    ]
