# Generated by Django 4.2.13 on 2024-06-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0517_resort_edit_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="paid_subscription",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="paid_subscription_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
