# Generated by Django 5.0.6 on 2024-05-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0518_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivetransaction",
            name="restored_timestamp",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
