# Generated by Django 5.0.6 on 2024-05-08 01:16

from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index


class Migration(migrations.Migration):
    atomic = settings.ATOMIC_PG_MIGRATIONS

    dependencies = [
        ("zerver", "0519_archivetransaction_restored_timestamp"),
    ]

    operations = [
        add_index(
            model_name="attachment",
            index=models.Index(
                models.F("realm"),
                models.F("create_time"),
                name="zerver_attachment_realm_create_time",
            ),
        ),
    ]
