# Generated by Django 4.2.10 on 2024-03-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zerver",
            "0520_attachment_zerver_attachment_realm_create_time",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="include_realm_default_subscriptions",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="include_realm_default_subscriptions",
            field=models.BooleanField(null=True),
        ),
    ]
