# Generated by Django 5.0.5 on 2024-05-02 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0520_attachment_zerver_attachment_realm_create_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alertword",
            old_name="word",
            new_name="watched_phrase",
        ),
        migrations.AlterUniqueTogether(
            name="alertword",
            unique_together={("user_profile", "watched_phrase")},
        ),
    ]
