# Generated by Django 5.0.6 on 2024-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0520_attachment_zerver_attachment_realm_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="date_deleted_history",
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AddField(
            model_name="archivedmessage",
            name="deleter_history_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="archivedmessage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="date_deleted_history",
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AddField(
            model_name="message",
            name="deleter_history_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
