# Generated by Django 5.0.5 on 2024-04-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0522_set_include_realm_default_subscriptions_for_existing_objects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiuseinvite",
            name="include_realm_default_subscriptions",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="preregistrationuser",
            name="include_realm_default_subscriptions",
            field=models.BooleanField(default=True),
        ),
    ]
