# Generated by Django 5.0.6 on 2024-05-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0523_alter_multiuseinvite_subscribe_to_default_streams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_change_own_name_group",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
