# Generated by Django 5.0.6 on 2024-05-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0523_alter_multiuseinvite_subscribe_to_default_streams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="background_source",
            field=models.CharField(
                choices=[("U", "Uploaded by administrator")], default="D", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="background_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
