# Generated by Django 5.0.6 on 2024-05-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0523_alter_multiuseinvite_subscribe_to_default_streams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="user_groups",
            field=models.ManyToManyField(to="zerver.namedusergroup"),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="user_groups",
            field=models.ManyToManyField(to="zerver.namedusergroup"),
        ),
    ]
