# Generated by Django 5.0.6 on 2024-05-29 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0523_alter_multiuseinvite_subscribe_to_default_streams_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="onboarding_steps",
        ),
    ]
