# Generated by Django 5.0.5 on 2024-05-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0524_remove_userprofile_onboarding_steps"),
    ]

    operations = [
        # Create a new column, making it NULLable to avoid locking the table
        # rewriting rows with a non-NULL default value.
        migrations.AddField(
            model_name="userpresence",
            name="last_update_id",
            field=models.PositiveBigIntegerField(db_index=True, null=True),
        ),
        # This is an SQL noop, since Django doesn't add defaults at database level.
        # The default guarantees new rows will have a value. Old rows can get backfilled
        # in the next migration.
        migrations.AlterField(
            model_name="userpresence",
            name="last_update_id",
            field=models.PositiveBigIntegerField(db_index=True, default=0, null=True),
        ),
    ]
