# Generated by Django 5.0.6 on 2024-05-17 10:55

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def migrate_name_change_policy(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Realm = apps.get_model("zerver", "Realm")
    POLICY_EVERYONE = 5
    POLICY_ADMINS_ONLY = 2
    for realm in Realm.objects.all():
        if realm.name_changes_disabled:
            realm.can_change_own_name_group = POLICY_ADMINS_ONLY
        else:
            realm.can_change_own_name_group = POLICY_EVERYONE
        realm.save()


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0524_realm_can_change_own_name_group"),
    ]

    operations = [
        migrations.RunPython(migrate_name_change_policy),
    ]
