# Generated by Django 5.0.6 on 2024-05-17 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0525_realm_name_changes_disabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="name_changes_disabled",
        ),
    ]
