# Generated by Django 5.0.6 on 2024-06-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0528_realmauditlog_zerver_realmauditlog_user_activations_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_left_sidebar_unreads_count_summary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_left_sidebar_unreads_count_summary",
            field=models.BooleanField(default=False),
        ),
    ]
