# Generated by Django 5.0.6 on 2024-05-23 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0531_convert_most_ids_to_bigints"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_create_public_channel_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
