# Generated by Django 5.0.6 on 2024-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0531_convert_most_ids_to_bigints"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_dm_reaction_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="streams_reaction_notification",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_dm_reaction_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="streams_reaction_notification",
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
