# Generated by Django 5.0.6 on 2024-06-17 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0536_add_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_create_private_channel_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
