# Generated by Django 4.2.5 on 2023-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zerver",
            "0536_add_message_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="user_groups",
            field=models.ManyToManyField(to="zerver.namedusergroup"),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="user_groups",
            field=models.ManyToManyField(to="zerver.namedusergroup"),
        ),
    ]
