# Generated by Django 5.0.6 on 2024-06-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0536_add_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="custom_default_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="custom_default_hours",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="custom_default_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="custom_default_hours",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
