# Generated by Django 5.0.6 on 2024-06-20 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0521_archivedmessage_date_deleted_history_and_more"),
        ("zerver", "0536_add_message_type"),
    ]

    operations = []
