# Generated by Django 5.0.6 on 2024-06-11 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0506_userprofile_ban_reason"),
        ("zerver", "0536_add_message_type"),
    ]

    operations = []
