# Generated by Django 5.0.6 on 2024-06-17 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0538_set_can_create_private_channel_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_create_private_channel_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
