# Generated by Django 5.0.6 on 2024-06-23 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0537_merge_20240620_1545"),
        ("zerver", "0540_remove_realm_create_private_stream_policy"),
    ]

    operations = []
