# Generated by Django 5.0.6 on 2024-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0540_remove_realm_create_private_stream_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="automatically_detect_time_zone",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="automatically_detect_time_zone",
            field=models.BooleanField(default=True),
        ),
    ]
