# Generated by Django 5.0.6 on 2024-05-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0541_alter_realmauditlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
