# Generated by Django 5.0.6 on 2024-06-30 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0541_alter_realmauditlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="creator",
            field=models.ForeignKey(
                db_column="creator",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="namedusergroup",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
