# Generated by Django 4.2.11 on 2024-04-17 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zerver",
            "0541_alter_realmauditlog_options",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RealmSession",
            fields=[
                (
                    "session_key",
                    models.CharField(
                        max_length=40, primary_key=True, serialize=False, verbose_name="session key"
                    ),
                ),
                ("session_data", models.TextField(verbose_name="session data")),
                ("expire_date", models.DateTimeField(db_index=True, verbose_name="expire date")),
                ("ip_address", models.GenericIPAddressField(null=True)),
                (
                    "realm",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["realm", "user"], name="zerver_realmsession_realm_user_idx"
                    ),
                    models.Index(fields=["ip_address"], name="zerver_realmsession_ip_address_idx"),
                ],
            },
        ),
    ]
