# Generated by Django 5.0.6 on 2024-06-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0541_alter_realmauditlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="custom_default_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="custom_default_hours",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="custom_default_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="custom_default_hours",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
