# Generated by Django 5.0.6 on 2024-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0546_rename_huddle_directmessagegroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_navigate_to_sent_message",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_navigate_to_sent_message",
            field=models.BooleanField(default=True),
        ),
    ]
