# Generated by Django 5.0.6 on 2024-07-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0547_realmuserdefault_web_navigate_to_sent_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_channel_default_view",
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_channel_default_view",
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
    ]
