# Generated by Django 5.0.6 on 2024-06-27 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0551_alter_realm_direct_message_initiator_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="private_message_policy",
        ),
    ]
