# Generated by Django 5.0.6 on 2024-07-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0552_remove_realm_private_message_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="background_source",
            field=models.CharField(
                choices=[("U", "Uploaded by administrator")], default="D", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="background_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
