# Generated by Django 5.0.5 on 2024-04-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0554_imageattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingstep",
            name="onboarding_step",
            field=models.CharField(max_length=40),
        ),
    ]
