# Generated by Django 5.0.6 on 2024-07-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0555_alter_onboardingstep_onboarding_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmuserdefault",
            name="dense_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="realmuserdefault",
            name="web_font_size_px",
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name="realmuserdefault",
            name="web_line_height_percent",
            field=models.PositiveSmallIntegerField(default=140),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dense_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="web_font_size_px",
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="web_line_height_percent",
            field=models.PositiveSmallIntegerField(default=140),
        ),
    ]
