# Generated by Django 5.0.6 on 2024-07-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0557_change_information_density_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_animate_image_previews",
            field=models.TextField(default="on_hover"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_animate_image_previews",
            field=models.TextField(default="on_hover"),
        ),
    ]
