# Generated by Django 5.0.6 on 2024-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0562_remove_realm_create_web_public_stream_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_suggest_update_timezone",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_suggest_update_timezone",
            field=models.BooleanField(default=True),
        ),
    ]
