# Generated by Django 5.0.6 on 2024-05-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0562_remove_realm_create_web_public_stream_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
