# Generated by Django 5.0.6 on 2024-07-18 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0566_set_default_for_can_delete_any_message_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_delete_any_message_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
