# Generated by Django 5.0.6 on 2024-07-25 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0568_mark_narrow_to_dm_with_welcome_bot_new_user_as_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="tutorial_status",
        ),
    ]
