# Generated by Django 4.2.2 on 2023-07-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0569_remove_userprofile_tutorial_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="can_manage_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
