# Generated by Django 5.0.7 on 2024-08-12 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0569_remove_userprofile_tutorial_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=150, unique=True)),
                (
                    "time_sent",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
