# Generated by Django 4.2.2 on 2023-07-16 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0571_set_default_for_can_manage_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namedusergroup",
            name="can_manage_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
