# Generated by Django 5.0.6 on 2024-08-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0572_alter_usergroup_can_manage_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessagegroup",
            name="group_size",
            field=models.IntegerField(null=True),
        ),
    ]
