# Generated by Django 5.0.6 on 2024-05-21 16:56

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def set_default_code_block_language(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Stream = apps.get_model("zerver", "Stream")
    for stream in Stream.objects.all():
        stream.default_code_block_language = stream.realm.default_code_block_language
        stream.save()


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0575_alter_directmessagegroup_group_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="default_code_block_language",
            field=models.TextField(default=""),
        ),
        migrations.RunPython(set_default_code_block_language),
    ]
