# Generated by Django 5.0.8 on 2024-08-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0577_merge_20240829_0153"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_dm_reaction_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="streams_reaction_notification",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_dm_reaction_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="streams_reaction_notification",
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
