# Generated by Django 5.0.8 on 2024-09-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0577_merge_20240829_0153"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertword",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
