# Generated by Django 5.0.7 on 2024-08-28 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0578_namedusergroup_deactivated"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_delete_own_message_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
