# Generated by Django 5.0.7 on 2024-08-28 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0580_set_default_value_for_can_delete_own_message_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_delete_own_message_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
