# Generated by Django 5.0.8 on 2024-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0584_namedusergroup_creator_date_created_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="allow_private_data_export",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="allow_private_data_export",
            field=models.BooleanField(default=False),
        ),
    ]
