# Generated by Django 5.0.6 on 2024-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0584_namedusergroup_creator_date_created_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="enable_guest_user_dm_warning",
            field=models.BooleanField(default=True),
        ),
    ]
