# Generated by Django 5.0.8 on 2024-09-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0584_namedusergroup_creator_date_created_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="user_groups",
            field=models.ManyToManyField(to="zerver.namedusergroup"),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="user_groups",
            field=models.ManyToManyField(to="zerver.namedusergroup"),
        ),
    ]
