# Generated by Django 5.0.8 on 2024-09-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0585_userprofile_allow_private_data_export_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="groups",
            field=models.ManyToManyField(to="zerver.namedusergroup"),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="groups",
            field=models.ManyToManyField(to="zerver.namedusergroup"),
        ),
    ]
