# Generated by Django 5.0.6 on 2024-06-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0585_userprofile_allow_private_data_export_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customprofilefield",
            name="editable_by_user",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
