# Generated by Django 5.0.8 on 2024-09-24 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0586_customprofilefield_editable_by_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.TextField(max_length=60)),
                ("content", models.TextField(max_length=10000)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
