# Generated by Django 5.0.6 on 2024-05-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0587_set_default_for_can_access_stream_topics_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="can_access_stream_topics_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
