# Generated by Django 5.0.8 on 2024-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0587_savedsnippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_left_sidebar_unreads_count_summary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_left_sidebar_unreads_count_summary",
            field=models.BooleanField(default=False),
        ),
    ]
