# Generated by Django 5.0.8 on 2024-09-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0589_set_can_create_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_create_groups",
            field=models.ForeignKey(
                on_delete=models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
