# Generated by Django 5.0.8 on 2024-09-17 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0593_alter_realm_manage_all_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="user_group_edit_policy",
        ),
    ]
