# Generated by Django 5.0.8 on 2024-09-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0595_add_realmexport_table_and_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="can_join_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
