# Generated by Django 5.0.8 on 2024-09-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0597_set_default_value_for_can_join_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namedusergroup",
            name="can_join_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
