# Generated by Django 5.0.9 on 2024-10-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0598_alter_namedusergroup_can_join_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="is_recently_active",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
