# Generated by Django 5.0.9 on 2024-11-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0602_remap_can_manage_all_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmauditlog",
            name="new_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="realmauditlog",
            name="old_value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
