# Generated by Django 5.0.9 on 2024-10-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0602_remap_can_manage_all_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_add_custom_emoji_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
