# Generated by Django 5.0.9 on 2024-10-05 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0605_alter_realm_can_add_custom_emoji_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="add_custom_emoji_policy",
        ),
    ]
