# Generated by Django 5.0.9 on 2024-10-14 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0606_remove_realm_add_custom_emoji_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="can_leave_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
