# Generated by Django 5.0.9 on 2024-10-16 11:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0609_alter_namedusergroup_can_leave_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationrealm",
            name="data_import_metadata",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
