# Generated by Django 5.0.9 on 2024-10-12 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0610_mark_introduce_resolve_topic_modal_as_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_move_messages_between_channels_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
