# Generated by Django 5.0.9 on 2024-10-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0612_set_default_value_for_can_move_messages_between_channels_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_move_messages_between_channels_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
