# Generated by Django 5.0.9 on 2024-10-25 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0617_remove_prefix_from_archived_streams"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_move_messages_between_topics_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
