# Generated by Django 4.2.1 on 2023-06-12 10:47

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import OuterRef


def set_default_value_for_can_move_messages_between_topics_group(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Realm = apps.get_model("zerver", "Realm")
    NamedUserGroup = apps.get_model("zerver", "NamedUserGroup")

    edit_topic_policy_to_group_name = {
        1: "role:members",
        2: "role:administrators",
        3: "role:fullmembers",
        4: "role:moderators",
        5: "role:everyone",
        6: "role:nobody",
    }

    for id, group_name in edit_topic_policy_to_group_name.items():
        Realm.objects.filter(
            can_move_messages_between_topics_group=None, edit_topic_policy=id
        ).update(
            can_move_messages_between_topics_group=NamedUserGroup.objects.filter(
                name=group_name, realm=OuterRef("id"), is_system_group=True
            ).values("pk")
        )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0618_realm_can_move_messages_between_topics_group"),
    ]

    operations = [
        migrations.RunPython(
            set_default_value_for_can_move_messages_between_topics_group,
            elidable=True,
            reverse_code=migrations.RunPython.noop,
        )
    ]
