# Generated by Django 5.0.9 on 2024-10-27 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0620_alter_realm_can_move_messages_between_topics_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="edit_topic_policy",
        ),
    ]
