# Generated by Django 5.0.9 on 2024-10-30 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0621_remove_realm_edit_topic_policy"),
        ("zerver", "0622_backfill_imageattachment_again"),
    ]

    operations = []
