# Generated by Django 5.0.9 on 2024-11-04 04:23

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def rename_default_view(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    RealmUserDefault = apps.get_model("zerver", "RealmUserDefault")
    UserProfile = apps.get_model("zerver", "UserProfile")

    # Change "recent_topics" to "recent"
    RealmUserDefault.objects.filter(web_home_view="recent_topics").update(web_home_view="recent")
    UserProfile.objects.filter(web_home_view="recent_topics").update(web_home_view="recent")


def reverse_rename_default_view(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    RealmUserDefault = apps.get_model("zerver", "RealmUserDefault")
    UserProfile = apps.get_model("zerver", "UserProfile")

    # Change "recent" back to "recent_topics"
    RealmUserDefault.objects.filter(web_home_view="recent").update(web_home_view="recent_topics")
    UserProfile.objects.filter(web_home_view="recent").update(web_home_view="recent_topics")


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0623_merge_20241030_1835"),  # Replace with the actual previous migration
    ]

    operations = [
        migrations.RunPython(rename_default_view, reverse_code=reverse_rename_default_view),
    ]
