# Generated by Django 5.0.9 on 2024-11-02 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0623_merge_20241030_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_invite_to_channel_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
