# Generated by Django 5.0.9 on 2024-10-31 12:26

import datetime

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0623_merge_20241030_1835"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("topic_name", models.CharField(max_length=60)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.stream"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        models.F("realm"),
                        models.F("stream"),
                        django.db.models.functions.text.Lower("topic_name"),
                        name="topicsettings_stream_topic_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="topicsettings",
            constraint=models.UniqueConstraint(
                models.F("realm"),
                models.F("user_profile"),
                models.F("stream"),
                django.db.models.functions.text.Lower("topic_name"),
                name="topicsettings_case_insensitive_topic_uniq",
            ),
        ),
    ]
