# Generated by Django 5.0.9 on 2024-11-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0623_merge_20241030_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmexport",
            name="tarball_size_bytes",
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
    ]
