# Generated by Django 5.0.9 on 2024-11-13 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0624_alter_realmexport_tarball_size_bytes"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_invite_users_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
