# Generated by Django 4.2.1 on 2023-06-12 10:47

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import OuterRef


def set_default_value_for_can_invite_users_group(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Realm = apps.get_model("zerver", "Realm")
    NamedUserGroup = apps.get_model("zerver", "NamedUserGroup")

    invite_to_realm_policy_to_group_name = {
        1: "role:members",
        2: "role:administrators",
        3: "role:fullmembers",
        4: "role:moderators",
        6: "role:nobody",
    }

    for id, group_name in invite_to_realm_policy_to_group_name.items():
        Realm.objects.filter(can_invite_users_group=None, invite_to_realm_policy=id).update(
            can_invite_users_group=NamedUserGroup.objects.filter(
                name=group_name, realm=OuterRef("id"), is_system_group=True
            ).values("pk")
        )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0625_realm_can_invite_users_group"),
    ]

    operations = [
        migrations.RunPython(
            set_default_value_for_can_invite_users_group,
            elidable=True,
            reverse_code=migrations.RunPython.noop,
        )
    ]
