# Generated by Django 5.0.9 on 2024-11-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0625_set_default_value_for_can_invite_to_channel_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_invite_to_channel_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
