# Generated by Django 5.0.9 on 2024-11-05 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0626_alter_realm_can_invite_to_channel_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="invite_to_stream_policy",
        ),
    ]
