# Generated by Django 5.0.9 on 2024-11-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0630_multiuseinvite_groups_preregistrationuser_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="is_recently_active",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
