# Generated by Django 5.0.9 on 2024-11-29 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

MENU = 1
EXPANDED = 2

LOCATION_CHOICES = [
    (MENU, "Menu"),
    (EXPANDED, "Expanded"),
]


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0631_stream_is_recently_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("view_id", models.TextField()),
                ("location", models.PositiveSmallIntegerField(choices=LOCATION_CHOICES)),
                ("name", models.TextField(blank=True, null=True)),
                ("url_hash", models.TextField(blank=True, null=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("user_profile", "view_id")},
            },
        ),
    ]
