# Generated by Django 5.0.9 on 2024-11-28 06:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0631_stream_is_recently_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationrealm",
            name="data_import_metadata",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
