# Generated by Django 5.0.9 on 2024-11-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0632_preregistrationrealm_data_import_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="can_remove_members_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
