# Generated by Django 5.0.9 on 2024-11-29 13:48

from django.db import migrations, models

EXPANDED = 2


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0632_pinnedview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pinnedview",
            name="location",
            field=models.PositiveSmallIntegerField(default=EXPANDED),
        ),
    ]
