# Generated by Django 5.0.9 on 2024-11-12 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0635_alter_namedusergroup_can_remove_members_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="can_administer_channel_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
