# Generated by Django 5.0.9 on 2024-10-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0638_alter_stream_can_administer_channel_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="scheduled_deletion_date",
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
