# Generated by Django 5.0.9 on 2024-12-04 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0638_alter_stream_can_administer_channel_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="abuse_report_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zerver.stream",
            ),
        ),
    ]
