# Generated by Django 5.0.9 on 2024-12-11 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0638_alter_stream_can_administer_channel_group"),
        ("zerver", "0639_zh_hant_tw_rename"),
    ]

    operations = []
