# Generated by Django 5.0.9 on 2024-11-08 13:02

import time

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import Q

BATCH_SIZE = 1000


def process_batch(apps: StateApps, id_start: int, id_end: int, last_id: int) -> None:
    RECIPIENT_PERSONAL = 1
    RECIPIENT_HUDDLE = 3

    Client = apps.get_model("zerver", "Client")
    Message = apps.get_model("zerver", "Message")

    # Fetch the ID of "populate_db" client which is the sending_client of imported messages
    internal_client, _ = Client.objects.get_or_create(name="populate_db")

    # Matches subjects like '2015-08-18 Slack thread 2'
    slack_thread_pattern = r"\d{4}-\d{2}-\d{2} Slack thread \d+"

    # Filter batch of messages that are imported from Slack
    messages_to_update = Message.objects.filter(
        id__gte=id_start,
        id__lte=id_end,
        sending_client_id=internal_client.id,
        recipient__type__in=[RECIPIENT_PERSONAL, RECIPIENT_HUDDLE],
    ).filter(Q(subject="Imported from Slack") | Q(subject__regex=slack_thread_pattern))

    messages_to_update.update(subject="")

    if id_end % 1000 == 0:
        print(f"Processed messages up to ID {id_end} / {last_id}")


def update_dm_and_gdm_topic_name(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Message = apps.get_model("zerver", "Message")
    if not Message.objects.exists():
        # Nothing to do, and Message.objects.latest() will crash.
        return

    last_id = Message.objects.latest("id").id

    id_range_lower_bound = 0
    id_range_upper_bound = 0 + BATCH_SIZE
    while id_range_upper_bound <= last_id:
        process_batch(apps, id_range_lower_bound, id_range_upper_bound, last_id)

        id_range_lower_bound = id_range_upper_bound + 1
        id_range_upper_bound = id_range_lower_bound + BATCH_SIZE
        time.sleep(0.1)

    # Handle any remaining messages
    if last_id > id_range_lower_bound:
        process_batch(apps, id_range_lower_bound, last_id, last_id)


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("zerver", "0640_merge_20241211_1953"),
    ]

    operations = [
        migrations.RunPython(update_dm_and_gdm_topic_name),
    ]
