# Generated by Django 5.0.9 on 2024-12-12 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0640_merge_20241211_1953"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="moderation_request_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zerver.stream",
            ),
        ),
    ]
