# Generated by Django 5.0.9 on 2024-12-14 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0641_web_suggest_update_time_zone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url_hash", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("name", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "url_hash")},
            },
        ),
    ]
