# Generated by Django 5.0.10 on 2024-12-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0643_realm_scheduled_deletion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="welcome_bot_custom_message",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="realm",
            name="welcome_bot_custom_message_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
