# Generated by Django 5.0.10 on 2024-12-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0643_realm_scheduled_deletion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="mobile_push_notifications_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
