# Generated by Django 5.0.10 on 2024-12-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0643_realm_scheduled_deletion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="display_organization_name",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="display_organization_name",
            field=models.BooleanField(default=False),
        ),
    ]
