# Generated by Django 5.0.10 on 2024-12-27 08:28

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def migrate_allow_edit_history(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    MESSAGE_EDIT_HISTORY_VISIBILITY_ALL = 1
    MESSAGE_EDIT_HISTORY_VISIBILITY_NONE = 3

    Realm = apps.get_model("zerver", "Realm")
    Realm.objects.filter(allow_edit_history=True).update(
        message_edit_history_visibility=MESSAGE_EDIT_HISTORY_VISIBILITY_ALL
    )
    Realm.objects.filter(allow_edit_history=False).update(
        message_edit_history_visibility=MESSAGE_EDIT_HISTORY_VISIBILITY_NONE
    )


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0643_realm_scheduled_deletion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="message_edit_history_visibility",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(migrate_allow_edit_history),
        migrations.RemoveField(
            model_name="realm",
            name="allow_edit_history",
        ),
    ]
