# Generated by Django 5.0.9 on 2024-12-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0643_realm_scheduled_deletion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="enable_guest_user_dm_warning",
            field=models.BooleanField(default=True),
        ),
    ]
