# Generated by Django 5.0.10 on 2024-12-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0643_realm_scheduled_deletion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="signup_notifications_include_referrer",
            field=models.BooleanField(default=True),
        ),
    ]
