# Generated by Django 5.0.9 on 2024-12-05 12:32
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0643_realm_scheduled_deletion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedattachment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attachment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="imageattachment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        AddIndexConcurrently(
            model_name="archivedattachment",
            index=models.Index(
                condition=models.Q(("deleted", True)),
                fields=["deleted"],
                name="zerver_archivedattachment_deleted_true_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="attachment",
            index=models.Index(
                condition=models.Q(("deleted", True)),
                fields=["deleted"],
                name="zerver_attachment_deleted_true_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="imageattachment",
            index=models.Index(
                condition=models.Q(("deleted", True)),
                fields=["deleted"],
                name="zerver_imageattachment_deleted_true_idx",
            ),
        ),
    ]
