# Generated by Django 5.0.10 on 2025-01-03 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0644_check_update_all_channels_active_status"),
        ("zerver", "0644_stream_mobile_push_notifications_enabled"),
    ]

    operations = []
