# Generated by Django 5.0.10 on 2025-01-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0644_check_update_all_channels_active_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="rendered_description",
            field=models.TextField(default=""),
        ),
    ]
