# Generated by Django 5.0.9 on 2024-12-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0646_set_default_for_can_send_message_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="can_send_message_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
