# Generated by Django 5.0.10 on 2025-01-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0648_remove_stream_stream_post_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertword",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
