# Generated by Django 5.0.10 on 2025-01-08 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0648_remove_stream_stream_post_policy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="realm",
            old_name="can_create_groups",
            new_name="can_create_groups_group",
        ),
        migrations.RenameField(
            model_name="realm",
            old_name="can_manage_all_groups",
            new_name="can_manage_all_groups_group",
        ),
    ]
