# Generated by Django 5.0.10 on 2025-01-13 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0650_set_default_for_realm_can_add_subscribers_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_add_subscribers_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
