# Generated by Django 5.0.10 on 2025-01-14 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0651_alter_realm_can_add_subscribers_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="invite_to_stream_policy",
        )
    ]
