# Generated by Django 5.0.10 on 2025-01-23 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0657_set_default_value_for_can_create_bots_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_create_bots_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
        migrations.AlterField(
            model_name="realm",
            name="can_create_write_only_bots_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
