# Generated by Django 5.0.10 on 2025-02-03 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0645_merge_20250103_2022"),
        ("zerver", "0660_add_imageattachment_content_type"),
    ]

    operations = []
