# Generated by Django 5.0.10 on 2025-02-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0662_clear_realm_channel_fields_if_configured_channel_deactivated"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="enable_guest_user_dm_warning",
            field=models.BooleanField(default=True),
        ),
    ]
