# Generated by Django 5.0.10 on 2025-02-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0666_alter_realm_can_summarize_topics_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="hide_ai_features",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hide_ai_features",
            field=models.BooleanField(default=False),
        ),
    ]
