# Generated by Django 5.0.10 on 2025-02-08 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0667_realmuserdefault_hide_ai_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_mention_many_users_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
