# Generated by Django 5.0.10 on 2025-02-08 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0669_set_default_value_for_can_mention_many_users_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_mention_many_users_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
