# Generated by Django 5.0.10 on 2025-02-11 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0670_alter_realm_can_mention_many_users_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="wildcard_mention_policy",
        ),
    ]
