# Generated by Django 5.0.10 on 2025-02-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0671_remove_realm_wildcard_mention_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="welcome_bot_custom_message",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="welcome_bot_custom_message",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
