# Generated by Django 5.0.10 on 2025-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0672_multiuseinvite_welcome_bot_custom_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="default_welcome_bot_custom_message",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="realm",
            name="send_invite_welcome_bot_custom_message",
            field=models.BooleanField(default=False),
        ),
    ]
