# Generated by Django 5.0.10 on 2025-01-06 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0673_set_value_for_message_edit_history_visibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="allow_edit_history",
        ),
    ]
