# Generated by Django 5.0.10 on 2025-02-16 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0677_set_default_message_edit_history_visibility_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="allow_edit_history",
        ),
    ]
