# Generated by Django 5.1.6 on 2025-02-26 17:25

from django.db import migrations, models
from django.conf import settings

from . import add_index


class Migration(migrations.Migration):
    atomic = settings.ATOMIC_PG_MIGRATIONS

    dependencies = [
        ("zerver", "0678_remove_realm_allow_edit_history"),
    ]

    operations = [
        add_index(
            model_name="message",
            index=models.Index(
                condition=models.Q(("edit_history__isnull", False)),
                fields=["id"],
                name="zerver_message_edit_history_id",
            ),
        ),
    ]
