# Generated by Django 5.1.6 on 2025-02-26 17:25

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0678_remove_realm_allow_edit_history"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="message",
            index=models.Index(
                condition=models.Q(("edit_history__isnull", False)),
                fields=["id"],
                name="zerver_message_edit_history_id",
            ),
        ),
    ]
