# Generated by Django 5.1.6 on 2025-03-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0680_rename_general_chat_to_empty_string_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_mark_resolved_topic_notifications_as_read",
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_mark_resolved_topic_notifications_as_read",
            field=models.SmallIntegerField(default=2),
        ),
    ]
