# Generated by Django 5.0.10 on 2025-02-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0680_rename_general_chat_to_empty_string_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_manage_billing_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
