# Generated by Django 5.1.6 on 2025-03-08 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0684_remove_userprofile_is_billing_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realmuserdefault",
            name="dense_mode",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="dense_mode",
        ),
    ]
