# Generated by Django 5.0.6 on 2024-05-16 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0687_set_default_value_for_can_resolve_topics_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_resolve_topics_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
