# Generated by Django 5.1.6 on 2025-03-18 01:00
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0696_rename_no_topic_to_empty_string_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedattachment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attachment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        AddIndexConcurrently(
            model_name="archivedattachment",
            index=models.Index(
                condition=models.Q(("deleted", True)),
                fields=["deleted"],
                name="zerver_archivedattachment_deleted_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="attachment",
            index=models.Index(
                condition=models.Q(("deleted", True)),
                fields=["deleted"],
                name="zerver_attachment_deleted_idx",
            ),
        ),
    ]
