# Generated by Django 5.1.7 on 2025-03-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0696_rename_no_topic_to_empty_string_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="welcome_bot_custom_message",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="welcome_bot_custom_message",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
