# Generated by Django 5.1.7 on 2025-03-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0696_rename_no_topic_to_empty_string_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="rendered_topic",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="rendered_topic",
            field=models.TextField(null=True),
        ),
    ]
