# Generated by Django 5.1.8 on 2025-05-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0697_empty_topic_name_for_dms_from_third_party_imports"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auto_collapse_views",
            field=models.BooleanField(default=True),
        ),
    ]
