# Generated by Django 5.1.8 on 2025-04-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    when_following = 2
    dependencies = [
        ("zerver", "0697_empty_topic_name_for_dms_from_third_party_imports"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="resolved_topic_notice_unread_policy",
            field=models.PositiveSmallIntegerField(default=when_following),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="resolved_topic_notice_unread_policy",
            field=models.PositiveSmallIntegerField(default=when_following),
        ),
    ]
