# Generated by Django 5.1.7 on 2025-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0697_empty_topic_name_for_dms_from_third_party_imports"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="default_color",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
