# Generated by Django 5.1.7 on 2025-03-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0697_empty_topic_name_for_dms_from_third_party_imports"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="welcome_bot_custom_message",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="welcome_bot_custom_message",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
