# Generated by Django 5.0.10 on 2025-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0697_empty_topic_name_for_dms_from_third_party_imports"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="rendered_description",
            field=models.TextField(default=""),
        ),
    ]
