# Generated by Django 5.1.7 on 2025-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0697_empty_topic_name_for_dms_from_third_party_imports"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="rendered_topic",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="rendered_topic",
            field=models.TextField(null=True),
        ),
    ]
