# Generated by Django 5.1.8 on 2025-04-15 16:27

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def rename_populate_db_client(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Renames the 'populate_db' client to 'ZulipDataImport' to reflect updated naming conventions.
    This is part of transitioning data import clients to a standardized name.
    """
    Client = apps.get_model("zerver", "Client")
    db_alias = schema_editor.connection.alias

    Client.objects.using(db_alias).filter(name="populate_db").update(name="ZulipDataImport")


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0697_empty_topic_name_for_dms_from_third_party_imports"),
    ]

    operations = [
        migrations.RunPython(
            rename_populate_db_client,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
