# Generated by Django 5.1.8 on 2025-04-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0697_empty_topic_name_for_dms_from_third_party_imports"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="default_welcome_bot_custom_message",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="realm",
            name="send_invite_welcome_bot_custom_message",
            field=models.BooleanField(default=False),
        ),
    ]
