# Generated by Django 5.1.7 on 2025-03-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    unfollowed_topics = 2
    dependencies = [
        ("zerver", "0697_empty_topic_name_for_dms_from_third_party_imports"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="mark_resolved_topic_notifications_as_read_policy",
            field=models.PositiveSmallIntegerField(default=unfollowed_topics),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mark_resolved_topic_notifications_as_read_policy",
            field=models.PositiveSmallIntegerField(default=unfollowed_topics),
        ),
    ]
