# Generated by Django 5.1.8 on 2025-04-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0698_userprofile_auto_collapse_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="reminder_target_message_id",
            field=models.IntegerField(null=True),
        ),
    ]
