# Generated by Django 5.1.8 on 2025-04-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    except_followed = 2
    dependencies = [
        ("zerver", "0698_scheduledmessage_request_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="resolved_topic_notice_auto_read_policy",
            field=models.PositiveSmallIntegerField(default=except_followed),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="resolved_topic_notice_auto_read_policy",
            field=models.PositiveSmallIntegerField(default=except_followed),
        ),
    ]
