# Generated by Django 5.1.8 on 2025-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0698_userprofile_auto_collapse_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="auto_collapse_views",
            field=models.BooleanField(default=False),
        ),
    ]
