# Generated by Django 5.1.8 on 2025-05-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0700_fix_user_role_system_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="message_trigger_type",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
