# Generated by Django 5.1.8 on 2025-05-08 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0699_realmuserdefault_auto_collapse_views"),
        ("zerver", "0701_merge"),
    ]

    operations = []
