# Generated by Django 5.1.7 on 2025-04-02 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0702_rename_populate_db_client_to_zulip_data_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="can_unsubscribe_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
