# Generated by Django 5.1.8 on 2025-04-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    except_followed = 2
    dependencies = [
        ("zerver", "0702_rename_populate_db_client_to_zulip_data_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="resolved_topic_notice_auto_read_policy",
            field=models.PositiveSmallIntegerField(
                default=except_followed,
                db_default=except_followed,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="resolved_topic_notice_auto_read_policy",
            field=models.PositiveSmallIntegerField(
                default=except_followed,
                db_default=except_followed,
            ),
        ),
    ]
