# Generated by Django 5.1.7 on 2025-03-24 09:05
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0702_rename_populate_db_client_to_zulip_data_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="topics_policy",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
