# Generated by Django 5.1.7 on 2025-04-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0703_realmuserdefault_resolved_topic_notice_auto_read_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="subscriber_count",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
