# Generated by Django 5.1.8 on 2025-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0703_rename_populate_db_client_to_zulip_data_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="auto_collapse_views",
            field=models.BooleanField(default=True),
        ),
    ]
