# Generated by Django 5.1.7 on 2025-03-24 09:05
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0705_stream_subscriber_count_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="topics_policy",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
