# Generated by Django 5.1.7 on 2025-04-08 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0705_stream_subscriber_count_data_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fragment", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("name", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "fragment")},
            },
        ),
    ]
