# Generated by Django 5.1.8 on 2025-05-05 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0706_channelfolder"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmauditlog",
            name="modified_channel_folder",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="zerver.channelfolder"
            ),
        ),
    ]
