# Generated by Django 5.1.8 on 2025-05-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0707_realmauditlog_modified_channel_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="folder",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="zerver.channelfolder"
            ),
        ),
    ]
