# Generated by Django 5.1.8 on 2025-06-09 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0709_navigationview"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAuthID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("external_auth_method_name", models.TextField(db_index=True)),
                ("external_auth_id", models.TextField(db_index=True)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("realm", "external_auth_id", "external_auth_method_name"),
                        name="zerver_externalauthid_uniq",
                    )
                ],
            },
        ),
    ]
