# Generated by Django 5.1.8 on 2025-05-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0709_navigationview"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="is_editable_by_others",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_editable_by_others",
            field=models.BooleanField(default=False),
        ),
    ]
