# Generated by Django 5.1.7 on 2025-04-08 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0709_navigationview"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="can_resolve_topics_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
