# Generated by Django 5.1.8 on 2025-06-02 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0709_navigationview"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token_kind", models.PositiveSmallIntegerField(choices=[(1, "Apns"), (2, "Fcm")])),
                ("push_account_id", models.BigIntegerField()),
                ("push_public_key", models.TextField()),
                ("bouncer_device_id", models.BigIntegerField(null=True)),
                ("bouncer_public_key", models.TextField(null=True)),
                ("encrypted_push_registration", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
