# Generated by Django 5.1.8 on 2025-04-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0709_realm_default_welcome_bot_custom_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="welcome_bot_custom_message",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="welcome_bot_custom_message",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
