# Generated by Django 5.1.7 on 2025-03-24 09:11

from enum import Enum

from django.db import migrations, models


class RealmTopicsPolicyEnum(Enum):
    allow_empty_topic = 2


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0711_set_default_value_for_realm_topics_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="topics_policy",
            field=models.PositiveSmallIntegerField(
                default=RealmTopicsPolicyEnum.allow_empty_topic.value
            ),
        ),
    ]
