# Generated by Django 5.1.10 on 2025-06-08 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0711_set_default_can_create_topic_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="can_create_topic_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
