# Generated by Django 5.1.7 on 2025-03-24 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0712_alter_realm_topics_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="mandatory_topics",
        ),
    ]
