# Generated by Django 5.1.7 on 2025-03-29 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0713_remove_realm_mandatory_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_set_topics_policy_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
