# Generated by Django 5.1.7 on 2025-03-29 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0715_set_default_value_for_can_set_topics_policy_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_set_topics_policy_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
