# Generated by Django 5.1.7 on 2025-03-29 12:17

from enum import Enum

from django.db import migrations, models


class StreamTopicsPolicyEnum(Enum):
    inherit = 1


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0716_alter_realm_can_set_topics_policy_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="topics_policy",
            field=models.PositiveSmallIntegerField(default=StreamTopicsPolicyEnum.inherit.value),
        ),
    ]
