# Generated by Django 5.1.8 on 2025-06-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0718_fix_topics_for_direct_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="can_move_messages_within_channel_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
