# Generated by Django 5.1.8 on 2025-06-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0720_set_default_value_for_can_move_messages_within_channel_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="can_move_messages_within_channel_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
