# Generated by Django 5.1.8 on 2025-05-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0724_alter_stream_can_move_messages_out_of_channel_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_left_sidebar_unreads_count_summary",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_left_sidebar_unreads_count_summary",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
