# Generated by Django 5.2.3 on 2025-06-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0724_alter_stream_can_move_messages_out_of_channel_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="triggers",
            field=models.JSONField(default=list),
        ),
    ]
