# Generated by Django 5.2.3 on 2025-06-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0724_alter_stream_can_move_messages_out_of_channel_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="reaction_notifications_policy",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reaction_notifications_policy",
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
