# Generated by Django 5.2.3 on 2025-06-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0725_realmuserdefault_web_left_sidebar_unreads_count_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="triggers",
            field=models.JSONField(default=list),
        ),
    ]
