# Generated by Django 5.2.3 on 2025-07-01 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0725_realmuserdefault_web_left_sidebar_unreads_count_summary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token_kind", models.PositiveSmallIntegerField(choices=[(1, "APNs"), (2, "FCM")])),
                ("push_account_id", models.BigIntegerField()),
                ("push_public_key", models.TextField()),
                ("bouncer_device_id", models.BigIntegerField(null=True)),
                ("bouncer_public_key", models.TextField(null=True)),
                ("encrypted_push_registration", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "push_account_id"],
                        name="zerver_push_device_user_push_account_id_idx",
                    )
                ],
            },
        ),
    ]
