# Generated by Django 5.2.3 on 2025-07-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0725_realmuserdefault_web_left_sidebar_unreads_count_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_reaction_audible_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_reaction_desktop_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_reaction_audible_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_reaction_desktop_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
