# Generated by Django 5.2.3 on 2025-06-26 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0725_realmuserdefault_web_left_sidebar_unreads_count_summary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAuthID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("external_auth_method_name", models.TextField()),
                ("external_auth_id", models.TextField()),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["realm", "external_auth_method_name"],
                        name="zerver_externalauthid_realm_method_name_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("realm", "external_auth_id", "external_auth_method_name"),
                        name="zerver_externalauthid_uniq",
                    )
                ],
            },
        ),
    ]
