# Generated by Django 5.1.10 on 2025-06-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0725_realmuserdefault_web_left_sidebar_unreads_count_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="can_create_topic_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
