# Generated by Django 5.2.3 on 2025-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0726_realm_welcome_message_custom_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiuseinvite",
            name="welcome_message_custom_text",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="welcome_message_custom_text",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
