# Generated by Django 5.2.3 on 2025-06-30 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0727_set_default_value_for_stream_can_resolve_topics_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="can_resolve_topics_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
