# Generated by Django 5.2.3 on 2025-06-25 12:55

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0729_externalauthid"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.UUIDField(db_index=True, unique=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                ("identifier", models.IntegerField(db_index=True, null=True)),
                ("cached_response", models.JSONField(default=None, null=True)),
            ],
        ),
    ]
