# Generated by Django 5.2.3 on 2025-07-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0729_externalauthid"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_reaction_audible_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_reaction_desktop_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_reaction_audible_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_reaction_desktop_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
