# Generated by Django 5.2.3 on 2025-06-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0730_pushdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="can_delete_any_message_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
