# Generated by Django 5.2.3 on 2025-06-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0735_set_default_value_for_can_delete_own_message_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="can_delete_own_message_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
