# Generated by Django 5.2.3 on 2025-06-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0736_alter_stream_can_delete_own_message_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_set_delete_message_policy_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
