# Generated by Django 5.2.3 on 2025-06-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0738_set_default_value_for_can_set_delete_message_policy_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="can_set_delete_message_policy_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
