# Generated by Django 5.2.3 on 2025-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0739_alter_realm_can_set_delete_message_policy_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="welcome_message_custom_text",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
