# Generated by Django 5.2.4 on 2025-07-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0739_alter_realm_can_set_delete_message_policy_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="can_create_topic_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
