# Generated by Django 5.2.4 on 2025-07-22 11:57

from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index


class Migration(migrations.Migration):
    atomic = settings.ATOMIC_PG_MIGRATIONS

    dependencies = [
        ("zerver", "0740_pushdevicetoken_apns_case_insensitive"),
    ]

    operations = [
        add_index(
            model_name="pushdevice",
            index=models.Index(
                condition=models.Q(("bouncer_device_id__isnull", False)),
                fields=["user", "bouncer_device_id"],
                name="zerver_pushdevice_user_bouncer_device_id_idx",
            ),
        ),
    ]
