# Generated by Django 5.2.4 on 2025-07-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0729_alertword_deactivated"),
        ("zerver", "0742_usermessage_zerver_usermessage_is_private_unread_message_id"),
    ]

    operations = []
