# Generated by Django 5.2.4 on 2025-07-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0742_usermessage_zerver_usermessage_is_private_unread_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="reminder_note_text",
            field=models.TextField(null=True),
        ),
    ]
