# Generated by Django 5.2.4 on 2025-07-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0743_realm_require_e2ee_push_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelfolder",
            name="name",
            field=models.CharField(max_length=60),
        ),
    ]
