# Generated by Django 5.2.4 on 2025-07-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0744_alter_channelfolder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertword",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
