# Generated by Django 5.2.4 on 2025-08-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0744_alter_channelfolder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_left_sidebar_show_channel_folders",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_left_sidebar_show_channel_folders",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
