# Generated by Django 5.2.4 on 2025-07-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0744_alter_channelfolder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="reminder_note_text",
            field=models.TextField(null=True),
        ),
    ]
