# Generated by Django 5.2.4 on 2025-07-30 19:00

from django.db import migrations, transaction
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

ROLE_REALM_OWNER = 100
REALM_EMOJI_ADDED = 226


def recreate_missing_realmemoji(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    RealmEmoji = apps.get_model("zerver", "RealmEmoji")
    RealmAuditLog = apps.get_model("zerver", "RealmAuditLog")
    Realm = apps.get_model("zerver", "Realm")
    UserProfile = apps.get_model("zerver", "UserProfile")
    for realm in Realm.objects.all():
        with transaction.atomic():
            last_emoji_add = (
                RealmAuditLog.objects.filter(
                    realm=realm,
                    event_type=REALM_EMOJI_ADDED,
                )
                .order_by("id")
                .last()
            )
            if last_emoji_add is None:
                continue
            first_owner = (
                UserProfile.objects.filter(
                    realm=realm, is_bot=False, role=ROLE_REALM_OWNER, is_active=True
                )
                .order_by("id")
                .first()
            )
            emoji = list(last_emoji_add.extra_data["realm_emoji"].values())
            for e in emoji:
                if RealmEmoji.objects.filter(id=int(e["id"])).exists():
                    continue
                file_name = e["source_url"][1 + e["source_url"].rfind("/") :]
                print(f"Creating missing emoji {e['name']}")
                RealmEmoji.objects.create(
                    id=int(e["id"]),
                    realm_id=realm.id,
                    name=e["name"],
                    author_id=first_owner.id,
                    file_name=file_name,
                    deactivated=e["deactivated"],
                    is_animated=e["still_url"] is not None,
                )

    # TODO: flushing the cache would be helpful. perhaps just add flush-memcached to suggested instructions?


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0744_alter_channelfolder_name"),
    ]

    operations = [
        migrations.RunPython(
            recreate_missing_realmemoji,
            elidable=True,
        ),
    ]
