# Generated by Django 5.2.4 on 2025-07-20 20:28

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0744_alter_channelfolder_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.UUIDField(db_index=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                ("identifier", models.IntegerField(db_index=True, null=True)),
                ("cached_response", models.JSONField(default=None, null=True)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("realm", "user", "idempotency_key"),
                        name="unique_realm_user_idempotency_key",
                    )
                ],
            },
        ),
    ]
