# Generated by Django 5.2.4 on 2025-07-29 09:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0745_usersetting_web_left_sidebar_show_channel_folders"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="channelfolder",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="channelfolder",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("realm"),
                condition=models.Q(("is_archived", False)),
                name="unique_realm_folder_name_when_not_archived",
            ),
        ),
    ]
