# Generated by Django 5.2.3 on 2025-07-04 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0746_alter_channelfolder_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealmCreationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("presume_email_valid", models.BooleanField(default=False)),
            ],
        ),
    ]
