# Generated by Django 5.2.4 on 2025-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0749_scheduledmessage_reminder_note_text"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="externalauthid",
            constraint=models.UniqueConstraint(
                fields=("user", "external_auth_method_name"), name="zerver_user_externalauth_uniq"
            ),
        ),
    ]
