# Generated by Django 5.2.4 on 2025-08-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0749_scheduledmessage_reminder_note_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertword",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
