# Generated by Django 5.2.4 on 2025-08-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0750_multiuseinvite_welcome_message_custom_text_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="externalauthid",
            constraint=models.UniqueConstraint(
                fields=("user", "external_auth_method_name"), name="zerver_user_externalauth_uniq"
            ),
        ),
    ]
