# Generated by Django 5.1.7 on 2025-04-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0751_externalauthid_zerver_user_externalauth_uniq"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="default_code_block_language",
            field=models.TextField(default=""),
        ),
    ]
