# Generated by Django 5.2.6 on 2025-09-08 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0751_externalauthid_zerver_user_externalauth_uniq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stream",
            name="is_in_zephyr_realm",
        ),
    ]
