# Generated by Django 5.2.5 on 2025-08-31 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0751_externalauthid_zerver_user_externalauth_uniq"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertWordRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("word", models.TextField()),
                (
                    "removed_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_profile", "removed_at"], name="zerver_aler_user_pr_7e9a5c_idx"
                    )
                ],
            },
        ),
    ]
