# Generated by Django 5.2.4 on 2025-08-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0751_externalauthid_zerver_user_externalauth_uniq"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertword",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
