# Generated by Django 5.2.4 on 2025-08-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0752_remove_stream_is_in_zephyr_realm"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="triggers",
            field=models.JSONField(default=list),
        ),
    ]
