# Generated by Django 5.2.6 on 2025-09-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0752_remove_stream_is_in_zephyr_realm"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationrealm",
            name="demo_organization",
            field=models.BooleanField(default=False),
        ),
    ]
