# Generated by Django 5.2.6 on 2025-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0753_remove_google_blob_emojiset"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_imported_stub",
            field=models.BooleanField(default=False),
        ),
    ]
