# Generated by Django 5.2.5 on 2025-09-12 23:06

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import Count, Max, Min


def backfill_direct_message_group_stats_fields(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    print()

    DirectMessageGroup = apps.get_model("zerver", "DirectMessageGroup")

    num_of_dm_groups = DirectMessageGroup.objects.all().count()
    print(f"Detected {num_of_dm_groups} direct message groups.")

    if num_of_dm_groups == 0:
        return

    dm_group_id_lower_bound = DirectMessageGroup.objects.earliest("id").id
    max_dm_group_id = DirectMessageGroup.objects.latest("id").id

    BATCH_SIZE = 1000
    # We would like to set the upper bound significantly past the maximum
    # dm group id, because it is likely that new Direct Message Groups are
    # created during this transaction, and their id is assigned as the one
    # right after the max id.
    max_dm_group_id += 100 * BATCH_SIZE

    while dm_group_id_lower_bound <= max_dm_group_id:
        do_backfill_stat_fields_for_direct_message_groups(
            apps,
            dm_group_id_lower_bound=dm_group_id_lower_bound,
            dm_group_id_upper_bound=min(dm_group_id_lower_bound + BATCH_SIZE, max_dm_group_id),
        )
        dm_group_id_lower_bound += BATCH_SIZE


def do_backfill_stat_fields_for_direct_message_groups(
    apps: StateApps,
    dm_group_id_lower_bound: int,
    dm_group_id_upper_bound: int,
) -> None:
    Message = apps.get_model("zerver", "Message")
    DirectMessageGroup = apps.get_model("zerver", "DirectMessageGroup")

    dm_groups = DirectMessageGroup.objects.filter(
        id__gte=dm_group_id_lower_bound,
        id__lt=dm_group_id_upper_bound,
    )

    recipient_id_to_dm_group = {dm_group.recipient_id: dm_group for dm_group in dm_groups}
    recipient_ids = recipient_id_to_dm_group.keys()

    stat_records = (
        Message.objects.filter(recipient_id__in=recipient_ids)
        .values("recipient_id")
        .annotate(min_message_id=Min("id"), max_message_id=Max("id"), total_messages=Count("id"))
        .values_list("recipient_id", "min_message_id", "max_message_id", "total_messages")
    )

    for recipient_id, min_message_id, max_message_id, total_messages in stat_records:
        if recipient_id in recipient_id_to_dm_group:
            dm_group = recipient_id_to_dm_group[recipient_id]
            dm_group.first_message_id = min_message_id
            dm_group.last_message_id = max_message_id
            dm_group.total_messages = total_messages

    DirectMessageGroup.objects.bulk_update(
        recipient_id_to_dm_group.values(),
        ["first_message_id", "last_message_id", "total_messages"],
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0753_directmessagegroup_add_stats_fields"),
    ]

    operations = [
        migrations.RunPython(
            backfill_direct_message_group_stats_fields,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
