# Generated by Django 5.2.6 on 2025-10-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0753_remove_google_blob_emojiset"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_inbox_show_channel_folders",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_inbox_show_channel_folders",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
