# Generated by Django 5.2.6 on 2025-10-14 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0752_remove_stream_is_in_zephyr_realm"),
        ("zerver", "0753_remove_google_blob_emojiset"),
    ]

    operations = []
