# Generated by Django 5.2.6 on 2025-10-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0754_merge_20251014_1855"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="week_start_day",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="week_start_day",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
