# Generated by Django 5.2.7 on 2025-10-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0754_merge_20251014_1855"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_inbox_show_channel_folders",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_inbox_show_channel_folders",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
