# Generated by Django 5.2.7 on 2025-10-25 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0754_merge_20251014_1855"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="can_unsubscribe_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
