# Generated by Django 5.2.7 on 2025-10-29 05:28

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("zerver", "0754_merge_20251014_1855"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="usermessage",
            index=models.Index(
                models.F("message"),
                condition=models.Q(("flags__andnz", 4096)),
                name="zerver_usermessage_message_active_mobile_push_notification_idx",
            ),
        ),
        migrations.RunSQL("ANALYZE zerver_usermessage"),
    ]
