# Generated by Django 5.0.6 on 2024-06-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zerver",
            "0755_usermessage_zerver_usermessage_message_active_mobile_push_notification_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatus",
            name="scheduled_end_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
