# Generated by Django 5.2.7 on 2025-11-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0756_handle_same_anonymous_group_used_for_multiple_streams"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_inbox_show_channel_folders",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_inbox_show_channel_folders",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
