# Generated by Django 5.2.7 on 2025-11-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zerver",
            "0755_usermessage_zerver_usermessage_message_active_mobile_push_notification_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_inbox_show_channel_folders",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_inbox_show_channel_folders",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
