# Generated by Django 5.2.6 on 2025-10-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0757_realmuserdefault_web_inbox_show_channel_folders_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pushdevice",
            name="push_public_key",
        ),
        migrations.AddField(
            model_name="pushdevice",
            name="push_key",
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
    ]
