# Generated by Django 5.2.7 on 2025-10-27 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0758_alter_stream_can_unsubscribe_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="can_unsubscribe_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
