# Generated by Django 5.2.7 on 2025-11-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0758_remove_pushdevice_push_public_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="default_newUser_avatar",
            field=models.CharField(
                choices=[
                    ("gravatar", "Gravatar"),
                    ("jdenticon", "Jdenticon"),
                    ("colorful_silhouette", "Colorful silhouette"),
                ],
                default="gravatar",
                max_length=30,
            ),
        ),
    ]
