# Generated by Django 5.2.6 on 2025-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0758_remove_pushdevice_push_public_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_imported_stub",
            field=models.BooleanField(default=False),
        ),
    ]
