# Generated by Django 5.2.7 on 2025-11-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0758_remove_pushdevice_push_public_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationuser",
            name="is_realm_importer",
            field=models.BooleanField(default=False),
        ),
    ]
