# Generated by Django 5.2.7 on 2025-11-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0759_userprofile_is_imported_stub"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationuser",
            name="is_realm_importer",
            field=models.BooleanField(default=False),
        ),
    ]
