# Generated by Django 5.2.7 on 2025-11-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0759_realm_default_newuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_source",
            field=models.CharField(
                choices=[
                    ("G", "Hosted by Gravatar"),
                    ("U", "Uploaded by user"),
                    ("D", "Default by Organisation Admin"),
                ],
                default="G",
                max_length=1,
            ),
        ),
    ]
