# Generated by Django 5.2.7 on 2025-11-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0760_preregistrationuser_is_realm_importer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customprofilefield",
            name="use_in_mentions",
            field=models.BooleanField(default=False),
        ),
    ]
