# Generated by Django 5.2.7 on 2025-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0760_preregistrationuser_is_realm_importer"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="default_avatar_provider",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Jdenticon"), (2, "Gravatar"), (3, "Colorful silhouettes")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="realm",
            name="icon_source",
            field=models.CharField(
                choices=[
                    ("G", "Hosted by Gravatar"),
                    ("U", "Uploaded by administrator"),
                    ("J", "Jdenticon"),
                ],
                default="J",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_source",
            field=models.CharField(
                choices=[
                    ("G", "Hosted by Gravatar"),
                    ("U", "Uploaded by user"),
                    ("J", "Jdenticon"),
                    ("S", "Colorful silhouettes"),
                ],
                default="G",
                max_length=1,
            ),
        ),
    ]
