# Generated by Django 5.2.7 on 2025-11-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0760_preregistrationuser_is_realm_importer"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="default_new_user_avatar",
            field=models.CharField(
                choices=[
                    ("gravatar", "Gravatar"),
                    ("jdenticon", "Jdenticon"),
                    ("colorful_silhouette", "Colorful silhouette"),
                ],
                default="gravatar",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_source",
            field=models.CharField(
                choices=[
                    ("G", "Hosted by Gravatar"),
                    ("U", "Uploaded by user"),
                    ("D", "Default by Organisation Admin"),
                ],
                default="G",
                max_length=1,
            ),
        ),
    ]
