# Generated by Django 5.2.7 on 2025-11-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0761_realm_send_channel_events_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="owner_full_content_access",
            field=models.BooleanField(default=False, db_default=False),
        ),
    ]
