# Generated by Django 5.2.7 on 2025-11-27 00:00

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def backfill_owner_full_content_access(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Realm = apps.get_model("zerver", "Realm")
    Realm.objects.all().update(owner_full_content_access=False)


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0761_realm_send_channel_events_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="owner_full_content_access",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            backfill_owner_full_content_access,
            elidable=True,
        ),
    ]
