# Generated by Django 5.2.7 on 2025-11-15 11:16

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def update_existing_realms(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Update existing realms that may have been created before this field existed
    or with the old default value. Set them all to 'gravatar' to maintain
    backward compatibility.
    """
    Realm = apps.get_model("zerver", "Realm")
    # Update all realms where default_new_user_avatar is not already set to gravatar
    Realm.objects.exclude(default_new_user_avatar="gravatar").update(
        default_new_user_avatar="gravatar"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0762_alter_userprofile_avatar_source_default"),
    ]

    operations = [
        migrations.RunPython(
            update_existing_realms,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
