# Generated by Django 5.2.7 on 2025-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0762_migrate_realms_using_y_rating_to_use_a_g_rating_for_giphy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="giphy_rating",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
