# Generated by Django 5.2.8 on 2025-12-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0763_migrate_realms_using_y_rating_to_use_a_g_rating_for_giphy"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="default_avatar_source",
            field=models.CharField(
                choices=[("G", "Hosted by Gravatar"), ("J", "Generated using Jdenticon")],
                default="J",
                max_length=1,
            ),
        ),
    ]
