# Generated by Django 5.2.4 on 2025-07-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zerver",
            "0763_migrate_realms_using_y_rating_to_use_a_g_rating_for_giphy",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="can_create_topic_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
