# Generated by Django 5.2.8 on 2025-12-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0766_alter_stream_can_create_topic_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertword",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
