# Generated by Django 5.2.8 on 2025-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0767_rename_zoom_token_to_video_call_provider_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmauditlog",
            name="scrubbed",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
