# Generated by Django 5.2.4 on 2025-07-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0768_realmauditlog_scrubbed"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_reaction_audible_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_reaction_desktop_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_reaction_audible_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_reaction_desktop_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
