# Generated by Django 5.2.8 on 2025-12-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0768_realmauditlog_scrubbed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customprofilefield",
            name="field_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (9, "Checkboxes"),
                    (4, "Date"),
                    (7, "External account"),
                    (5, "Link"),
                    (3, "List of options"),
                    (8, "Pronouns"),
                    (2, "Text (long)"),
                    (1, "Text (short)"),
                    (6, "Users"),
                ],
                default=1,
            ),
        ),
    ]
