# Generated by Django 5.2.8 on 2025-12-02 14:59

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def set_to_gravatar_for_existing_realms(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Realm = apps.get_model("zerver", "Realm")
    Realm.objects.all().update(default_avatar_source="G")


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0768_realmauditlog_scrubbed"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="default_avatar_source",
            field=models.CharField(
                choices=[("G", "Hosted by Gravatar"), ("J", "Generated using Jdenticon")],
                default="J",
                max_length=1,
            ),
        ),
        migrations.RunPython(
            set_to_gravatar_for_existing_realms, reverse_code=migrations.RunPython.noop
        ),
    ]
