# Generated by Django 5.2.8 on 2025-12-25 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0769_rename_profile_field_twitter_to_x"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmplayground",
            name="pygments_language",
            field=models.CharField(
                db_index=True,
                max_length=40,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid characters in pygments language",
                        regex="^[a-zA-Z0-9_+-./#]*$",
                    )
                ],
            ),
        ),
    ]
