# Generated by Django 5.2.9 on 2026-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0769_rename_profile_field_twitter_to_x"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="pin_direct_messages",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pin_direct_messages",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
