# Generated by Django 5.1.8 on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0770_botcommand"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_trusted_bot",
            field=models.BooleanField(default=False),
        ),
    ]
