# Generated by Django 5.1.8 on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0771_userprofile_is_trusted_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="submessage",
            name="visible_to",
            field=models.JSONField(null=True, default=None),
        ),
        migrations.AddField(
            model_name="archivedsubmessage",
            name="visible_to",
            field=models.JSONField(null=True, default=None),
        ),
    ]
