# Generated by Django 5.2.9 on 2026-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0771_alter_realmemoji_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="image_thumbnail_size",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
