# Generated by Django 5.2.6 on 2026-01-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0772_clean_up_imageattachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_smooth_scroll_navigation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_smooth_scroll_navigation",
            field=models.BooleanField(default=False),
        ),
    ]
