# Generated by Django 5.2.9 on 2026-01-13 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0772_clean_up_imageattachments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="realm",
            old_name="giphy_rating",
            new_name="gif_rating_policy",
        ),
    ]
