# Generated by Django 5.2.9 on 2026-01-19 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0770_realmuserdefault_pin_direct_messages_and_more"),
        ("zerver", "0772_clean_up_imageattachments"),
    ]

    operations = []
