# Generated by Django 5.2.9 on 2026-01-14 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0772_clean_up_imageattachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmplayground",
            name="pygments_language",
            field=models.CharField(
                db_index=True,
                max_length=40,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid characters in pygments language",
                        regex="^[a-zA-Z0-9_+-./#]*$",
                    ),
                ],
            ),
        ),
    ]
