# Generated by Django 5.2.10 on 2026-01-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0775_customprofilefield_use_for_user_matching"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="default_avatar_source",
            field=models.CharField(
                choices=[("G", "Hosted by Gravatar"), ("J", "Generated using Jdenticon")],
                default="J",
                max_length=1,
            ),
        ),
    ]
