# Generated by Django 5.2.10 on 2026-01-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0775_customprofilefield_use_for_user_matching"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="rendered_description_html",
            field=models.TextField(default=""),
        ),
    ]
