# Generated by Django 5.2.10 on 2026-02-05 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0776_realm_default_avatar_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedsubmessage",
            name="timestamp",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="submessage",
            name="timestamp",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
