# Generated by Django 5.x on 2024-XX-XX
# NOTE: This migration was auto-generated and should not be run until reviewed

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0776_realm_default_avatar_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="topic_resolution_message_requirement",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
