# Generated by Django 5.2.10 on 2026-02-04 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0776_preregistrationuser_require_invited_email"),
        ("zerver", "0776_realm_default_avatar_source"),
    ]

    operations = []
