# Generated by Django 5.2.10 on 2026-01-30 10:06

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0776_realm_default_avatar_source"),
    ]

    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name="reaction",
            index=models.Index(
                fields=["emoji_code", "message"], name="zerver_reaction_emoji_code_message_id"
            ),
        ),
    ]
