# Generated by Django 5.2.11 on 2026-02-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0776_realm_default_avatar_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_source",
            field=models.CharField(
                choices=[
                    ("G", "Hosted by Gravatar"),
                    ("J", "Generated using Jdenticon"),
                    ("U", "Uploaded by user"),
                ],
                default="G",
                max_length=1,
            ),
        ),
    ]
