# Generated by Django 5.2.9 on 2026-01-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0776_realm_default_avatar_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="rendered_description",
            field=models.TextField(default=None, null=True),
        ),
    ]
