# Generated by Django 5.2.9 on 2026-01-08 21:16
# BotPresence model was initially created here but has been replaced with
# unified presence in UserPresence. Bot presence is now tracked using the
# same UserPresence table with is_bot-aware logic.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0776_add_stream_puppet_model"),
    ]

    operations = []
