# Generated by Django 5.2.10 on 2026-01-30 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0776_realm_default_avatar_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("push_key", models.BinaryField(null=True)),
                ("push_key_id", models.BigIntegerField(null=True)),
                ("push_token_id", models.BigIntegerField(null=True)),
                ("pending_push_token_id", models.BigIntegerField(null=True)),
                (
                    "push_token_kind",
                    models.CharField(
                        choices=[("apns", "APNs"), ("fcm", "FCM")], max_length=4, null=True
                    ),
                ),
                (
                    "push_registration_error_code",
                    models.CharField(
                        choices=[
                            ("INVALID_BOUNCER_PUBLIC_KEY", "Invalid Bouncer Public Key"),
                            ("BAD_REQUEST", "Invalid Encrypted Push Registration"),
                            ("REQUEST_EXPIRED", "Request Expired"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
