# Generated by Django 5.2.10 on 2026-03-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0776_realm_default_avatar_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatchUpSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                ("ended_at", models.DateTimeField(db_index=True)),
                ("duration_ms", models.PositiveIntegerField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.client"
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.userprofile"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["realm", "ended_at"],
                        name="zerver_catchupsess_realm_id_ended_at_9f5c0c3a_idx",
                    ),
                    models.Index(
                        fields=["user_profile", "ended_at"],
                        name="zerver_catchupsess_user_profile_id_ended_at_d2e8f3d0_idx",
                    ),
                ],
            },
        ),
    ]
