# Generated by Django 5.2.11 on 2026-02-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0777_realm_rendered_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="rendered_description_version",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
