# Generated by Django 5.2.10 on 2026-04-24 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0777_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zerver.message",
            ),
        ),
    ]
