# Generated by Django 5.2.4 on 2025-08-08 02:52

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

SERVICE_BOT_TYPES = [3, 4]
# Before we add Service.triggers field, all Service bots by
# default have these triggers.
DEFAULT_SERVICE_BOT_TRIGGERS = ["all_direct_mentions", "dms_received"]


def update_service_bot_triggers(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Service = apps.get_model("zerver", "Service")
    bot_services = Service.objects.filter(user_profile__bot_type__in=SERVICE_BOT_TYPES, triggers=[])
    bot_services.update(triggers=DEFAULT_SERVICE_BOT_TRIGGERS)


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0777_service_triggers"),
    ]

    operations = [
        migrations.RunPython(update_service_bot_triggers),
    ]
