# Generated by Django 5.2.10 on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0777_catch_up_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatchUpSessionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("item_type", models.PositiveSmallIntegerField(choices=[(1, "stream_topic"), (2, "dm_personal"), (3, "dm_group")])),
                ("stream_id", models.IntegerField(null=True)),
                ("topic_name", models.TextField(null=True)),
                ("dm_sender_id", models.IntegerField(null=True)),
                ("dm_recipient_id", models.IntegerField(null=True)),
                ("first_message_id", models.PositiveIntegerField()),
                ("last_message_id", models.PositiveIntegerField()),
                ("message_count", models.PositiveIntegerField()),
                ("unread_count_at_surface", models.PositiveIntegerField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="zerver.catchupsession",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="zerver_catchupsessitem_session_id_created_at_7bd85a6d_idx",
                    )
                ],
            },
        ),
    ]

