# Generated by Django 5.2.11 on 2026-02-14 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0770_realmuserdefault_pin_direct_messages_and_more"),
        ("zerver", "0778_realm_rendered_description_version"),
    ]

    operations = []
