# Generated by Django 5.2.10 on 2026-04-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0778_task_message_nullable"),
        ("zerver", "0778_task_time_log"),
    ]

    operations = []
