# Generated by Django 5.2.11 on 2026-02-07 14:30
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0778_add_rendered_description_html_to_usergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="rendered_description_version",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
