# Generated by Django 5.2.10 on 2026-02-03 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0779_device"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PushDevice",
        ),
    ]
