# Generated by Django 5.2.5 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0780_delete_pushdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_smooth_topic_navigation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_smooth_topic_navigation",
            field=models.BooleanField(default=False),
        ),
    ]
