# Generated by Django 5.2.11 on 2026-02-19 15:17

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0780_delete_pushdevice"),
    ]

    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name="reaction",
            index=models.Index(
                fields=["emoji_code", "message"], name="zerver_reaction_emoji_code_message_id"
            ),
        ),
    ]
