# Generated by Django 5.2.11 on 2026-02-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0780_delete_pushdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatus",
            name="scheduled_end_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
