# Generated by Django 5.2.3 on 2026-02-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0782_set_default_value_for_can_change_name_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="name_changes_disabled",
        ),
        migrations.AlterField(
            model_name="realm",
            name="can_change_name_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
