# Generated by Django 5.2.7 on 2025-11-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0782_delete_unused_anonymous_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="triggers",
            field=models.JSONField(default=list),
        ),
    ]
