# Generated by Django 5.2.11 on 2026-03-05 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0777_submessage_timestamp"),
        ("zerver", "0784_realmfilter_reverse_template"),
    ]

    operations = []
