# Generated by Django 5.2.11 on 2026-02-19 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0784_realmfilter_reverse_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="workplace_users_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
