# Generated by Django 5.2.11 on 2026-02-19 02:23

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import OuterRef


def set_default_value_for_workplace_users_group(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Realm = apps.get_model("zerver", "Realm")
    NamedUserGroup = apps.get_model("zerver", "NamedUserGroup")

    EVERYONE_GROUP_NAME = "role:everyone"

    Realm.objects.filter(workplace_users_group=None).update(
        workplace_users_group=NamedUserGroup.objects.filter(
            name=EVERYONE_GROUP_NAME, realm=OuterRef("id"), is_system_group=True
        ).values("pk")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0785_realm_workplace_users_group"),
    ]

    operations = [
        migrations.RunPython(
            set_default_value_for_workplace_users_group,
            elidable=True,
            reverse_code=migrations.RunPython.noop,
        )
    ]
