# Generated by Django 5.2.11 on 2026-02-19 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0786_set_default_for_workplace_users_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="workplace_users_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="zerver.usergroup",
            ),
        ),
    ]
