# Generated by Django 5.2.11 on 2026-03-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0787_alter_realm_workplace_users_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="hidden_preview_urls",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="hidden_preview_urls",
            field=models.TextField(null=True),
        ),
    ]
