# Generated by Django 5.2.11 on 2026-02-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0787_alter_realm_workplace_users_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_left_sidebar_auto_collapse_views",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_left_sidebar_auto_collapse_views",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
