# Generated by Django 5.2.11 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0788_realmfilter_alternative_url_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedusergroup",
            name="rendered_description",
            field=models.TextField(db_default="", default=""),
        ),
    ]
