# Generated by Django 5.2.11 on 2026-03-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0783_recurringscheduledmessage"),
        ("zerver", "0788_realmfilter_alternative_url_templates"),
    ]

    operations = []
