# Generated by Django 5.2.11 on 2026-03-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0788_realmfilter_alternative_url_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
