# Generated by Django 5.2.11 on 2026-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0788_realmfilter_alternative_url_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customprofilefield",
            name="field_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (4, "Date"),
                    (3, "Dropdown"),
                    (7, "External account"),
                    (5, "Link"),
                    (2, "Paragraph"),
                    (9, "Phone number"),
                    (8, "Pronouns"),
                    (1, "Short text"),
                    (6, "Users"),
                ],
                default=1,
            ),
        ),
    ]
