# Generated by Django 5.2.11 on 2026-02-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0788_realmfilter_alternative_url_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistrationuser",
            name="external_auth_id",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="preregistrationuser",
            name="external_auth_method_name",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
