# Generated by Django 5.2.12 on 2026-03-15 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0782_stream_wildcard_mention_policy"),
        ("zerver", "0788_realmfilter_alternative_url_templates"),
    ]

    operations = []
