# Generated by Django 5.2.12 on 2026-03-30 12:51
import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0789_add_external_auth_fields_to_preregistrationuser"),
    ]

    operations = [
        # For backfilling existing custom emojis.
        migrations.AddField(
            model_name="realmemoji",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2001, 1, 1, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.AlterField(
            model_name="realmemoji",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
