# Generated by Django 5.2.12 on 2026-03-20 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0770_realmuserdefault_pin_direct_messages_and_more"),
        ("zerver", "0789_add_external_auth_fields_to_preregistrationuser"),
    ]

    operations = []
