# Generated by Django 5.2.12 on 2026-03-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0785_followeduser"),
        ("zerver", "0789_add_external_auth_fields_to_preregistrationuser"),
    ]

    operations = []
