# Generated by Django 5.2.11 on 2026-03-11 00:00

from dataclasses import dataclass
from typing import Any, cast

from django.conf import settings
from django.db import migrations, transaction
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

BATCH_SIZE = 1000
SUBDOMAIN_FOR_ROOT_DOMAIN = ""


@dataclass
class RealmForRendering:
    id: int
    string_id: str
    default_code_block_language: str

    @property
    def host(self) -> str:
        if self.string_id == SUBDOMAIN_FOR_ROOT_DOMAIN:
            return settings.EXTERNAL_HOST
        default_host = f"{self.string_id}.{settings.EXTERNAL_HOST}"
        return settings.REALM_HOSTS.get(self.string_id, default_host)

    @property
    def url(self) -> str:
        return settings.EXTERNAL_URI_SCHEME + self.host


def render_user_group_description(text: str, realm: RealmForRendering) -> str:
    if text == "":
        return ""

    # nosemgrep: tools.dont-import-models-in-migrations
    from zerver.lib.markdown import markdown_convert

    return markdown_convert(text, message_realm=cast(Any, realm), no_previews=True).rendered_content


def backfill_namedusergroup_rendered_description(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    NamedUserGroup = apps.get_model("zerver", "NamedUserGroup")

    last_id = 0
    realms: dict[int, RealmForRendering] = {}

    while True:
        user_groups = list(
            NamedUserGroup.objects.select_related("realm")
            .filter(id__gt=last_id, rendered_description="")
            .exclude(description="")
            .order_by("id")[:BATCH_SIZE]
        )
        if not user_groups:
            break

        for user_group in user_groups:
            realm = realms.get(user_group.realm_id)
            if realm is None:
                realm = RealmForRendering(
                    id=user_group.realm_id,
                    string_id=user_group.realm.string_id,
                    default_code_block_language=user_group.realm.default_code_block_language,
                )
                realms[user_group.realm_id] = realm
            user_group.rendered_description = render_user_group_description(
                user_group.description, realm
            )

        with transaction.atomic():
            NamedUserGroup.objects.bulk_update(
                user_groups, ["rendered_description"], batch_size=BATCH_SIZE
            )

        last_id = user_groups[-1].id


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0789_namedusergroup_rendered_description"),
    ]

    operations = [
        migrations.RunPython(
            backfill_namedusergroup_rendered_description,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
