# Generated by Django 5.2.12 on 2026-03-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0789_add_external_auth_fields_to_preregistrationuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_link_previews_enabled",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_link_previews_enabled",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
