# Generated by Django 5.2.12 on 2026-03-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0789_add_external_auth_fields_to_preregistrationuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="pin_views_section",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pin_views_section",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
