# Generated by Django 5.2.11 on 2026-03-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0789_add_external_auth_fields_to_preregistrationuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="topic_resolution_message_requirement",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
