# Generated by Django 5.2.12 on 2026-03-22 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0789_add_external_auth_fields_to_preregistrationuser"),
        ("zerver", "0789_merge_20260315_1955"),
    ]

    operations = []
