# Generated by Django 5.2.12 on 2026-03-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0789_add_external_auth_fields_to_preregistrationuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealmBigBlueButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("option", models.CharField(db_index=True, max_length=255)),
                ("value", models.CharField(max_length=50, null=True)),
                ("data_type", models.CharField(default="str", max_length=4)),
                ("parameter_type", models.CharField(default="create_param", max_length=13)),
                ("real_option", models.CharField(default="", max_length=100)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
    ]
