# Generated by Django 5.2.12 on 2026-03-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0790_merge_20260318_2030"),
        ("zerver", "0790_merge_20260318_2151"),
    ]

    operations = []
