# Generated by Django 5.2.11 on 2026-03-10 16:01
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0790_merge_20260322_0949"),
    ]
    operations = [
        migrations.AddField(
            model_name="stream",
            name="wildcard_mention_policy",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
