# Generated by Django 5.2.11 on 2026-03-14 18:24
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0791_stream_wildcard_mention_policy"),
    ]
    operations = [
        migrations.AlterField(
            model_name="stream",
            name="wildcard_mention_policy",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
