# Generated by Django 5.2.12 on 2026-03-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0790_followeduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_followed_user_email_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_followed_user_push_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_followed_user_email_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_followed_user_push_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
