# Generated by Django 5.2.12 on 2026-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0792_stream_wildcard_mention_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="wildcard_mention_policy",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
