# Generated by Django 5.2.12 on 2026-04-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0790_followeduser"),
        ("zerver", "0792_realmuserdefault_enable_followed_user_email_notifications_and_more"),
    ]

    operations = []
