# Generated by Django 5.2.12 on 2026-04-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0792_fix_animated_emoji_still_images"),
        ("zerver", "0793_alter_stream_wildcard_mention_policy"),
    ]

    operations = []
