# Generated by Django 5.2 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0800_cleanup_case_mismatched_legacy_apns_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_source",
            field=models.CharField(
                choices=[
                    ("G", "Hosted by Gravatar"),
                    ("J", "Generated using Jdenticon"),
                    ("U", "Uploaded by user"),
                    ("I", "Unknown user avatar"),
                ],
                default="J",
                max_length=1,
            ),
        ),
    ]
