# Generated by Django 5.2.14 on 2026-05-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0800_cleanup_case_mismatched_legacy_apns_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="color",
            field=models.CharField(db_default="#c2c2c2", default="#c2c2c2", max_length=10),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_muted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="pin_to_top",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
