# Generated by Django 5.2.13 on 2026-05-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0800_cleanup_case_mismatched_legacy_apns_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="topic_resolution_message_requirement",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
