# Generated by Django 5.2.12 on 2026-03-30 12:51

import django.utils.timezone
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import Exists, OuterRef

REALM_EMOJI_ADDED = 226


def backfill_emoji_date_created(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    RealmEmoji = apps.get_model("zerver", "RealmEmoji")
    RealmAuditLog = apps.get_model("zerver", "RealmAuditLog")
    Realm = apps.get_model("zerver", "Realm")
    has_emoji = RealmEmoji.objects.filter(realm_id=OuterRef("pk"))

    realm_data = (
        Realm.objects.annotate(has_emojis=Exists(has_emoji))
        .filter(has_emojis=True)
        .values_list("id", "date_created")
    )

    for realm_id, realm_date_created in realm_data.iterator():
        emojis_in_realm = RealmEmoji.objects.filter(realm_id=realm_id).only(
            "id", "realm_id", "date_created"
        )
        emoji_logs = list(
            RealmAuditLog.objects.filter(event_type=REALM_EMOJI_ADDED, realm_id=realm_id).order_by(
                "event_time"
            )
        )
        # If the REALM_EMOJI_ADDED audit log record doesn't exist for an emoji,
        # use the event time when the first REALM_EMOJI_ADDED log
        # in the realm was created, if present, else use the realm's
        # creation date as the final fallback.
        fallback_date = emoji_logs[0].event_time if len(emoji_logs) > 0 else realm_date_created
        emoji_to_creation_date = {}
        for log in emoji_logs:
            added_emoji = log.extra_data.get("added_emoji", {})
            emoji_id = int(added_emoji.get("id"))
            emoji_to_creation_date[emoji_id] = log.event_time
        for emoji in emojis_in_realm:
            emoji.date_created = emoji_to_creation_date.get(emoji.id, fallback_date)
        RealmEmoji.objects.bulk_update(emojis_in_realm, ["date_created"])


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0800_cleanup_case_mismatched_legacy_apns_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmemoji",
            name="date_created",
            field=models.DateTimeField(null=True, default=None),
        ),
        migrations.RunPython(backfill_emoji_date_created, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="realmemoji",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now, null=False),
        ),
    ]
