# Generated by Django 5.2.13 on 2026-05-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0801_realmexport_backfill_export_from_prior_server_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customprofilefield",
            name="rendered_name",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="customprofilefield",
            name="rendered_hint",
            field=models.TextField(default=""),
        ),
    ]
