# Generated by Django 5.2.14 on 2026-06-08 12:26

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0801_realmexport_backfill_export_from_prior_server_status"),
    ]

    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name="reaction",
            index=models.Index(
                fields=["emoji_code", "message"], name="zerver_reaction_emoji_code_message_id"
            ),
        ),
    ]
