# Generated by Django 5.2.5 on 2025-09-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0801_realmexport_backfill_export_from_prior_server_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessagegroup",
            name="first_message",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_message_group_first",
                to="zerver.message",
            ),
        ),
        migrations.AddField(
            model_name="directmessagegroup",
            name="last_message",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_message_group_last",
                to="zerver.message",
            ),
        ),
        migrations.AddField(
            model_name="directmessagegroup",
            name="total_messages",
            field=models.IntegerField(default=0),
        ),
    ]
