# Generated by Django 5.2.3 on 2026-02-21 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0803_alter_realm_can_change_own_name_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="name_changes_disabled",
        ),
    ]
