# Generated by Django 5.2.11 on 2026-03-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0804_backfill_user_created_audit_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="hidden_preview_urls",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="hidden_preview_urls",
            field=models.JSONField(default=None, null=True),
        ),
    ]
