# Generated by Django 5.2.14 on 2026-07-02 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import zerver.lib.utils


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0804_backfill_user_created_audit_logs"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "api_key",
                    models.CharField(
                        default=zerver.lib.utils.generate_api_key, max_length=32, unique=True
                    ),
                ),
                ("is_revoked", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="api_key",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
