# Generated by Django 5.2.14 on 2026-06-29 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0804_backfill_user_created_audit_logs"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMCPApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used", models.DateTimeField(default=None, null=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
