# Generated by Django 5.2.14 on 2026-06-23 17:37

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0804_backfill_user_created_audit_logs"),
    ]

    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name="reaction",
            index=models.Index(
                fields=["emoji_code", "message"], name="zerver_reaction_emoji_code_message_id"
            ),
        ),
    ]
