# Generated by Django 5.2.14 on 2026-07-02 13:39

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import Max


def copy_api_keys(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    UserProfile = apps.get_model("zerver", "UserProfile")
    UserAPIKey = apps.get_model("zerver", "UserAPIKey")
    RealmAuditLog = apps.get_model("zerver", "RealmAuditLog")

    LEGACY_API_KEY_DESCRIPTION = "Legacy API key"
    USER_API_KEY_CHANGED = 127

    for user in UserProfile.objects.all().iterator():
        # First, compute the date the user's API key last changed:
        last_key_regeneration_date = RealmAuditLog.objects.filter(
            modified_user_id=user.id,
            event_type=USER_API_KEY_CHANGED,
        ).aggregate(Max("event_time"))["event_time__max"]

        if last_key_regeneration_date is not None:
            date_created = last_key_regeneration_date
        else:
            # Most API keys will never never been regenerated after
            # RealmAuditLogs were implemented, so if there are no
            # records of the API key changing, for this user, we assume
            # it was created the same time as the user
            date_created = user.date_joined

        UserAPIKey.objects.create(
            user_id=user.id,
            api_key=user.api_key,
            description=LEGACY_API_KEY_DESCRIPTION,
            date_created=date_created,
        )


def reverse_copy_api_keys(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    UserProfile = apps.get_model("zerver", "UserProfile")
    UserAPIKey = apps.get_model("zerver", "UserAPIKey")

    for user in UserProfile.objects.all().iterator():
        user_api_key = UserAPIKey.objects.filter(user_id=user.id).order_by("id").first()
        if user_api_key is not None:
            user.api_key = user_api_key.api_key
            user.save(update_fields=["api_key"])


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0805_userapikey_table"),
    ]

    operations = [
        migrations.RunPython(copy_api_keys, reverse_code=reverse_copy_api_keys),
    ]
