# Generated by Django 5.2.14 on 2026-06-18 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0804_backfill_user_created_audit_logs"),
        ("zerver", "0806_alter_stream_can_access_stream_topics_group"),
    ]

    operations = []
