# Generated by Django 5.2.16 on 2026-08-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0806_stream_default_push_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="removed_preview_urls",
            field=models.JSONField(db_default=[], default=list),
        ),
        migrations.AddField(
            model_name="message",
            name="removed_preview_urls",
            field=models.JSONField(db_default=[], default=list),
        ),
    ]
