# Generated by Django 5.2.15 on 2026-07-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0806_stream_default_push_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="enable_mcp_access",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
