# Generated by Django 5.2.16 on 2026-08-02 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0806_stream_default_push_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmplayground",
            name="pygments_language",
            field=models.CharField(
                db_index=True,
                max_length=40,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid characters in pygments language", regex="^[a-z0-9_+-./#]+$"
                    )
                ],
            ),
        ),
    ]
