# Generated by Django 5.2.14 on 2026-07-02 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0806_backfill_user_profile_api_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="api_key",
        ),
    ]
