# Generated by Django 5.2.12 on 2026-04-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0806_stream_default_push_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="triggers",
            field=models.JSONField(default=list),
        ),
    ]
