# Generated by Django 5.2.16 on 2026-08-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0807_usertopic_zerver_usertopic_user_visibility_recipient_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="split_group_id",
            field=models.CharField(db_index=True, max_length=36, null=True),
        ),
    ]
