# Generated by Django 5.2.15 on 2026-07-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0807_usertopic_zerver_usertopic_user_visibility_recipient_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="enable_mcp_read_access",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
