# Generated by Django 5.2.4 on 2025-07-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0807_usertopic_zerver_usertopic_user_visibility_recipient_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_reaction_audible_notifications",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_reaction_desktop_notifications",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_reaction_audible_notifications",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_reaction_desktop_notifications",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
