# Generated by Django 5.0 on 2024-01-01 00:00

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

OLD_DESKTOP_ICON_COUNT_DISPLAY_NONE = 4
NEW_DESKTOP_ICON_COUNT_DISPLAY_NONE = 5


def renumber_options(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    # We added a new option 'DESKTOP_ICON_COUNT_DISPLAY_CURRENT_CONVERSATION'
    # for 'desktop_icon_count_display' setting. It has the value 4.
    # The following option is renumbered:
    # * 'DESKTOP_ICON_COUNT_DISPLAY_NONE' from 4 to 5
    # The migration is to update these values.
    RealmUserDefault = apps.get_model("zerver", "RealmUserDefault")
    UserProfile = apps.get_model("zerver", "UserProfile")

    UserProfile.objects.filter(
        desktop_icon_count_display=OLD_DESKTOP_ICON_COUNT_DISPLAY_NONE
    ).update(desktop_icon_count_display=NEW_DESKTOP_ICON_COUNT_DISPLAY_NONE)
    RealmUserDefault.objects.filter(
        desktop_icon_count_display=OLD_DESKTOP_ICON_COUNT_DISPLAY_NONE
    ).update(desktop_icon_count_display=NEW_DESKTOP_ICON_COUNT_DISPLAY_NONE)


def reverse_code(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    RealmUserDefault = apps.get_model("zerver", "RealmUserDefault")
    UserProfile = apps.get_model("zerver", "UserProfile")

    UserProfile.objects.filter(
        desktop_icon_count_display=NEW_DESKTOP_ICON_COUNT_DISPLAY_NONE
    ).update(desktop_icon_count_display=OLD_DESKTOP_ICON_COUNT_DISPLAY_NONE)
    RealmUserDefault.objects.filter(
        desktop_icon_count_display=NEW_DESKTOP_ICON_COUNT_DISPLAY_NONE
    ).update(desktop_icon_count_display=OLD_DESKTOP_ICON_COUNT_DISPLAY_NONE)


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0809_remove_message_nulls_last_topic_indexes"),
    ]

    operations = [
        migrations.RunPython(renumber_options, reverse_code=reverse_code, elidable=True),
    ]
