# Generated by Django 5.2.13 on 2026-05-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0809_remove_message_nulls_last_topic_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="customprofilefield",
            name="rendered_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="customprofilefield",
            name="rendered_hint",
            field=models.TextField(null=True),
        ),
    ]
