# Generated by Django 5.2.12 on 2026-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0809_remove_message_nulls_last_topic_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="message_content_allowed_in_email_notifications",
            field=models.BooleanField(default=True, db_default=True),
        ),
    ]
