# Generated by Django 5.2.12 on 2026-04-13 06:32

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

MESSAGE_TRIGGERED_BOT_TYPES = [3, 4]
# Before we add Service.triggers field, all message-triggered bots by
# default have these triggers.
DEFAULT_BOT_TRIGGERS = ["all_direct_mentions", "dms_received"]


def update_bots_service_triggers(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Service = apps.get_model("zerver", "Service")
    bot_services = Service.objects.filter(
        user_profile__bot_type__in=MESSAGE_TRIGGERED_BOT_TYPES, triggers=[]
    )
    bot_services.update(triggers=DEFAULT_BOT_TRIGGERS)


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0810_service_triggers"),
    ]

    operations = [
        migrations.RunPython(
            update_bots_service_triggers,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
