# Generated by Django 5.2.17 on 2026-09-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0810_delete_unused_anonymous_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="display_offline_users",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="display_offline_users",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
