# Generated by Django 5.2.17 on 2026-09-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0811_usermessage_add_hide_link_previews"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="default_color",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
