# Generated by Django 5.2.12 on 2026-04-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0811_usermessage_add_hide_link_previews"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_dm_collapse_policy",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_dm_collapse_policy",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
