# Generated by Django 5.2.17 on 2026-10-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0812_delete_inaccessible_user_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="customprofilefield",
            name="rendered_hint",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="customprofilefield",
            name="rendered_name",
            field=models.TextField(default=None, null=True),
        ),
    ]
