# Generated by Django 5.2.17 on 2026-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0812_delete_inaccessible_user_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="split_message_on_send",
            field=models.BooleanField(default=False),
        ),
    ]
