# Generated by Django 5.2.17 on 2026-10-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0812_delete_inaccessible_user_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="web_right_click_opens_message_actions_menu",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="web_right_click_opens_message_actions_menu",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
