# Generated by Django 5.2.11 on 2026-07-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0804_backfill_user_created_audit_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="miatsuco_inline_upload_preview",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
