# Generated by Django 5.2.11 on 2026-07-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0804_backfill_user_created_audit_logs"),
        ("zerver", "miatsuco_0001_add_inline_upload_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="miatsuco_web_show_upload_thumbnails",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="miatsuco_web_show_upload_thumbnails",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
