from typing import Text

from zerver.lib.test_classes import WebhookTestCase

class HoneybadgerWebHookTests(WebhookTestCase):
    STREAM_NAME = 'honeybadger'
    URL_TEMPLATE = "/api/v1/external/honeybadger?api_key={api_key}"
    FIXTURE_DIR_NAME = "honeybadger"

    def test_checkin(self) -> None:
        expected_subject = u"check_in_missing"
        expected_message = ('**[Zulip Integration] MISSING: Zulip hasn\'t checked in for 6 minutes**\n'
                            '**14:53:02 2017-12-29**: [Site](https://api.honeybadger.io/v1/check_in/15mIYe)')

        self.send_and_test_stream_message('checkin', expected_subject, expected_message,
                                          content_type="application/x-www-form-urlencoded")

    def test_uptime(self) -> None:
        expected_subject = u"up: Zulip"
        expected_message = ('**[Zulip Integration] Zulip will now receive uptime alerts.**\n'
                            '**Site**: [Zulip](https://zulipint.slack.com)')

        self.send_and_test_stream_message('uptime', expected_subject, expected_message,
                                          content_type="application/x-www-form-urlencoded")

    def test_error(self) -> None:
        expected_subject = u"occurred: Zulip Integration"
        expected_message = ('**[Zulip Integration/production] TestingException: '
                            'This is a test error generated by Honeybadger**\n'
                            '`This is a test error generated by Honeybadger`\n'
                            '**Site**: [Zulip Integration](https://app.honeybadger.io/projects/54639/faults/123)')

        self.send_and_test_stream_message('test_error', expected_subject, expected_message,
                                          content_type="application/x-www-form-urlencoded")

    def get_body(self, fixture_name: Text) -> Text:
        return self.fixture_data("honeybadger", fixture_name, file_type="json")
