#! /usr/bin/env sh

set -e
set x

cat <<EOF
This script will completely wipe your database, including all users, chat
messages, and metadata.  It will not modify your existing /etc/zulip
configuration files, but all other database-backed data will disappear. This
script is targeting /home/zulip/deployments/current.

Do you want to continue? You must type YES.
EOF

read -r yesno

if [ "x$yesno" != "xYES" ]; then
  >&2 echo "Exiting without changes."
  exit 1;
fi

if [ "$(id -u)" -ne "0" ]; then
  >&2 echo "Exiting because root is not available."
  exit 1
fi

/home/zulip/deployments/current/scripts/setup/postgres-init-db
/home/zulip/deployments/current/scripts/setup/initialize-database
