#!/usr/bin/env bash
set -e
set -x

# What user should we use for connecting to the database
POSTGRES_USER="${POSTGRES_USER:-postgres}"

(
# Make sure the current working directory is readable by postgres
cd /

su "$POSTGRES_USER" -c 'psql zulip' <<EOF
SET search_path = zulip,public,pgroonga,pg_catalog;

DROP INDEX zerver_message_search_pgroonga;
ALTER TABLE zerver_message DROP COLUMN search_pgroonga;

SET search_path = zulip,public;

ALTER ROLE zulip SET search_path TO zulip,public;

DROP EXTENSION pgroonga CASCADE;
EOF
)

# Clear memcached to avoid contamination from previous database state
sh "$(dirname "$0")/flush-memcached"

echo "PGroonga is disabled"
