#!/usr/bin/env python3

import os
import sys

BASE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../..")
sys.path.append(BASE_DIR)

import scripts.lib.setup_path_on_import
from zproject import settings
import pylibmc

pylibmc.Client(
    [settings.MEMCACHED_LOCATION],
    behaviors=settings.CACHES["default"]["OPTIONS"]  # type: ignore # settings not typed properly
).flush_all()
