#!/usr/bin/env -S uv run --frozen --no-config --only-group=prod --preview-features=target-workspace-discovery --script  # -*-python-*-
import os

import bmemcached
from django.conf import settings

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "zproject.settings")

cache = settings.CACHES["default"]
match cache["BACKEND"]:
    case "django.core.cache.backends.locmem.LocMemCache":
        pass
    case "zerver.lib.singleton_bmemcached.SingletonBMemcached":
        client = bmemcached.Client((cache["LOCATION"],), **cache["OPTIONS"])
        try:
            client.flush_all()
        finally:
            client.disconnect_all()
    case _:
        raise ValueError(f"Unrecognized cache backend {cache['BACKEND']}")
