#!/bin/bash
if [ "$EUID" -ne 0 ];
    then
    echo "Error: Script is running with insufficient privileges. Please re-run using sudo."
    exit
fi
mkdir -p /var/log/zulip
"$(dirname "$(dirname "$0")")/lib/install" "$@" 2>&1 | tee -a /var/log/zulip/install.log
