#!/bin/bash -xe

# Assumes we've already been untarred
if [ -z "$1" ]; then
    echo "Usage: install <ZULIP_TARBALL>"
    exit 1
fi
tarball="$1"

# First, install any updates from the apt repo that may be needed
cat >/etc/apt/sources.list.d/zulip.list <<EOF
deb http://apt.zulip.com/enterprise precise v1
EOF
apt-get update
apt-get -y dist-upgrade
apt-get install -y puppet git
cp -a /root/zulip/puppet/zulip/files/puppet.conf /etc/puppet/

mkdir /etc/zulip
echo -e "[machine]\npuppet_classes = zulip::local_server" > /etc/zulip/zulip.conf
/root/zulip/scripts/zulip-puppet-apply -f

# These server restarting bits should be moveable into puppet-land, ideally
apt-get -y upgrade
if [ -e "/etc/init.d/nginx" ]; then
    service nginx restart
fi
if [ -e "/etc/init.d/apache2" ]; then
    service apache2 restart
fi

deploy_path=$($(dirname $(dirname $0))/unpack-zulip "$tarball")
ln -nsf "$deploy_path" /home/zulip/deployments/current
chown -R zulip:zulip /home/zulip/deployments

set +x
cat <<EOF

 Done.

 Now do the next step!

EOF
