#!/usr/bin/env bash
set -e

POSTGRES_USER="postgres"
if [ "$(uname)" = "OpenBSD" ]; then
  POSTGRES_USER="_postgresql"
fi

cd /

username=$1

shift
tables="$(printf "'%s'," "${@//\'/\'\'}")"
tables="${tables%,}"

if [ "$EUID" -eq 0 ]; then
    su - "$POSTGRES_USER" -c "psql postgres '$POSTGRES_USER'" <<EOF
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname IN ($tables);
EOF
else
    psql -h localhost postgres "$username" <<EOF
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname IN ($tables);
EOF
fi
