location /static/onboarding-video/ {
    alias /home/zulip/prod-static/onboarding-video/;
    error_page 404 /django_static_404.html;
    include /etc/nginx/zulip-include/headers;
    add_header Access-Control-Allow-Origin *;
    add_header Timing-Allow-Origin *;
    add_header Cache-Control "public, max-age=31536000, immutable";
}

location = /static/onboarding-video/zulip-10.mp4 {
    return 302 aa5f785576fe61d8dedf4f56e79489b20381d8bc30ba3ae19d23ecdf8e1f2564.mp4;
}
