from typing import Dict, List, Optional, TypeVar, Any, Text
from zerver.lib.integrations import Integration, INTEGRATIONS

class IFTTTIntegration(Integration):

    def __init__(self, name: str, categories: Optional[List[str]]=None,
                 display_name: Optional[str]=None, logo: Optional[str]=None,
                 logo_alt: Optional[str]=None) -> None:
        if logo_alt is None:
            logo_alt = "{} logo".format(name.title())
        self.logo_alt = logo_alt

        if logo is None:
            logo = "static/images/integrations/logos/ifttt.svg"

        if categories is None:
            categories = ['ifttt-integration']

        super().__init__(
            name, name, categories,
            logo=logo, display_name=display_name,
            doc='zerver/integrations/ifttt_common.md'
        )

    def is_hidden(self) -> bool:
        return True

IFTTT_INTEGRATIONS = [
    IFTTTIntegration("500px", display_name="500px", logo_alt="500px logo"),
    IFTTTIntegration("aclu", display_name="ACLU", logo_alt="ACLU logo"),
    IFTTTIntegration("artik-cloud", display_name="ARTIK Cloud", logo_alt="ARTIK Cloud logo"),
    IFTTTIntegration("asus-router", display_name="ASUS Router", logo_alt="ASUS Router logo"),
    IFTTTIntegration("at&t-m2x", display_name="AT&T M2X", logo_alt="AT&T M2X logo"),
    IFTTTIntegration("axa-home", display_name="AXA Home", logo_alt="AXA Home logo"),
    IFTTTIntegration("acer-air-monitor", display_name="Acer Air Monitor",
                     logo_alt="Acer Air Monitor logo"),
    IFTTTIntegration("adafruit", display_name="Adafruit", logo_alt="Adafruit logo"),
    IFTTTIntegration("aeon-matrix", display_name="Aeon Matrix", logo_alt="Aeon Matrix logo"),
    IFTTTIntegration("air-by-propeller", display_name="Air by Propeller",
                     logo_alt="Air by Propeller logo"),
    IFTTTIntegration("airnow", display_name="AirNow", logo_alt="AirNow logo"),
    IFTTTIntegration("airpatrol-wifi", display_name="AirPatrol WiFi",
                     logo_alt="AirPatrol WiFi logo"),
    IFTTTIntegration("airtable", display_name="Airtable", logo_alt="Airtable logo"),
    IFTTTIntegration("almond", display_name="Almond", logo_alt="Almond logo"),
    IFTTTIntegration("amarr-entrematic", display_name="Amarr Entrematic",
                     logo_alt="Amarr Entrematic logo"),
    IFTTTIntegration("amazon-alexa", display_name="Amazon Alexa",
                     logo_alt="Amazon Alexa logo"),
    IFTTTIntegration("amazon-cloud-drive", display_name="Amazon Cloud Drive", logo_alt="Amazon Cloud Drive logo"),
    IFTTTIntegration("ambi-climate", display_name="Ambi Climate", logo_alt="Ambi Climate logo"),
    IFTTTIntegration("ambient-weather", display_name="Ambient Weather", logo_alt="Ambient Weather logo"),
    IFTTTIntegration("amdocs-connected-home", display_name="Amdocs Connected Home", logo_alt="Amdocs Connected Home logo"),
    IFTTTIntegration("american-psychological-association", display_name="American Psychological Association", logo_alt="American Psychological Association logo"),
    IFTTTIntegration("amtrak", display_name="Amtrak", logo_alt="Amtrak logo"),
    IFTTTIntegration("android-battery", display_name="Android Battery", logo_alt="Android Battery logo"),
    IFTTTIntegration("android-device", display_name="Android Device", logo_alt="Android Device logo"),
    IFTTTIntegration("android-phone-call", display_name="Android Phone Call", logo_alt="Android Phone Call logo"),
    IFTTTIntegration("android-photos", display_name="Android Photos", logo_alt="Android Photos logo"),
    IFTTTIntegration("android-sms", display_name="Android SMS", logo_alt="Android SMS logo"),
    IFTTTIntegration("android-wear", display_name="Android Wear", logo_alt="Android Wear logo"),
    IFTTTIntegration("angelcam", display_name="Angelcam", logo_alt="Angelcam logo"),
    IFTTTIntegration("anymote-smart-remote", display_name="AnyMote Smart Remote", logo_alt="AnyMote Smart Remote logo"),
    IFTTTIntegration("appzapp", display_name="AppZapp", logo_alt="AppZapp logo"),
    IFTTTIntegration("appkettle", display_name="Appkettle", logo_alt="Appkettle logo"),
    IFTTTIntegration("apple-app-store", display_name="Apple App Store", logo_alt="Apple App Store logo"),
    IFTTTIntegration("arlo", display_name="Arlo", logo_alt="Arlo logo"),
    IFTTTIntegration("arrayent-devkit", display_name="Arrayent DevKit", logo_alt="Arrayent DevKit logo"),
    IFTTTIntegration("asana", display_name="Asana", logo_alt="Asana logo"),
    IFTTTIntegration("august", display_name="August", logo_alt="August logo"),
    IFTTTIntegration("aura", display_name="Aura", logo_alt="Aura logo"),
    IFTTTIntegration("aura-frames", display_name="Aura Frames", logo_alt="Aura Frames logo"),
    IFTTTIntegration("automatic-classic", display_name="Automatic Classic", logo_alt="Automatic Classic logo"),
    IFTTTIntegration("automatic-pro", display_name="Automatic Pro", logo_alt="Automatic Pro logo"),
    IFTTTIntegration("awair", display_name="Awair", logo_alt="Awair logo"),
    IFTTTIntegration("awair-glow", display_name="Awair Glow", logo_alt="Awair Glow logo"),
    IFTTTIntegration("bmw-labs", display_name="BMW Labs", logo_alt="BMW Labs logo"),
    IFTTTIntegration("bond", display_name="BOND", logo_alt="BOND logo"),
    IFTTTIntegration("ballotpedia", display_name="Ballotpedia", logo_alt="Ballotpedia logo"),
    IFTTTIntegration("bang-&-olufsen's-beolink-gateway", display_name="Bang & Olufsen's BeoLink Gateway", logo_alt="Bang & Olufsen's BeoLink Gateway logo"),
    IFTTTIntegration("bbox-miami", display_name="Bbox Miami", logo_alt="Bbox Miami logo"),
    IFTTTIntegration("beeminder", display_name="Beeminder", logo_alt="Beeminder logo"),
    IFTTTIntegration("beseye", display_name="Beseye", logo_alt="Beseye logo"),
    IFTTTIntegration("best-buy", display_name="Best Buy", logo_alt="Best Buy logo"),
    IFTTTIntegration("bhome", display_name="Bhome", logo_alt="Bhome logo"),
    IFTTTIntegration("bitmark", display_name="Bitmark", logo_alt="Bitmark logo"),
    IFTTTIntegration("bixi", display_name="Bixi", logo_alt="Bixi logo"),
    IFTTTIntegration("blink", display_name="Blink", logo_alt="Blink logo"),
    IFTTTIntegration("blink-(europe)", display_name="Blink (Europe)", logo_alt="Blink (Europe) logo"),
    IFTTTIntegration("blogger", display_name="Blogger", logo_alt="Blogger logo"),
    IFTTTIntegration("bloomsky-weather", display_name="BloomSky Weather", logo_alt="BloomSky Weather logo"),
    IFTTTIntegration("blueair-aware", display_name="Blueair Aware", logo_alt="Blueair Aware logo"),
    IFTTTIntegration("blueair-classic-05", display_name="Blueair Classic 05", logo_alt="Blueair Classic 05 logo"),
    IFTTTIntegration("blueair-classic-i", display_name="Blueair Classic i", logo_alt="Blueair Classic i logo"),
    IFTTTIntegration("blueair-sense+", display_name="Blueair Sense+", logo_alt="Blueair Sense+ logo"),
    IFTTTIntegration("bouncie", display_name="Bouncie", logo_alt="Bouncie logo"),
    IFTTTIntegration("box", display_name="Box", logo_alt="Box logo"),
    IFTTTIntegration("boxcar-2", display_name="Boxcar 2", logo_alt="Boxcar 2 logo"),
    IFTTTIntegration("boxoh-package-tracking", display_name="Boxoh Package Tracking", logo_alt="Boxoh Package Tracking logo"),
    IFTTTIntegration("brainyquote", display_name="BrainyQuote", logo_alt="BrainyQuote logo"),
    IFTTTIntegration("bright", display_name="Bright", logo_alt="Bright logo"),
    IFTTTIntegration("bttn", display_name="Bttn", logo_alt="Bttn logo"),
    IFTTTIntegration("buffer", display_name="Buffer", logo_alt="Buffer logo"),
    IFTTTIntegration("bureau-of-economic-analysis", display_name="Bureau of Economic Analysis", logo_alt="Bureau of Economic Analysis logo"),
    IFTTTIntegration("button-widget", display_name="Button widget", logo_alt="Button widget logo"),
    IFTTTIntegration("cnct-life", display_name="CNCT Life", logo_alt="CNCT Life logo"),
    IFTTTIntegration("caleo", display_name="Caleo", logo_alt="Caleo logo"),
    IFTTTIntegration("caltrain", display_name="Caltrain", logo_alt="Caltrain logo"),
    IFTTTIntegration("camera-widget", display_name="Camera widget", logo_alt="Camera widget logo"),
    IFTTTIntegration("camio", display_name="Camio", logo_alt="Camio logo"),
    IFTTTIntegration("centers-for-disease-control-and-prevention", display_name="Centers for Disease Control and Prevention", logo_alt="Centers for Disease Control and Prevention logo"),
    IFTTTIntegration("chain", display_name="Chain", logo_alt="Chain logo"),
    IFTTTIntegration("chicago-transit-authority", display_name="Chicago Transit Authority", logo_alt="Chicago Transit Authority logo"),
    IFTTTIntegration("chiekoo-bell", display_name="Chiekoo Bell", logo_alt="Chiekoo Bell logo"),
    IFTTTIntegration("circle", display_name="Circle", logo_alt="Circle logo"),
    IFTTTIntegration("cisco-spark", display_name="Cisco Spark", logo_alt="Cisco Spark logo"),
    IFTTTIntegration("city-of-tampa,-florida", display_name="City of Tampa, Florida", logo_alt="City of Tampa, Florida logo"),
    IFTTTIntegration("classifieds", display_name="Classifieds", logo_alt="Classifieds logo"),
    IFTTTIntegration("clicksend-sms", display_name="ClickSend SMS", logo_alt="ClickSend SMS logo"),
    IFTTTIntegration("clinicaltrials.gov", display_name="ClinicalTrials.gov", logo_alt="ClinicalTrials.gov logo"),
    IFTTTIntegration("code-school", display_name="Code School", logo_alt="Code School logo"),
    IFTTTIntegration("cogitai-continua", display_name="Cogitai Continua", logo_alt="Cogitai Continua logo"),
    IFTTTIntegration("comed-hourly-pricing", display_name="ComEd Hourly Pricing", logo_alt="ComEd Hourly Pricing logo"),
    IFTTTIntegration("comed-peak-time-savings", display_name="ComEd Peak Time Savings", logo_alt="ComEd Peak Time Savings logo"),
    IFTTTIntegration("comcast-labs", display_name="Comcast Labs", logo_alt="Comcast Labs logo"),
    IFTTTIntegration("concierge", display_name="Concierge", logo_alt="Concierge logo"),
    IFTTTIntegration("concur-labs", display_name="Concur Labs", logo_alt="Concur Labs logo"),
    IFTTTIntegration("connected-thermostat", display_name="Connected Thermostat", logo_alt="Connected Thermostat logo"),
    IFTTTIntegration("convo", display_name="Convo", logo_alt="Convo logo"),
    IFTTTIntegration("cronologics", display_name="Cronologics", logo_alt="Cronologics logo"),
    IFTTTIntegration("d-link-connected-home-camera", display_name="D-Link Connected Home Camera", logo_alt="D-Link Connected Home Camera logo"),
    IFTTTIntegration("d-link-motion-sensor", display_name="D-Link Motion Sensor", logo_alt="D-Link Motion Sensor logo"),
    IFTTTIntegration("d-link-siren", display_name="D-Link Siren", logo_alt="D-Link Siren logo"),
    IFTTTIntegration("d-link-smart-plug", display_name="D-Link Smart Plug", logo_alt="D-Link Smart Plug logo"),
    IFTTTIntegration("d-link-water-sensor", display_name="D-Link Water Sensor", logo_alt="D-Link Water Sensor logo"),
    IFTTTIntegration("dart", display_name="DART", logo_alt="DART logo"),
    IFTTTIntegration("daikin-online-controller", display_name="Daikin Online Controller", logo_alt="Daikin Online Controller logo"),
    IFTTTIntegration("dailymotion", display_name="Dailymotion", logo_alt="Dailymotion logo"),
    IFTTTIntegration("danalock", display_name="Danalock", logo_alt="Danalock logo"),
    IFTTTIntegration("das-keyboard-q", display_name="Das Keyboard Q", logo_alt="Das Keyboard Q logo"),
    IFTTTIntegration("dash", display_name="Dash", logo_alt="Dash logo"),
    IFTTTIntegration("date-&-time", display_name="Date & Time", logo_alt="Date & Time logo"),
    IFTTTIntegration("day-one", display_name="Day One", logo_alt="Day One logo"),
    IFTTTIntegration("deezer", display_name="Deezer", logo_alt="Deezer logo"),
    IFTTTIntegration("delicious", display_name="Delicious", logo_alt="Delicious logo"),
    IFTTTIntegration("department-of-agriculture", display_name="Department of Agriculture", logo_alt="Department of Agriculture logo"),
    IFTTTIntegration("department-of-defense", display_name="Department of Defense", logo_alt="Department of Defense logo"),
    IFTTTIntegration("department-of-labor", display_name="Department of Labor", logo_alt="Department of Labor logo"),
    IFTTTIntegration("department-of-state", display_name="Department of State", logo_alt="Department of State logo"),
    IFTTTIntegration("digg", display_name="Digg", logo_alt="Digg logo"),
    IFTTTIntegration("diigo", display_name="Diigo", logo_alt="Diigo logo"),
    IFTTTIntegration("docsend", display_name="DocSend", logo_alt="DocSend logo"),
    IFTTTIntegration("domino's", display_name="Domino's", logo_alt="Domino's logo"),
    IFTTTIntegration("donation-manager-redcloud™", display_name="Donation Manager RedCloud™", logo_alt="Donation Manager RedCloud™ logo"),
    IFTTTIntegration("dropbox", display_name="Dropbox", logo_alt="Dropbox logo"),
    IFTTTIntegration("espn", display_name="ESPN", logo_alt="ESPN logo"),
    IFTTTIntegration("eve-for-tesla", display_name="EVE For Tesla", logo_alt="EVE For Tesla logo"),
    IFTTTIntegration("ezviz", display_name="EZVIZ", logo_alt="EZVIZ logo"),
    IFTTTIntegration("eagle-eye-nubocam", display_name="Eagle Eye NuboCam", logo_alt="Eagle Eye NuboCam logo"),
    IFTTTIntegration("edyn", display_name="Edyn", logo_alt="Edyn logo"),
    IFTTTIntegration("eight", display_name="Eight", logo_alt="Eight logo"),
    IFTTTIntegration("electronic-frontier-foundation", display_name="Electronic Frontier Foundation", logo_alt="Electronic Frontier Foundation logo"),
    IFTTTIntegration("ello", display_name="Ello", logo_alt="Ello logo"),
    IFTTTIntegration("email", display_name="Email", logo_alt="Email logo"),
    IFTTTIntegration("email-digest", display_name="Email Digest", logo_alt="Email Digest logo"),
    IFTTTIntegration("emberlight", display_name="Emberlight", logo_alt="Emberlight logo"),
    IFTTTIntegration("energenie-mi|home", display_name="Energenie Mi|Home", logo_alt="Energenie Mi|Home logo"),
    IFTTTIntegration("energy-information-administration", display_name="Energy Information Administration", logo_alt="Energy Information Administration logo"),
    IFTTTIntegration("environmental-protection-agency", display_name="Environmental Protection Agency", logo_alt="Environmental Protection Agency logo"),
    IFTTTIntegration("envoy", display_name="Envoy", logo_alt="Envoy logo"),
    IFTTTIntegration("equal-rights-advocates", display_name="Equal Rights Advocates", logo_alt="Equal Rights Advocates logo"),
    IFTTTIntegration("evernote", display_name="Evernote", logo_alt="Evernote logo"),
    IFTTTIntegration("everykit", display_name="EveryKit", logo_alt="EveryKit logo"),
    IFTTTIntegration("facebook", display_name="Facebook", logo_alt="Facebook logo"),
    IFTTTIntegration("facebook-messenger", display_name="Facebook Messenger", logo_alt="Facebook Messenger logo"),
    IFTTTIntegration("facebook-pages", display_name="Facebook Pages", logo_alt="Facebook Pages logo"),
    IFTTTIntegration("federal-communications-commission", display_name="Federal Communications Commission", logo_alt="Federal Communications Commission logo"),
    IFTTTIntegration("feedly", display_name="Feedly", logo_alt="Feedly logo"),
    IFTTTIntegration("fitbit", display_name="Fitbit", logo_alt="Fitbit logo"),
    IFTTTIntegration("fiverr", display_name="Fiverr", logo_alt="Fiverr logo"),
    IFTTTIntegration("fleep", display_name="Fleep", logo_alt="Fleep logo"),
    IFTTTIntegration("flic", display_name="Flic", logo_alt="Flic logo"),
    IFTTTIntegration("flickr", display_name="Flickr", logo_alt="Flickr logo"),
    IFTTTIntegration("flock", display_name="Flock", logo_alt="Flock logo"),
    IFTTTIntegration("flux-smart-light", display_name="Flux Smart Light", logo_alt="Flux Smart Light logo"),
    IFTTTIntegration("followup.cc", display_name="FollowUp.cc", logo_alt="FollowUp.cc logo"),
    IFTTTIntegration("foobot", display_name="Foobot", logo_alt="Foobot logo"),
    IFTTTIntegration("fortinet", display_name="Fortinet", logo_alt="Fortinet logo"),
    IFTTTIntegration("foursquare", display_name="Foursquare", logo_alt="Foursquare logo"),
    IFTTTIntegration("fox-news", display_name="Fox News", logo_alt="Fox News logo"),
    IFTTTIntegration("futurehome", display_name="Futurehome", logo_alt="Futurehome logo"),
    IFTTTIntegration("ge-appliances-cooking", display_name="GE Appliances Cooking", logo_alt="GE Appliances Cooking logo"),
    IFTTTIntegration("ge-appliances-dishwasher", display_name="GE Appliances Dishwasher", logo_alt="GE Appliances Dishwasher logo"),
    IFTTTIntegration("ge-appliances-dryer", display_name="GE Appliances Dryer", logo_alt="GE Appliances Dryer logo"),
    IFTTTIntegration("ge-appliances-geospring™", display_name="GE Appliances GeoSpring™", logo_alt="GE Appliances GeoSpring™ logo"),
    IFTTTIntegration("ge-appliances-refrigerator", display_name="GE Appliances Refrigerator", logo_alt="GE Appliances Refrigerator logo"),
    IFTTTIntegration("ge-appliances-washer", display_name="GE Appliances Washer", logo_alt="GE Appliances Washer logo"),
    IFTTTIntegration("ge-appliances-window-ac", display_name="GE Appliances Window AC", logo_alt="GE Appliances Window AC logo"),
    IFTTTIntegration("go", display_name="GO", logo_alt="GO logo"),
    IFTTTIntegration("garadget", display_name="Garadget", logo_alt="Garadget logo"),
    IFTTTIntegration("garageio", display_name="Garageio", logo_alt="Garageio logo"),
    IFTTTIntegration("genius", display_name="Genius", logo_alt="Genius logo"),
    IFTTTIntegration("genius-hub", display_name="Genius Hub", logo_alt="Genius Hub logo"),
    IFTTTIntegration("getsafe", display_name="GetSafe", logo_alt="GetSafe logo"),
    IFTTTIntegration("gideon-smart-home", display_name="Gideon Smart Home", logo_alt="Gideon Smart Home logo"),
    IFTTTIntegration("giphy", display_name="Giphy", logo_alt="Giphy logo"),
    IFTTTIntegration("github", display_name="GitHub", logo_alt="GitHub logo"),
    IFTTTIntegration("glance-clock", display_name="Glance Clock", logo_alt="Glance Clock logo"),
    IFTTTIntegration("gmail", display_name="Gmail", logo_alt="Gmail logo"),
    IFTTTIntegration("gogogate", display_name="Gogogate", logo_alt="Gogogate logo"),
    IFTTTIntegration("google-assistant", display_name="Google Assistant", logo_alt="Google Assistant logo"),
    IFTTTIntegration("google-calendar", display_name="Google Calendar", logo_alt="Google Calendar logo"),
    IFTTTIntegration("google-contacts", display_name="Google Contacts", logo_alt="Google Contacts logo"),
    IFTTTIntegration("google-docs", display_name="Google Docs", logo_alt="Google Docs logo"),
    IFTTTIntegration("google-drive", display_name="Google Drive", logo_alt="Google Drive logo"),
    IFTTTIntegration("google-glass", display_name="Google Glass", logo_alt="Google Glass logo"),
    IFTTTIntegration("google-photos", display_name="Google Photos", logo_alt="Google Photos logo"),
    IFTTTIntegration("google-sheets", display_name="Google Sheets", logo_alt="Google Sheets logo"),
    IFTTTIntegration("google-wifi", display_name="Google Wifi", logo_alt="Google Wifi logo"),
    IFTTTIntegration("grants.gov", display_name="Grants.gov", logo_alt="Grants.gov logo"),
    IFTTTIntegration("greeniq", display_name="GreenIQ", logo_alt="GreenIQ logo"),
    IFTTTIntegration("greenwave-systems", display_name="Greenwave Systems", logo_alt="Greenwave Systems logo"),
    IFTTTIntegration("groupme", display_name="GroupMe", logo_alt="GroupMe logo"),
    IFTTTIntegration("guardpeanut", display_name="GuardPeanut", logo_alt="GuardPeanut logo"),
    IFTTTIntegration("guardzilla", display_name="Guardzilla", logo_alt="Guardzilla logo"),
    IFTTTIntegration("gumroad", display_name="Gumroad", logo_alt="Gumroad logo"),
    IFTTTIntegration("hp-print", display_name="HP Print", logo_alt="HP Print logo"),
    IFTTTIntegration("hacker-news", display_name="Hacker News", logo_alt="Hacker News logo"),
    IFTTTIntegration("hager-iot", display_name="Hager IoT", logo_alt="Hager IoT logo"),
    IFTTTIntegration("halo-smart-labs", display_name="Halo Smart Labs", logo_alt="Halo Smart Labs logo"),
    IFTTTIntegration("harmony", display_name="Harmony", logo_alt="Harmony logo"),
    IFTTTIntegration("harvest", display_name="Harvest", logo_alt="Harvest logo"),
    IFTTTIntegration("heatmiser", display_name="Heatmiser", logo_alt="Heatmiser logo"),
    IFTTTIntegration("hive-active-heating™---uk-and-europe", display_name="Hive Active Heating™ - UK and Europe", logo_alt="Hive Active Heating™ - UK and Europe logo"),
    IFTTTIntegration("hive-active-light™", display_name="Hive Active Light™", logo_alt="Hive Active Light™ logo"),
    IFTTTIntegration("hive-active-plug™", display_name="Hive Active Plug™", logo_alt="Hive Active Plug™ logo"),
    IFTTTIntegration("hive-active-thermostat™---us-and-canada", display_name="Hive Active Thermostat™ - US and Canada", logo_alt="Hive Active Thermostat™ - US and Canada logo"),
    IFTTTIntegration("home-connect-coffee-machine", display_name="Home Connect Coffee Machine", logo_alt="Home Connect Coffee Machine logo"),
    IFTTTIntegration("home-connect-dishwasher", display_name="Home Connect Dishwasher", logo_alt="Home Connect Dishwasher logo"),
    IFTTTIntegration("home-connect-dryer", display_name="Home Connect Dryer", logo_alt="Home Connect Dryer logo"),
    IFTTTIntegration("home-connect-fridge", display_name="Home Connect Fridge", logo_alt="Home Connect Fridge logo"),
    IFTTTIntegration("home-connect-hood", display_name="Home Connect Hood", logo_alt="Home Connect Hood logo"),
    IFTTTIntegration("home-connect-oven", display_name="Home Connect Oven", logo_alt="Home Connect Oven logo"),
    IFTTTIntegration("home-connect-washer", display_name="Home Connect Washer", logo_alt="Home Connect Washer logo"),
    IFTTTIntegration("home8", display_name="Home8", logo_alt="Home8 logo"),
    IFTTTIntegration("homecontrol-flex", display_name="HomeControl Flex", logo_alt="HomeControl Flex logo"),
    IFTTTIntegration("homeseer", display_name="HomeSeer", logo_alt="HomeSeer logo"),
    IFTTTIntegration("homeboy", display_name="Homeboy", logo_alt="Homeboy logo"),
    IFTTTIntegration("homey", display_name="Homey", logo_alt="Homey logo"),
    IFTTTIntegration("honeywell-lyric", display_name="Honeywell Lyric", logo_alt="Honeywell Lyric logo"),
    IFTTTIntegration("honeywell-single-zone-thermostat", display_name="Honeywell Single-zone Thermostat", logo_alt="Honeywell Single-zone Thermostat logo"),
    IFTTTIntegration("honeywell-total-connect-comfort", display_name="Honeywell Total Connect Comfort", logo_alt="Honeywell Total Connect Comfort logo"),
    IFTTTIntegration("honeywell-evohome", display_name="Honeywell evohome", logo_alt="Honeywell evohome logo"),
    IFTTTIntegration("hunter-douglas-powerview", display_name="Hunter Douglas PowerView", logo_alt="Hunter Douglas PowerView logo"),
    IFTTTIntegration("ibm-watson-workspace", display_name="IBM Watson Workspace", logo_alt="IBM Watson Workspace logo"),
    IFTTTIntegration("icq", display_name="ICQ", logo_alt="ICQ logo"),
    IFTTTIntegration("ifttt", display_name="IFTTT", logo_alt="IFTTT logo"),
    IFTTTIntegration("instyle", display_name="InStyle", logo_alt="InStyle logo"),
    IFTTTIntegration("inoreader", display_name="Inoreader", logo_alt="Inoreader logo"),
    IFTTTIntegration("instagram", display_name="Instagram", logo_alt="Instagram logo"),
    IFTTTIntegration("instapaper", display_name="Instapaper", logo_alt="Instapaper logo"),
    IFTTTIntegration("instapush", display_name="Instapush", logo_alt="Instapush logo"),
    IFTTTIntegration("instawell", display_name="Instawell", logo_alt="Instawell logo"),
    IFTTTIntegration("international-monetary-fund", display_name="International Monetary Fund", logo_alt="International Monetary Fund logo"),
    IFTTTIntegration("intesishome", display_name="IntesisHome", logo_alt="IntesisHome logo"),
    IFTTTIntegration("invoxia-triby", display_name="Invoxia Triby", logo_alt="Invoxia Triby logo"),
    IFTTTIntegration("iot-podcast", display_name="IoT Podcast", logo_alt="IoT Podcast logo"),
    IFTTTIntegration("is-it-christmas", display_name="Is It Christmas?", logo_alt="Is It Christmas? logo"),
    IFTTTIntegration("ivideon", display_name="Ivideon", logo_alt="Ivideon logo"),
    IFTTTIntegration("jibo", display_name="Jibo", logo_alt="Jibo logo"),
    IFTTTIntegration("jotform", display_name="JotForm", logo_alt="JotForm logo"),
    IFTTTIntegration("keenai", display_name="Keenai", logo_alt="Keenai logo"),
    IFTTTIntegration("kevo", display_name="Kevo", logo_alt="Kevo logo"),
    IFTTTIntegration("king-county-metro", display_name="King County Metro", logo_alt="King County Metro logo"),
    IFTTTIntegration("kronaby", display_name="Kronaby", logo_alt="Kronaby logo"),
    IFTTTIntegration("kyber-calendars,-todos-&-reminders", display_name="Kyber calendars, todos & reminders", logo_alt="Kyber calendars, todos & reminders logo"),
    IFTTTIntegration("lg-dryer", display_name="LG Dryer", logo_alt="LG Dryer logo"),
    IFTTTIntegration("lg-smartphone", display_name="LG Smartphone", logo_alt="LG Smartphone logo"),
    IFTTTIntegration("lg-washer", display_name="LG Washer", logo_alt="LG Washer logo"),
    IFTTTIntegration("lifx", display_name="LIFX", logo_alt="LIFX logo"),
    IFTTTIntegration("line", display_name="LINE", logo_alt="LINE logo"),
    IFTTTIntegration("lspx-p1", display_name="LSPX-P1", logo_alt="LSPX-P1 logo"),
    IFTTTIntegration("lametric", display_name="LaMetric", logo_alt="LaMetric logo"),
    IFTTTIntegration("leeo", display_name="Leeo", logo_alt="Leeo logo"),
    IFTTTIntegration("library-of-congress", display_name="Library of Congress", logo_alt="Library of Congress logo"),
    IFTTTIntegration("liebherr", display_name="Liebherr", logo_alt="Liebherr logo"),
    IFTTTIntegration("life360", display_name="Life360", logo_alt="Life360 logo"),
    IFTTTIntegration("lightwaverf-events", display_name="LightwaveRF Events", logo_alt="LightwaveRF Events logo"),
    IFTTTIntegration("lightwaverf-heating", display_name="LightwaveRF Heating", logo_alt="LightwaveRF Heating logo"),
    IFTTTIntegration("lightwaverf-lighting", display_name="LightwaveRF Lighting", logo_alt="LightwaveRF Lighting logo"),
    IFTTTIntegration("lightwaverf-power", display_name="LightwaveRF Power", logo_alt="LightwaveRF Power logo"),
    IFTTTIntegration("linear-pro-access", display_name="Linear PRO Access", logo_alt="Linear PRO Access logo"),
    IFTTTIntegration("link-shades", display_name="Link Shades", logo_alt="Link Shades logo"),
    IFTTTIntegration("linkdesk", display_name="LinkDesk", logo_alt="LinkDesk logo"),
    IFTTTIntegration("linkedin", display_name="LinkedIn", logo_alt="LinkedIn logo"),
    IFTTTIntegration("location", display_name="Location", logo_alt="Location logo"),
    IFTTTIntegration("lockitron", display_name="Lockitron", logo_alt="Lockitron logo"),
    IFTTTIntegration("logitech-pop", display_name="Logitech POP", logo_alt="Logitech POP logo"),
    IFTTTIntegration("lutron-caséta-and-ra2-select", display_name="Lutron Caséta and RA2 Select", logo_alt="Lutron Caséta and RA2 Select logo"),
    IFTTTIntegration("luxafor", display_name="Luxafor", logo_alt="Luxafor logo"),
    IFTTTIntegration("lynx-technology", display_name="Lynx Technology", logo_alt="Lynx Technology logo"),
    IFTTTIntegration("mesh", display_name="MESH", logo_alt="MESH logo"),
    IFTTTIntegration("magichue", display_name="MagicHue", logo_alt="MagicHue logo"),
    IFTTTIntegration("magiclight-wifi", display_name="MagicLight WiFi", logo_alt="MagicLight WiFi logo"),
    IFTTTIntegration("mailchimp", display_name="MailChimp", logo_alt="MailChimp logo"),
    IFTTTIntegration("manything", display_name="Manything", logo_alt="Manything logo"),
    IFTTTIntegration("maryland-state-highway-administration", display_name="Maryland State Highway Administration", logo_alt="Maryland State Highway Administration logo"),
    IFTTTIntegration("mateverse", display_name="Mateverse", logo_alt="Mateverse logo"),
    IFTTTIntegration("medium", display_name="Medium", logo_alt="Medium logo"),
    IFTTTIntegration("meistertask", display_name="MeisterTask", logo_alt="MeisterTask logo"),
    IFTTTIntegration("melissa", display_name="Melissa", logo_alt="Melissa logo"),
    IFTTTIntegration("memobird", display_name="Memobird", logo_alt="Memobird logo"),
    IFTTTIntegration("messagebird", display_name="MessageBird", logo_alt="MessageBird logo"),
    IFTTTIntegration("migo", display_name="MiGo", logo_alt="MiGo logo"),
    IFTTTIntegration("microbot-push-for-prota", display_name="MicroBot Push for Prota", logo_alt="MicroBot Push for Prota logo"),
    IFTTTIntegration("minut", display_name="Minut", logo_alt="Minut logo"),
    IFTTTIntegration("misfit", display_name="Misfit", logo_alt="Misfit logo"),
    IFTTTIntegration("mojio", display_name="Mojio", logo_alt="Mojio logo"),
    IFTTTIntegration("moni.ai", display_name="Moni.ai", logo_alt="Moni.ai logo"),
    IFTTTIntegration("mosaic", display_name="Mosaic", logo_alt="Mosaic logo"),
    IFTTTIntegration("musaic", display_name="Musaic", logo_alt="Musaic logo"),
    IFTTTIntegration("musixmatch", display_name="Musixmatch", logo_alt="Musixmatch logo"),
    IFTTTIntegration("muzik", display_name="Muzik", logo_alt="Muzik logo"),
    IFTTTIntegration("my-cloud-home", display_name="My Cloud Home", logo_alt="My Cloud Home logo"),
    IFTTTIntegration("my-leviton", display_name="My Leviton", logo_alt="My Leviton logo"),
    IFTTTIntegration("myq", display_name="MyQ", logo_alt="MyQ logo"),
    IFTTTIntegration("mywakes", display_name="MyWakes", logo_alt="MyWakes logo"),
    IFTTTIntegration("myfox-homecontrol", display_name="Myfox HomeControl", logo_alt="Myfox HomeControl logo"),
    IFTTTIntegration("nibe-uplink", display_name="NIBE Uplink", logo_alt="NIBE Uplink logo"),
    IFTTTIntegration("niu", display_name="NIU", logo_alt="NIU logo"),
    IFTTTIntegration("nj-transit", display_name="NJ Transit", logo_alt="NJ Transit logo"),
    IFTTTIntegration("npr", display_name="NPR", logo_alt="NPR logo"),
    IFTTTIntegration("nanoleaf-smarter-series", display_name="Nanoleaf Smarter Series", logo_alt="Nanoleaf Smarter Series logo"),
    IFTTTIntegration("narrative", display_name="Narrative", logo_alt="Narrative logo"),
    IFTTTIntegration("narro", display_name="Narro", logo_alt="Narro logo"),
    IFTTTIntegration("national-science-foundation", display_name="National Science Foundation", logo_alt="National Science Foundation logo"),
    IFTTTIntegration("national-vulnerability-database", display_name="National Vulnerability Database", logo_alt="National Vulnerability Database logo"),
    IFTTTIntegration("nature-remo", display_name="Nature Remo", logo_alt="Nature Remo logo"),
    IFTTTIntegration("neato", display_name="Neato", logo_alt="Neato logo"),
    IFTTTIntegration("nefit-easy", display_name="Nefit Easy", logo_alt="Nefit Easy logo"),
    IFTTTIntegration("nest-cam", display_name="Nest Cam", logo_alt="Nest Cam logo"),
    IFTTTIntegration("nest-protect", display_name="Nest Protect", logo_alt="Nest Protect logo"),
    IFTTTIntegration("nest-thermostat", display_name="Nest Thermostat", logo_alt="Nest Thermostat logo"),
    IFTTTIntegration("netatmo-security", display_name="Netatmo Security", logo_alt="Netatmo Security logo"),
    IFTTTIntegration("netatmo-thermostat", display_name="Netatmo Thermostat", logo_alt="Netatmo Thermostat logo"),
    IFTTTIntegration("netatmo-weather-station", display_name="Netatmo Weather Station", logo_alt="Netatmo Weather Station logo"),
    IFTTTIntegration("neurio", display_name="Neurio", logo_alt="Neurio logo"),
    IFTTTIntegration("newsblur", display_name="NewsBlur", logo_alt="NewsBlur logo"),
    IFTTTIntegration("nex", display_name="Nex", logo_alt="Nex logo"),
    IFTTTIntegration("nexia", display_name="Nexia", logo_alt="Nexia logo"),
    IFTTTIntegration("nice", display_name="Nice", logo_alt="Nice logo"),
    IFTTTIntegration("nightingale", display_name="Nightingale", logo_alt="Nightingale logo"),
    IFTTTIntegration("nimbus-note", display_name="Nimbus Note", logo_alt="Nimbus Note logo"),
    IFTTTIntegration("nokia-home", display_name="Nokia Home", logo_alt="Nokia Home logo"),
    IFTTTIntegration("note-widget", display_name="Note widget", logo_alt="Note widget logo"),
    IFTTTIntegration("notifications", display_name="Notifications", logo_alt="Notifications logo"),
    IFTTTIntegration("nuki", display_name="Nuki", logo_alt="Nuki logo"),
    IFTTTIntegration("orbnext", display_name="ORBneXt", logo_alt="ORBneXt logo"),
    IFTTTIntegration("oui.sncf", display_name="OUI.sncf", logo_alt="OUI.sncf logo"),
    IFTTTIntegration("oco-camera", display_name="Oco Camera", logo_alt="Oco Camera logo"),
    IFTTTIntegration("office-365-calendar", display_name="Office 365 Calendar", logo_alt="Office 365 Calendar logo"),
    IFTTTIntegration("office-365-contacts", display_name="Office 365 Contacts", logo_alt="Office 365 Contacts logo"),
    IFTTTIntegration("office-365-mail", display_name="Office 365 Mail", logo_alt="Office 365 Mail logo"),
    IFTTTIntegration("onedrive", display_name="OneDrive", logo_alt="OneDrive logo"),
    IFTTTIntegration("onedrive-for-business", display_name="OneDrive for Business", logo_alt="OneDrive for Business logo"),
    IFTTTIntegration("onenote", display_name="OneNote", logo_alt="OneNote logo"),
    IFTTTIntegration("ooma", display_name="Ooma", logo_alt="Ooma logo"),
    IFTTTIntegration("optus-smart-living", display_name="Optus Smart Living", logo_alt="Optus Smart Living logo"),
    IFTTTIntegration("orion", display_name="Orion", logo_alt="Orion logo"),
    IFTTTIntegration("oticon", display_name="Oticon", logo_alt="Oticon logo"),
    IFTTTIntegration("pavlok", display_name="PAVLOK", logo_alt="PAVLOK logo"),
    IFTTTIntegration("particle", display_name="Particle", logo_alt="Particle logo"),
    IFTTTIntegration("pebblebee", display_name="Pebblebee", logo_alt="Pebblebee logo"),
    IFTTTIntegration("pert", display_name="Pert", logo_alt="Pert logo"),
    IFTTTIntegration("pew-research-center", display_name="Pew Research Center", logo_alt="Pew Research Center logo"),
    IFTTTIntegration("philips-hue", display_name="Philips Hue", logo_alt="Philips Hue logo"),
    IFTTTIntegration("phone-call-(us-only)", display_name="Phone Call (US only)", logo_alt="Phone Call (US only) logo"),
    IFTTTIntegration("pinboard", display_name="Pinboard", logo_alt="Pinboard logo"),
    IFTTTIntegration("pinterest", display_name="Pinterest", logo_alt="Pinterest logo"),
    IFTTTIntegration("piper", display_name="Piper", logo_alt="Piper logo"),
    IFTTTIntegration("plum", display_name="Plum", logo_alt="Plum logo"),
    IFTTTIntegration("pocket", display_name="Pocket", logo_alt="Pocket logo"),
    IFTTTIntegration("polar3d", display_name="Polar3D", logo_alt="Polar3D logo"),
    IFTTTIntegration("printhug", display_name="Printhug", logo_alt="Printhug logo"),
    IFTTTIntegration("propublica", display_name="ProPublica", logo_alt="ProPublica logo"),
    IFTTTIntegration("product-hunt", display_name="Product Hunt", logo_alt="Product Hunt logo"),
    IFTTTIntegration("prota", display_name="Prota", logo_alt="Prota logo"),
    IFTTTIntegration("pruvan", display_name="Pruvan", logo_alt="Pruvan logo"),
    IFTTTIntegration("pryv", display_name="Pryv", logo_alt="Pryv logo"),
    IFTTTIntegration("pushalot", display_name="Pushalot", logo_alt="Pushalot logo"),
    IFTTTIntegration("pushbullet", display_name="Pushbullet", logo_alt="Pushbullet logo"),
    IFTTTIntegration("pushover", display_name="Pushover", logo_alt="Pushover logo"),
    IFTTTIntegration("qnap", display_name="QNAP", logo_alt="QNAP logo"),
    IFTTTIntegration("qapital", display_name="Qapital", logo_alt="Qapital logo"),
    IFTTTIntegration("qblinks-qmote", display_name="Qblinks Qmote", logo_alt="Qblinks Qmote logo"),
    IFTTTIntegration("qualitytime", display_name="QualityTime", logo_alt="QualityTime logo"),
    IFTTTIntegration("quartz", display_name="Quartz", logo_alt="Quartz logo"),
    IFTTTIntegration("quip", display_name="Quip", logo_alt="Quip logo"),
    IFTTTIntegration("rss-feed", display_name="RSS Feed", logo_alt="RSS Feed logo"),
    IFTTTIntegration("rachio", display_name="Rachio", logo_alt="Rachio logo"),
    IFTTTIntegration("rainmachine", display_name="RainMachine", logo_alt="RainMachine logo"),
    IFTTTIntegration("rankwyz", display_name="RankWyz", logo_alt="RankWyz logo"),
    IFTTTIntegration("recon", display_name="Recon", logo_alt="Recon logo"),
    IFTTTIntegration("remember-the-milk", display_name="Remember The Milk", logo_alt="Remember The Milk logo"),
    IFTTTIntegration("remotelync", display_name="RemoteLync", logo_alt="RemoteLync logo"),
    IFTTTIntegration("rescuetime", display_name="RescueTime", logo_alt="RescueTime logo"),
    IFTTTIntegration("ring", display_name="Ring", logo_alt="Ring logo"),
    IFTTTIntegration("roost-smart-battery", display_name="Roost Smart Battery", logo_alt="Roost Smart Battery logo"),
    IFTTTIntegration("sfgate", display_name="SFGATE", logo_alt="SFGATE logo"),
    IFTTTIntegration("sfmta", display_name="SFMTA", logo_alt="SFMTA logo"),
    IFTTTIntegration("signul-beacon", display_name="SIGNUL Beacon", logo_alt="SIGNUL Beacon logo"),
    IFTTTIntegration("sms", display_name="SMS", logo_alt="SMS logo"),
    IFTTTIntegration("safetrek", display_name="SafeTrek", logo_alt="SafeTrek logo"),
    IFTTTIntegration("salesforce", display_name="Salesforce", logo_alt="Salesforce logo"),
    IFTTTIntegration("samsung-air-purifier", display_name="Samsung Air Purifier", logo_alt="Samsung Air Purifier logo"),
    IFTTTIntegration("samsung-floor-air-conditioner", display_name="Samsung Floor Air Conditioner", logo_alt="Samsung Floor Air Conditioner logo"),
    IFTTTIntegration("samsung-refrigerator", display_name="Samsung Refrigerator", logo_alt="Samsung Refrigerator logo"),
    IFTTTIntegration("samsung-robot-vacuum", display_name="Samsung Robot Vacuum", logo_alt="Samsung Robot Vacuum logo"),
    IFTTTIntegration("samsung-room-air-conditioner", display_name="Samsung Room Air Conditioner", logo_alt="Samsung Room Air Conditioner logo"),
    IFTTTIntegration("samsung-washer", display_name="Samsung Washer", logo_alt="Samsung Washer logo"),
    IFTTTIntegration("sateraito-office", display_name="Sateraito Office", logo_alt="Sateraito Office logo"),
    IFTTTIntegration("scout-alarm", display_name="Scout Alarm", logo_alt="Scout Alarm logo"),
    IFTTTIntegration("seagate-personal-cloud", display_name="Seagate Personal Cloud", logo_alt="Seagate Personal Cloud logo"),
    IFTTTIntegration("securities-and-exchange-commission", display_name="Securities and Exchange Commission", logo_alt="Securities and Exchange Commission logo"),
    IFTTTIntegration("securycate", display_name="SecuryCate", logo_alt="SecuryCate logo"),
    IFTTTIntegration("seeed", display_name="Seeed", logo_alt="Seeed logo"),
    IFTTTIntegration("seeed-wio", display_name="Seeed Wio", logo_alt="Seeed Wio logo"),
    IFTTTIntegration("sen.se-mother", display_name="Sen.se Mother", logo_alt="Sen.se Mother logo"),
    IFTTTIntegration("sense-energy-monitor", display_name="Sense Energy Monitor", logo_alt="Sense Energy Monitor logo"),
    IFTTTIntegration("sensibo", display_name="Sensibo", logo_alt="Sensibo logo"),
    IFTTTIntegration("sesame-by-candy-house", display_name="Sesame by CANDY HOUSE", logo_alt="Sesame by CANDY HOUSE logo"),
    IFTTTIntegration("sharpr", display_name="Sharpr", logo_alt="Sharpr logo"),
    IFTTTIntegration("shopyourway", display_name="ShopYourWay", logo_alt="ShopYourWay logo"),
    IFTTTIntegration("sighthound-video", display_name="Sighthound Video", logo_alt="Sighthound Video logo"),
    IFTTTIntegration("sina-weibo", display_name="Sina Weibo", logo_alt="Sina Weibo logo"),
    IFTTTIntegration("skybell-hd", display_name="SkyBell HD", logo_alt="SkyBell HD logo"),
    IFTTTIntegration("skydrop", display_name="Skydrop", logo_alt="Skydrop logo"),
    IFTTTIntegration("skylark", display_name="Skylark", logo_alt="Skylark logo"),
    IFTTTIntegration("skylinknet", display_name="SkylinkNet", logo_alt="SkylinkNet logo"),
    IFTTTIntegration("skype", display_name="Skype", logo_alt="Skype logo"),
    IFTTTIntegration("slack", display_name="Slack", logo_alt="Slack logo"),
    IFTTTIntegration("slashdot", display_name="Slashdot", logo_alt="Slashdot logo"),
    IFTTTIntegration("sleeppeanut", display_name="SleepPeanut", logo_alt="SleepPeanut logo"),
    IFTTTIntegration("slice", display_name="Slice", logo_alt="Slice logo"),
    IFTTTIntegration("smappee", display_name="Smappee", logo_alt="Smappee logo"),
    IFTTTIntegration("smart-life", display_name="Smart Life", logo_alt="Smart Life logo"),
    IFTTTIntegration("smart-louisville", display_name="Smart Louisville", logo_alt="Smart Louisville logo"),
    IFTTTIntegration("smartthings", display_name="SmartThings", logo_alt="SmartThings logo"),
    IFTTTIntegration("smarter", display_name="Smarter", logo_alt="Smarter logo"),
    IFTTTIntegration("smartika", display_name="Smartika", logo_alt="Smartika logo"),
    IFTTTIntegration("somfy-protect", display_name="Somfy Protect", logo_alt="Somfy Protect logo"),
    IFTTTIntegration("songkick", display_name="Songkick", logo_alt="Songkick logo"),
    IFTTTIntegration("sotheby's", display_name="Sotheby's", logo_alt="Sotheby's logo"),
    IFTTTIntegration("soundcloud", display_name="SoundCloud", logo_alt="SoundCloud logo"),
    IFTTTIntegration("sowee", display_name="Sowee", logo_alt="Sowee logo"),
    IFTTTIntegration("space", display_name="Space", logo_alt="Space logo"),
    IFTTTIntegration("sports-illustrated", display_name="Sports Illustrated", logo_alt="Sports Illustrated logo"),
    IFTTTIntegration("spotcam-hd", display_name="SpotCam HD", logo_alt="SpotCam HD logo"),
    IFTTTIntegration("spotcam-sense", display_name="SpotCam Sense", logo_alt="SpotCam Sense logo"),
    IFTTTIntegration("spotify", display_name="Spotify", logo_alt="Spotify logo"),
    IFTTTIntegration("square", display_name="Square", logo_alt="Square logo"),
    IFTTTIntegration("stack-lighting", display_name="Stack Lighting", logo_alt="Stack Lighting logo"),
    IFTTTIntegration("star-wars-force-band-by-sphero", display_name="Star Wars Force Band by Sphero", logo_alt="Star Wars Force Band by Sphero logo"),
    IFTTTIntegration("stockimo", display_name="Stockimo", logo_alt="Stockimo logo"),
    IFTTTIntegration("stocks", display_name="Stocks", logo_alt="Stocks logo"),
    IFTTTIntegration("strava", display_name="Strava", logo_alt="Strava logo"),
    IFTTTIntegration("stringify", display_name="Stringify", logo_alt="Stringify logo"),
    IFTTTIntegration("stripe", display_name="Stripe", logo_alt="Stripe logo"),
    IFTTTIntegration("surfline", display_name="Surfline", logo_alt="Surfline logo"),
    IFTTTIntegration("surveymonkey", display_name="SurveyMonkey", logo_alt="SurveyMonkey logo"),
    IFTTTIntegration("switchbot", display_name="SwitchBot", logo_alt="SwitchBot logo"),
    IFTTTIntegration("time", display_name="TIME", logo_alt="TIME logo"),
    IFTTTIntegration("tp-link-kasa-(beta)", display_name="TP-Link Kasa (Beta)", logo_alt="TP-Link Kasa (Beta) logo"),
    IFTTTIntegration("tp-link-router", display_name="TP-Link Router", logo_alt="TP-Link Router logo"),
    IFTTTIntegration("tahoma", display_name="TaHoma", logo_alt="TaHoma logo"),
    IFTTTIntegration("teamsnap", display_name="TeamSnap", logo_alt="TeamSnap logo"),
    IFTTTIntegration("telegram", display_name="Telegram", logo_alt="Telegram logo"),
    IFTTTIntegration("telia-zone", display_name="Telia Zone", logo_alt="Telia Zone logo"),
    IFTTTIntegration("telldus-live!", display_name="Telldus Live!", logo_alt="Telldus Live! logo"),
    IFTTTIntegration("tesco", display_name="Tesco", logo_alt="Tesco logo"),
    IFTTTIntegration("texas-legislature", display_name="Texas Legislature", logo_alt="Texas Legislature logo"),
    IFTTTIntegration("the-new-york-times", display_name="The New York Times", logo_alt="The New York Times logo"),
    IFTTTIntegration("thermopeanut", display_name="ThermoPeanut", logo_alt="ThermoPeanut logo"),
    IFTTTIntegration("thermosmart", display_name="ThermoSmart", logo_alt="ThermoSmart logo"),
    IFTTTIntegration("thinga", display_name="Thinga", logo_alt="Thinga logo"),
    IFTTTIntegration("ticatag", display_name="Ticatag", logo_alt="Ticatag logo"),
    IFTTTIntegration("time-tracker", display_name="Time Tracker", logo_alt="Time Tracker logo"),
    IFTTTIntegration("todoist", display_name="Todoist", logo_alt="Todoist logo"),
    IFTTTIntegration("toodledo", display_name="Toodledo", logo_alt="Toodledo logo"),
    IFTTTIntegration("toronto-transit-commission", display_name="Toronto Transit Commission", logo_alt="Toronto Transit Commission logo"),
    IFTTTIntegration("trello", display_name="Trello", logo_alt="Trello logo"),
    IFTTTIntegration("tumblr", display_name="Tumblr", logo_alt="Tumblr logo"),
    IFTTTIntegration("twitch", display_name="Twitch", logo_alt="Twitch logo"),
    IFTTTIntegration("twitter", display_name="Twitter", logo_alt="Twitter logo"),
    IFTTTIntegration("u.s.-independence-day", display_name="U.S. Independence Day", logo_alt="U.S. Independence Day logo"),
    IFTTTIntegration("up-by-jawbone", display_name="UP by Jawbone", logo_alt="UP by Jawbone logo"),
    IFTTTIntegration("us-cert", display_name="US-CERT", logo_alt="US-CERT logo"),
    IFTTTIntegration("usa.gov", display_name="USA.gov", logo_alt="USA.gov logo"),
    IFTTTIntegration("uber", display_name="Uber", logo_alt="Uber logo"),
    IFTTTIntegration("ubi", display_name="Ubi", logo_alt="Ubi logo"),
    IFTTTIntegration("unforgettable-me", display_name="Unforgettable Me", logo_alt="Unforgettable Me logo"),
    IFTTTIntegration("united-nations-office-on-drugs-and-crime", display_name="United Nations Office on Drugs and Crime", logo_alt="United Nations Office on Drugs and Crime logo"),
    IFTTTIntegration("verizon-cloud", display_name="Verizon Cloud", logo_alt="Verizon Cloud logo"),
    IFTTTIntegration("vimeo", display_name="Vimeo", logo_alt="Vimeo logo"),
    IFTTTIntegration("vinli", display_name="Vinli", logo_alt="Vinli logo"),
    IFTTTIntegration("voip-calls", display_name="VoIP Calls", logo_alt="VoIP Calls logo"),
    IFTTTIntegration("vowkam", display_name="VowKam", logo_alt="VowKam logo"),
    IFTTTIntegration("wifiplug", display_name="WIFIPLUG", logo_alt="WIFIPLUG logo"),
    IFTTTIntegration("wallyhome", display_name="WallyHome", logo_alt="WallyHome logo"),
    IFTTTIntegration("warmup-smart-thermostat", display_name="Warmup Smart Thermostat", logo_alt="Warmup Smart Thermostat logo"),
    IFTTTIntegration("wattio-gate", display_name="Wattio GATE", logo_alt="Wattio GATE logo"),
    IFTTTIntegration("wattio-pod", display_name="Wattio POD", logo_alt="Wattio POD logo"),
    IFTTTIntegration("wattio-thermic", display_name="Wattio THERMIC", logo_alt="Wattio THERMIC logo"),
    IFTTTIntegration("wemo-air-purifier", display_name="WeMo Air Purifier", logo_alt="WeMo Air Purifier logo"),
    IFTTTIntegration("wemo-coffeemaker", display_name="WeMo Coffeemaker", logo_alt="WeMo Coffeemaker logo"),
    IFTTTIntegration("wemo-dimmer", display_name="WeMo Dimmer", logo_alt="WeMo Dimmer logo"),
    IFTTTIntegration("wemo-humidifier", display_name="WeMo Humidifier", logo_alt="WeMo Humidifier logo"),
    IFTTTIntegration("wemo-insight-switch", display_name="WeMo Insight Switch", logo_alt="WeMo Insight Switch logo"),
    IFTTTIntegration("wemo-light-switch", display_name="WeMo Light Switch", logo_alt="WeMo Light Switch logo"),
    IFTTTIntegration("wemo-lighting", display_name="WeMo Lighting", logo_alt="WeMo Lighting logo"),
    IFTTTIntegration("wemo-maker", display_name="WeMo Maker", logo_alt="WeMo Maker logo"),
    IFTTTIntegration("wemo-motion", display_name="WeMo Motion", logo_alt="WeMo Motion logo"),
    IFTTTIntegration("wemo-slow-cooker", display_name="WeMo Slow Cooker", logo_alt="WeMo Slow Cooker logo"),
    IFTTTIntegration("wemo-smart-plug", display_name="WeMo Smart Plug", logo_alt="WeMo Smart Plug logo"),
    IFTTTIntegration("weather-underground", display_name="Weather Underground", logo_alt="Weather Underground logo"),
    IFTTTIntegration("weatherflow-smart-weather-stations", display_name="WeatherFlow Smart Weather Stations", logo_alt="WeatherFlow Smart Weather Stations logo"),
    IFTTTIntegration("webhooks", display_name="Webhooks", logo_alt="Webhooks logo"),
    IFTTTIntegration("weebly", display_name="Weebly", logo_alt="Weebly logo"),
    IFTTTIntegration("whaller", display_name="Whaller", logo_alt="Whaller logo"),
    IFTTTIntegration("whirlpool-dryer", display_name="Whirlpool Dryer", logo_alt="Whirlpool Dryer logo"),
    IFTTTIntegration("whirlpool-refrigerator", display_name="Whirlpool Refrigerator", logo_alt="Whirlpool Refrigerator logo"),
    IFTTTIntegration("whirlpool-washer", display_name="Whirlpool Washer", logo_alt="Whirlpool Washer logo"),
    IFTTTIntegration("whistle", display_name="Whistle", logo_alt="Whistle logo"),
    IFTTTIntegration("wiz", display_name="WiZ", logo_alt="WiZ logo"),
    IFTTTIntegration("wikipedia", display_name="Wikipedia", logo_alt="Wikipedia logo"),
    IFTTTIntegration("wink-relay", display_name="Wink Relay", logo_alt="Wink Relay logo"),
    IFTTTIntegration("wink:-aros", display_name="Wink: Aros", logo_alt="Wink: Aros logo"),
    IFTTTIntegration("wink:-egg-minder", display_name="Wink: Egg Minder", logo_alt="Wink: Egg Minder logo"),
    IFTTTIntegration("wink:-nimbus", display_name="Wink: Nimbus", logo_alt="Wink: Nimbus logo"),
    IFTTTIntegration("wink:-pivot-power-genius", display_name="Wink: Pivot Power Genius", logo_alt="Wink: Pivot Power Genius logo"),
    IFTTTIntegration("wink:-porkfolio", display_name="Wink: Porkfolio", logo_alt="Wink: Porkfolio logo"),
    IFTTTIntegration("wink:-shortcuts", display_name="Wink: Shortcuts", logo_alt="Wink: Shortcuts logo"),
    IFTTTIntegration("wink:-spotter", display_name="Wink: Spotter", logo_alt="Wink: Spotter logo"),
    IFTTTIntegration("wireless-tag", display_name="Wireless Tag", logo_alt="Wireless Tag logo"),
    IFTTTIntegration("wiser-air", display_name="Wiser Air", logo_alt="Wiser Air logo"),
    IFTTTIntegration("withings", display_name="Withings", logo_alt="Withings logo"),
    IFTTTIntegration("wolfram-data-drop", display_name="Wolfram Data Drop", logo_alt="Wolfram Data Drop logo"),
    IFTTTIntegration("wordpress", display_name="WordPress", logo_alt="WordPress logo"),
    IFTTTIntegration("workflow", display_name="Workflow", logo_alt="Workflow logo"),
    IFTTTIntegration("world-health-organization", display_name="World Health Organization", logo_alt="World Health Organization logo"),
    IFTTTIntegration("world-wildlife-fund", display_name="World Wildlife Fund", logo_alt="World Wildlife Fund logo"),
    IFTTTIntegration("xy-findables", display_name="XY Findables", logo_alt="XY Findables logo"),
    IFTTTIntegration("yeelight", display_name="Yeelight", logo_alt="Yeelight logo"),
    IFTTTIntegration("youtube", display_name="YouTube", logo_alt="YouTube logo"),
    IFTTTIntegration("z-ware", display_name="Z-Ware", logo_alt="Z-Ware logo"),
    IFTTTIntegration("zeeq-by-rem-fit", display_name="ZEEQ by REM-Fit", logo_alt="ZEEQ by REM-Fit logo"),
    IFTTTIntegration("zubie", display_name="Zubie", logo_alt="Zubie logo"),
    IFTTTIntegration("abode", display_name="abode", logo_alt="abode logo"),
    IFTTTIntegration("bitly", display_name="bitly", logo_alt="bitly logo"),
    IFTTTIntegration("blink(1)", display_name="blink(1)", logo_alt="blink(1) logo"),
    IFTTTIntegration("data.world", display_name="data.world", logo_alt="data.world logo"),
    IFTTTIntegration("digitalstrom", display_name="digitalSTROM", logo_alt="digitalSTROM logo"),
    IFTTTIntegration("dondeesta-family", display_name="dondeEsta Family", logo_alt="dondeEsta Family logo"),
    IFTTTIntegration("ebay", display_name="eBay", logo_alt="eBay logo"),
    IFTTTIntegration("ewelink-smart-home", display_name="eWeLink Smart Home", logo_alt="eWeLink Smart Home logo"),
    IFTTTIntegration("easy4ip", display_name="easy4ip", logo_alt="easy4ip logo"),
    IFTTTIntegration("ecobee", display_name="ecobee", logo_alt="ecobee logo"),
    IFTTTIntegration("hugone", display_name="hugOne", logo_alt="hugOne logo"),
    IFTTTIntegration("ibaby", display_name="iBaby", logo_alt="iBaby logo"),
    IFTTTIntegration("idrate", display_name="iDrate", logo_alt="iDrate logo"),
    IFTTTIntegration("ilight", display_name="iLight", logo_alt="iLight logo"),
    IFTTTIntegration("io.e", display_name="iO.e", logo_alt="iO.e logo"),
    IFTTTIntegration("ios-calendar", display_name="iOS Calendar", logo_alt="iOS Calendar logo"),
    IFTTTIntegration("ios-contacts", display_name="iOS Contacts", logo_alt="iOS Contacts logo"),
    IFTTTIntegration("ios-health", display_name="iOS Health", logo_alt="iOS Health logo"),
    IFTTTIntegration("ios-photos", display_name="iOS Photos", logo_alt="iOS Photos logo"),
    IFTTTIntegration("ios-reading-list", display_name="iOS Reading List", logo_alt="iOS Reading List logo"),
    IFTTTIntegration("ios-reminders", display_name="iOS Reminders", logo_alt="iOS Reminders logo"),
    IFTTTIntegration("irobot", display_name="iRobot", logo_alt="iRobot logo"),
    IFTTTIntegration("isecurity+", display_name="iSecurity+", logo_alt="iSecurity+ logo"),
    IFTTTIntegration("ismartalarm", display_name="iSmartAlarm", logo_alt="iSmartAlarm logo"),
    IFTTTIntegration("ispy-agent", display_name="iSpy Agent", logo_alt="iSpy Agent logo"),
    IFTTTIntegration("izone", display_name="iZone", logo_alt="iZone logo"),
    IFTTTIntegration("ilumi", display_name="ilumi", logo_alt="ilumi logo"),
    IFTTTIntegration("intelligent-home", display_name="intelligent HOME", logo_alt="intelligent HOME logo"),
    IFTTTIntegration("iota-labs", display_name="iota labs", logo_alt="iota labs logo"),
    IFTTTIntegration("join.me", display_name="join.me", logo_alt="join.me logo"),
    IFTTTIntegration("littlebits", display_name="littleBits", logo_alt="littleBits logo"),
    IFTTTIntegration("mcamview-z+", display_name="mCamView Z+", logo_alt="mCamView Z+ logo"),
    IFTTTIntegration("matrix-io", display_name="matrix-io", logo_alt="matrix-io logo"),
    IFTTTIntegration("microbees", display_name="microBees", logo_alt="microBees logo"),
    IFTTTIntegration("mirubee", display_name="mirubee", logo_alt="mirubee logo"),
    IFTTTIntegration("mystrom", display_name="myStrom", logo_alt="myStrom logo"),
    IFTTTIntegration("nomos", display_name="nomos", logo_alt="nomos logo"),
    IFTTTIntegration("openhab", display_name="openHAB", logo_alt="openHAB logo"),
    IFTTTIntegration("popslate", display_name="popSLATE", logo_alt="popSLATE logo"),
    IFTTTIntegration("put.io", display_name="put.io", logo_alt="put.io logo"),
    IFTTTIntegration("reddit", display_name="reddit", logo_alt="reddit logo"),
    IFTTTIntegration("sremo", display_name="sRemo", logo_alt="sRemo logo"),
    IFTTTIntegration("simplehuman", display_name="simplehuman", logo_alt="simplehuman logo"),
    IFTTTIntegration("tado°-hot-water", display_name="tado° Hot Water", logo_alt="tado° Hot Water logo"),
    IFTTTIntegration("tadoº-air-conditioning", display_name="tadoº Air Conditioning", logo_alt="tadoº Air Conditioning logo"),
    IFTTTIntegration("tadoº-heating", display_name="tadoº Heating", logo_alt="tadoº Heating logo"),
    IFTTTIntegration("tracmo", display_name="tracMo", logo_alt="tracMo logo"),
    IFTTTIntegration("vsmart/erelax", display_name="vSMART/eRELAX", logo_alt="vSMART/eRELAX logo"),
    IFTTTIntegration("woopla", display_name="woopla", logo_alt="woopla logo"),
]   # type: List[IFTTTIntegration]
