from typing import Any

class JsonableError(Exception):
    error = ...  # type: Any
    def to_json_error_msg(self) -> Any: ...

class RequestVariableMissingError(JsonableError): ...

def REQ(*args: Any, **kwargs: Any) -> Any: ...

def has_request_variables(view_func: Any) -> Any: ...
