# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zilencer', '0003_add_default_for_remotezulipserver_last_updated_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteServerRegistrationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
