# Generated by Django 1.11.14 on 2018-08-13 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0182_set_initial_value_is_private_flag"),
        ("zilencer", "0009_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingProcessor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("state", models.CharField(max_length=20)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "log_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.RealmAuditLog"
                    ),
                ),
                (
                    "realm",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="zerver.Realm"
                    ),
                ),
            ],
        ),
    ]
