# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zilencer', '0010_billingprocessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_billing_relationship',
            field=models.BooleanField(default=False),
        ),
    ]
