# Generated by Django 1.11.14 on 2018-08-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0011_customer_has_billing_relationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("percent_off", models.SmallIntegerField(unique=True)),
                ("stripe_coupon_id", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
