# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-10 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zilencer', '0013_remove_customer_billing_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remotepushdevicetoken',
            unique_together=set([('server', 'user_id', 'kind', 'token')]),
        ),
    ]
