# Generated by Django 1.11.14 on 2018-10-10 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0013_remove_customer_billing_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="remotepushdevicetoken",
            unique_together={("server", "user_id", "kind", "token")},
        ),
    ]
