# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zilencer', '0015_delete_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotepushdevicetoken',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
