# Generated by Django 1.11.20 on 2019-04-23 20:17

from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index


class Migration(migrations.Migration):
    atomic = not settings.MIGRATIONS_ADD_REMOVE_INDEXES_CONCURRENTLY
    dependencies = [
        ("zilencer", "0016_remote_counts"),
    ]

    operations = [
        add_index(
            model_name="remoteinstallationcount",
            index=models.Index(
                fields=["server", "remote_id"],
                name="zilencer_remoteinstallat_server_id_remote_id_f72e4c30_idx",
            ),
        ),
        add_index(
            model_name="remoterealmcount",
            index=models.Index(
                fields=["server", "remote_id"],
                name="zilencer_remoterealmcount_server_id_remote_id_de1573d8_idx",
            ),
        ),
    ]
