# Generated by Django 2.2.14 on 2020-09-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zilencer', '0018_remoterealmauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotepushdevicetoken',
            name='encrypt_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
