# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-12 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zilencer', '0018_remoterealmauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotezulipserver',
            name='url_key',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
