# Generated by Django 3.2.9 on 2021-12-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0018_remoterealmauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="remotezulipserver",
            name="plan_type",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
