# Generated by Django 2.2.10 on 2020-02-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zilencer', '0018_remoterealmauditlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remoteinstallationcount',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='remoterealmcount',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='remoteinstallationcount',
            constraint=models.UniqueConstraint(condition=models.Q(subgroup__isnull=False), fields=('server', 'property', 'subgroup', 'end_time'), name='unique_remote_installation_count'),
        ),
        migrations.AddConstraint(
            model_name='remoteinstallationcount',
            constraint=models.UniqueConstraint(condition=models.Q(subgroup__isnull=True), fields=('server', 'property', 'end_time'), name='unique_remote_installation_count_null_subgroup'),
        ),
        migrations.AddConstraint(
            model_name='remoterealmcount',
            constraint=models.UniqueConstraint(condition=models.Q(subgroup__isnull=False), fields=('server', 'realm_id', 'property', 'subgroup', 'end_time'), name='unique_remote_realm_installation_count'),
        ),
        migrations.AddConstraint(
            model_name='remoterealmcount',
            constraint=models.UniqueConstraint(condition=models.Q(subgroup__isnull=True), fields=('server', 'realm_id', 'property', 'end_time'), name='unique_remote_realm_installation_count_null_subgroup'),
        ),
    ]
