# Generated by Django 3.2 on 2021-05-07 14:44
import orjson
import yaml
from django.db import migrations
from django.db.backends.postgresql.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def backfill_extra_data(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    RemoteRealmAuditLog = apps.get_model("zilencer", "RemoteRealmAuditLog")

    for data in RemoteRealmAuditLog.objects.filter(extra_data__isnull=False):
        try:
            extra_data_json = orjson.loads(data.extra_data)
        except orjson.JSONDecodeError:
            extra_data_json = yaml.safe_load(data.extra_data)
        data.extra_data_json = extra_data_json
        data.save(update_fields=["extra_data_json"])


class Migration(migrations.Migration):

    dependencies = [
        ("zilencer", "0019_remoterealmauditlog_extra_data_json"),
    ]

    operations = [
        migrations.RunPython(
            backfill_extra_data, reverse_code=migrations.RunPython.noop, elidable=True
        ),
    ]
