# Generated by Django 3.2.9 on 2021-12-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0020_remotezulipserverauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotezulipserver",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
