# Generated by Django 3.2 on 2021-05-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zilencer", "0020_backfill_remote_realmauditlog_extradata_to_json_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remoterealmauditlog",
            name="extra_data",
        ),
    ]
