# Generated by Django 4.1.3 on 2022-11-20 20:21

from typing import Type

import orjson
from django.db import migrations, models
from django.db.backends.postgresql.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def move_old_and_new_values_from_extra_data_to_columns(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    def move_for_audit_log_model(audit_log_model: Type[models.base.Model]) -> None:
        OLD_VALUE = "1"
        NEW_VALUE = "2"

        all_logs = audit_log_model.objects.exclude(extra_data=None)
        for log in all_logs:
            try:
                extra_data = orjson.loads(log.extra_data)
            except orjson.JSONDecodeError:
                continue

            if OLD_VALUE in extra_data:
                log.old_value = extra_data.pop(OLD_VALUE)
            if NEW_VALUE in extra_data:
                log.new_value = extra_data.pop(NEW_VALUE)

            log.extra_data = orjson.dumps(extra_data).decode()
            log.save()

    move_for_audit_log_model(apps.get_model("zilencer", "RemoteRealmAuditLog"))
    move_for_audit_log_model(apps.get_model("zilencer", "RemoteZulipServerAuditLog"))


class Migration(migrations.Migration):

    dependencies = [
        ("zilencer", "0025_alter_remotepushdevicetoken_user_id_drop_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoterealmauditlog",
            name="old_value",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="remoterealmauditlog",
            name="new_value",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="remotezulipserverauditlog",
            name="old_value",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="remotezulipserverauditlog",
            name="new_value",
            field=models.TextField(null=True),
        ),
        migrations.RunPython(
            move_old_and_new_values_from_extra_data_to_columns,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
