# Generated by Django 4.2.6 on 2023-10-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0030_alter_remoteinstallationcount_remote_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteinstallationcount",
            name="remote_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="remoterealmcount",
            name="remote_id",
            field=models.IntegerField(null=True),
        ),
    ]
