# Generated by Django 4.2.6 on 2023-11-08 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0033_remoterealm"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoterealmauditlog",
            name="remote_realm",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="zilencer.remoterealm"
            ),
        ),
        migrations.AlterField(
            model_name="remoterealmauditlog",
            name="remote_id",
            field=models.IntegerField(null=True),
        ),
    ]
