# Generated by Django 4.2.7 on 2023-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0035_remoterealmcount_remote_realm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="remotezulipserver",
            name="last_version",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
