# Generated by Django 4.2.7 on 2023-11-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0038_unique_server_remote_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoterealm",
            name="org_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Unspecified"),
                    (10, "Business"),
                    (20, "Open-source project"),
                    (30, "Education (non-profit)"),
                    (35, "Education (for-profit)"),
                    (40, "Research"),
                    (50, "Event or conference"),
                    (60, "Non-profit (registered)"),
                    (70, "Government"),
                    (80, "Political group"),
                    (90, "Community"),
                    (100, "Personal"),
                    (1000, "Other"),
                ],
                default=0,
            ),
        ),
    ]
