# Generated by Django 4.2.7 on 2023-12-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0042_alter_remoterealmauditlog_realm_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="remotepushdevicetoken",
            name="remote_realm",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="zilencer.remoterealm"
            ),
        ),
    ]
