# Generated by Django 4.2.7 on 2023-12-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0045_remoterealmauditlog_zilencer_remoterealmauditlog_server_realm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="remotezulipserver",
            name="last_audit_log_update",
            field=models.DateTimeField(null=True),
        ),
    ]
