# Generated by Django 4.2.8 on 2023-12-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0046_remotezulipserver_last_audit_log_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreregistrationRemoteServerBillingUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("status", models.IntegerField(default=0)),
                ("next_page", models.TextField(null=True)),
                (
                    "remote_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zilencer.remotezulipserver"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RemoteServerBillingUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.TextField(default="")),
                (
                    "remote_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zilencer.remotezulipserver"
                    ),
                ),
            ],
            options={
                "unique_together": {("remote_server", "email")},
            },
        ),
    ]
