# Generated by Django 4.2.8 on 2023-12-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0047_preregistrationremoteserverbillinguser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="remotezulipserver",
            name="last_api_feature_level",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
