# Generated by Django 4.2.8 on 2023-12-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0050_preregistrationremoterealmbillinguser_created_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoterealm",
            name="is_system_bot_realm",
            field=models.BooleanField(default=False),
        ),
    ]
