# Generated by Django 4.2.8 on 2023-12-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zilencer", "0052_alter_remoterealm_plan_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoterealmauditlog",
            name="acting_remote_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zilencer.remoterealmbillinguser",
            ),
        ),
        migrations.AddField(
            model_name="remoterealmauditlog",
            name="acting_support_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="remotezulipserverauditlog",
            name="acting_remote_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zilencer.remoteserverbillinguser",
            ),
        ),
        migrations.AddField(
            model_name="remotezulipserverauditlog",
            name="acting_support_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
