# Generated by Django 4.2.8 on 2023-12-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0055_remoteserverbillinguser_tos_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoterealm",
            name="realm_locally_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
