# Generated by Django 4.2.9 on 2024-02-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0057_remoterealm_last_request_timestamp_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="remoteinstallationcount",
            index=models.Index(
                condition=models.Q(("property", "mobile_pushes_forwarded::day")),
                fields=["server_id", "end_time"],
                name="zilencer_remoteinstallationcount_server_end_time_mobile_pushes_forwarded",
            ),
        ),
    ]
