# Generated by Django 4.2.9 on 2024-02-01 13:58

from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index


class Migration(migrations.Migration):
    atomic = not settings.MIGRATIONS_ADD_REMOVE_INDEXES_CONCURRENTLY
    dependencies = [
        ("zilencer", "0057_remoterealm_last_request_timestamp_and_more"),
    ]

    operations = [
        add_index(
            model_name="remoteinstallationcount",
            index=models.Index(
                condition=models.Q(("property", "mobile_pushes_forwarded::day")),
                fields=["server_id", "end_time"],
                name="zilencer_remoteinstallationcount_server_end_time_mobile_pushes_forwarded",
            ),
        ),
    ]
