# Generated by Django 4.2.9 on 2024-02-20 12:04

from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index


class Migration(migrations.Migration):
    atomic = not settings.MIGRATIONS_ADD_REMOVE_INDEXES_CONCURRENTLY
    dependencies = [
        ("zilencer", "0058_remoteinstallationcount_add_mobile_pushes_forwarded_index"),
    ]

    operations = [
        add_index(
            model_name="remoterealmauditlog",
            index=models.Index(
                condition=models.Q(("event_type__in", [101, 102, 103, 104, 105, 201, 202, 229])),
                fields=["remote_realm_id", "id"],
                name="zilencer_remoterealmauditlog_synced_billing_events",
            ),
        ),
    ]
