# Generated by Django 5.1.8 on 2025-06-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0710_pushdevice"),
        ("zilencer", "0001_squashed_0064_remotezulipserver_last_merge_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemotePushDevice",
            fields=[
                ("device_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.TextField()),
                ("token_kind", models.PositiveSmallIntegerField(choices=[(1, "Apns"), (2, "Fcm")])),
                ("push_account_id", models.BigIntegerField()),
                ("expired_time", models.DateTimeField(null=True)),
                (
                    "realm",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "remote_realm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zilencer.remoterealm",
                    ),
                ),
            ],
        ),
    ]
