# Generated by Django 5.2.3 on 2025-07-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0065_remotepushdevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotepushdevice",
            name="token_kind",
            field=models.CharField(choices=[("apns", "APNs"), ("fcm", "FCM")], max_length=4),
        ),
    ]
