# Generated by Django 5.2.10 on 2026-02-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0779_device"),
        ("zilencer", "0067_remotepushdevicetoken_apns_case_insensitive"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="remotepushdevice",
            name="unique_remote_push_device_push_account_id_token",
        ),
        migrations.AddField(
            model_name="remotepushdevice",
            name="token_id",
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="remotepushdevice",
            constraint=models.UniqueConstraint(
                fields=("token_id", "realm", "remote_realm"),
                name="unique_remote_push_device_token_id_realm_remote_realm",
            ),
        ),
    ]
