# Generated by Django 5.2.10 on 2026-02-03 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0068_add_remotepushdevice_token_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remotepushdevice",
            name="push_account_id",
        ),
    ]
