# Generated by Django 5.2.12 on 2026-04-08 16:02

from django.conf import settings
from django.db import migrations, models

from zerver.lib.migrate import add_index, remove_index


class Migration(migrations.Migration):
    atomic = settings.ATOMIC_PG_MIGRATIONS

    dependencies = [
        ("zilencer", "0069_remove_remotepushdevice_push_account_id"),
    ]

    operations = [
        remove_index(
            model_name="remoterealmauditlog",
            name="zilencer_remoterealmauditlog_synced_billing_events",
        ),
        add_index(
            model_name="remoterealmauditlog",
            index=models.Index(
                condition=models.Q(
                    (
                        "event_type__in",
                        [101, 102, 103, 104, 105, 201, 202, 229, 725],
                    )
                ),
                fields=["remote_realm_id", "id"],
                name="zilencer_remoterealmauditlog_synced_billing_events",
            ),
        ),
    ]
