# Generated by Django 5.2.17 on 2026-09-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zilencer",
            "0070_remove_remoterealmauditlog_zilencer_remoterealmauditlog_synced_billing_events_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="remoterealm",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="remoterealm",
            name="directory_announced_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="remoterealm",
            name="emails_restricted_to_domains",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="remoterealm",
            name="has_web_public_streams",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="remoterealm",
            name="icon_url",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="remoterealm",
            name="invite_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="remoterealm",
            name="is_demo_organization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="remoterealm",
            name="last_reachable_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="remoterealm",
            name="asks_to_advertise_in_communities_directory",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
