# Generated by Django 5.2.17 on 2026-10-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zilencer", "0071_remoterealm_communities_directory_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoterealm",
            name="last_mirrored_icon_url",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="remoterealm",
            name="mirrored_icon_version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
