#!/bin/sh -ex

rm -rf static/third/gemoji/images
(cd tools/emoji_dump && python ./emoji_dump.py)
mkdir -p static/third/gemoji/images
mv tools/emoji_dump/out static/third/gemoji/images/emoji
cp -RPp assets/zulip-emoji/* static/third/gemoji/images/emoji/
