#!/usr/bin/env bash
set -euxo pipefail

version="2.3.6"
sha256=fc68a66a216e304bb0e2ef627f767fff528f4fbf2bbda27e8cd8db1b7ba090b0

tmpdir="$(mktemp -d)"
trap 'rm -r "$tmpdir"' EXIT
cd "$tmpdir"
tarball="pgroonga-$version.tar.gz"
curl -fLO "https://packages.groonga.org/source/pgroonga/$tarball"
sha256sum -c <<<"$sha256 $tarball"
tar -xzf "$tarball"
cd "pgroonga-$version"

make -j "$(nproc)" HAVE_MSGPACK=1
make install
