#!/usr/bin/env bash
set -euxo pipefail

version="16.0.1"
sha256=d7c5c2fdd9f3734c00392e3da7c7dbbd9b28e3801f965458ba79c72e7ae581e1

tmpdir="$(mktemp -d)"
trap 'rm -r "$tmpdir"' EXIT
cd "$tmpdir"
tarball="groonga-$version.tar.gz"
curl -fLO --retry 3 "https://github.com/groonga/groonga/releases/download/v$version/$tarball"
sha256sum -c <<<"$sha256 $tarball"
tar -xzf "$tarball"
cd "groonga-$version"

./configure --prefix=/usr
make -j "$(nproc)"
make install
