#!/usr/bin/env python3
import argparse
import os
import subprocess
import sys

if False:
    from typing import Set, Text

ZULIP_PATH = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(ZULIP_PATH)
from scripts.lib.node_cache import generate_sha1sum_node_modules
from scripts.lib.zulip_tools import get_caches_to_be_purged, \
    get_environment, get_recent_deployments, parse_cache_script_args, \
    purge_unused_caches

ENV = get_environment()
NODE_MODULES_CACHE_PATH = "/srv/zulip-npm-cache"
if ENV == "travis":
    NODE_MODULES_CACHE_PATH = os.path.join(os.environ["HOME"], "zulip-npm-cache")
    try:
        subprocess.check_output(["/srv/zulip-yarn/bin/yarn", '--version'])
    except OSError:
        print('yarn not found. Most probably we are running static-analysis and '
              'hence yarn is not installed. Exiting without cleaning npm cache.')
        sys.exit(0)

def get_caches_in_use(threshold_days):
    # type: (int) -> Set[Text]
    setups_to_check = set([ZULIP_PATH, ])
    caches_in_use = set()

    if ENV == "prod":
        setups_to_check |= get_recent_deployments(threshold_days)
    if ENV == "dev":
        # In dev always include the currently active cache in order
        # not to break current installation in case dependencies
        # are updated with bumping the provision version.
        CURRENT_CACHE = os.path.dirname(os.path.realpath(os.path.join(ZULIP_PATH, "node_modules")))
        caches_in_use.add(CURRENT_CACHE)

    for setup_dir in setups_to_check:
        PACKAGES_FILE = os.path.join(setup_dir, "package.json")
        if os.path.exists(PACKAGES_FILE):
            # If 'package.json' file doesn't exist then no node_modules
            # cache is associated with this setup.
            sha1sum = generate_sha1sum_node_modules(setup_dir=setup_dir)
            caches_in_use.add(os.path.join(NODE_MODULES_CACHE_PATH, sha1sum))

    return caches_in_use

def main():
    # type: () -> None
    args = parse_cache_script_args("This script cleans unused zulip npm caches.")
    caches_in_use = get_caches_in_use(args.threshold_days)
    purge_unused_caches(
        NODE_MODULES_CACHE_PATH, caches_in_use, "node modules cache", args)

if __name__ == "__main__":
    main()
