#!/usr/bin/env python

import os
import argparse
from os.path import dirname, abspath
import sys

ZULIP_PATH = dirname(dirname(dirname(abspath(__file__))))
if ZULIP_PATH not in sys.path:
    sys.path.append(ZULIP_PATH)

from scripts.lib.setup_venv import setup_virtualenv

parser = argparse.ArgumentParser(description="Create a thumbor virtualenv with caching")
parser.add_argument("target")
args = parser.parse_args()

cached_venv_path = setup_virtualenv(
    args.target,
    os.path.join(ZULIP_PATH, "requirements", "thumbor.txt"))
# Now the virtualenv has been activated
