#!/usr/bin/env bash
set -euo pipefail

version=16.13.0
arch="$(uname -m)"

case $arch in
    x86_64)
        tarball="node-v$version-linux-x64.tar.xz"
        sha256=a876ce787133149abd1696afa54b0b5bc5ce3d5ae359081d407ff776e39b7ba8
        ;;

    aarch64)
        tarball="node-v$version-linux-arm64.tar.xz"
        sha256=93a0d03f9f802353cb7052bc97a02cd9642b49fa985671cdc16c99936c86d7d2
        ;;
esac

check_version() {
    out="$(node --version)" && [ "$out" = "v$version" ]
}

if ! check_version; then
    tmpdir="$(mktemp -d)"
    trap 'rm -r "$tmpdir"' EXIT
    cd "$tmpdir"
    curl_opts=(-fLO)
    if [ -n "${CUSTOM_CA_CERTIFICATES:-}" ]; then
        curl_opts+=(--cacert "${CUSTOM_CA_CERTIFICATES}")
    fi
    curl "${curl_opts[@]}" "https://nodejs.org/dist/v$version/$tarball"
    sha256sum -c <<<"$sha256 $tarball"
    rm -rf /srv/zulip-node
    mkdir -p /srv/zulip-node
    tar -xJf "$tarball" --no-same-owner --strip-components=1 -C /srv/zulip-node
    ln -sf /srv/zulip-node/bin/{node,npm,npx} /usr/local/bin
    rm -rf /usr/local/nvm
    check_version
fi
