#!/usr/bin/env bash
set -euo pipefail

version=20.18.0
arch="$(uname -m)"

case $arch in
    x86_64)
        tarball="node-v$version-linux-x64.tar.xz"
        sha256=4543670b589593f8fa5f106111fd5139081da42bb165a9239f05195e405f240a
        ;;

    aarch64)
        tarball="node-v$version-linux-arm64.tar.xz"
        sha256=a9ce85675ba33f00527f6234d90000946c0936fb4fca605f1891bb5f4fe6fb0a
        ;;
esac

check_version() {
    out="$(node --version)" && [ "$out" = "v$version" ] \
        && [ /usr/local/bin/pnpm -ef /srv/zulip-node/lib/node_modules/corepack/dist/pnpm.js ]
}

if ! check_version 2>/dev/null; then
    set -x
    tmpdir="$(mktemp -d)"
    trap 'rm -r "$tmpdir"' EXIT
    cd "$tmpdir"
    curl_opts=(-fLO --retry 3)
    if [ -n "${CUSTOM_CA_CERTIFICATES:-}" ]; then
        curl_opts+=(--cacert "${CUSTOM_CA_CERTIFICATES}")
    fi
    curl "${curl_opts[@]}" "https://nodejs.org/dist/v$version/$tarball"
    sha256sum -c <<<"$sha256 $tarball"
    rm -rf /srv/zulip-node
    mkdir -p /srv/zulip-node
    tar -xJf "$tarball" --no-same-owner --strip-components=1 -C /srv/zulip-node
    ln -sf /srv/zulip-node/bin/{corepack,node,npm,npx} /usr/local/bin
    COREPACK_DEFAULT_TO_LATEST=0 /usr/local/bin/corepack enable

    # Clean up after previous versions of this script
    rm -rf /srv/zulip-yarn /usr/bin/yarn /usr/local/nvm

    check_version
fi
