#!/usr/bin/env bash
set -eu

version=0.6.13
arch="$(uname -m)"
tarball="uv-$arch-unknown-linux-gnu.tar.gz"
declare -A sha256=(
    [aarch64]=ac0c723663ff76183077cc9aa91dcd0b5100081d87f93e1ba482930e0a584e90
    [x86_64]=f6788fd45a25ea1033a671eaa9ece6c9b004ce5c9cf09552effadde567a7d7a5
)

check_version() {
    out="$(uv --version)" && [ "$out" = "uv $version" ]
}

if ! check_version 2>/dev/null; then
    set -x
    tmpdir="$(mktemp -d)"
    trap 'rm -r "$tmpdir"' EXIT
    cd "$tmpdir"
    curl -fLO --retry 3 "https://github.com/astral-sh/uv/releases/download/$version/$tarball"
    sha256sum -c <<<"${sha256[$arch]} $tarball"
    tar -xzf "$tarball" --no-same-owner --strip-components=1 -C /usr/local/bin "uv-$arch-unknown-linux-gnu"/{uv,uvx}
    check_version
fi
