#!/usr/bin/env bash
set -eu

version=0.11.32
arch="$(uname -m)"
tarball="uv-$arch-unknown-linux-gnu.tar.gz"
declare -A sha256=(
    [aarch64]=4d4fa08d95b06642e5800df6a22bd71455f23f988269e18da2847971d8c0bf31
    [x86_64]=aab924fd522efd06f1c5f3b93a243864fc453132c94b2dc49f1371b528a4b967
)

check_version() {
    out="$(uv --version)" && [[ "$out" = "uv $version ("* ]]
}

if ! check_version 2>/dev/null; then
    set -x
    tmpdir="$(mktemp -d)"
    trap 'rm -r "$tmpdir"' EXIT
    cd "$tmpdir"
    curl -fLO --retry 3 "https://github.com/astral-sh/uv/releases/download/$version/$tarball"
    sha256sum -c <<<"${sha256[$arch]} $tarball"
    tar -xzf "$tarball" --no-same-owner --strip-components=1 -C /usr/local/bin "uv-$arch-unknown-linux-gnu"/{uv,uvx}
    check_version
fi
