#!/usr/bin/env bash
set -eu

version=0.11.26
arch="$(uname -m)"
tarball="uv-$arch-unknown-linux-gnu.tar.gz"
declare -A sha256=(
    [aarch64]=befa1a59c91e96eb601b0fd9a97c03dd666f17baba644b2b4db9c59a767e387e
    [x86_64]=6426a73c3837e6e2483ee344cbc00f36394d179afcba6183cb77437e67db4af0
)

check_version() {
    out="$(uv --version)" && [[ "$out" = "uv $version ("* ]]
}

if ! check_version 2>/dev/null; then
    set -x
    tmpdir="$(mktemp -d)"
    trap 'rm -r "$tmpdir"' EXIT
    cd "$tmpdir"
    curl -fLO --retry 3 "https://github.com/astral-sh/uv/releases/download/$version/$tarball"
    sha256sum -c <<<"${sha256[$arch]} $tarball"
    tar -xzf "$tarball" --no-same-owner --strip-components=1 -C /usr/local/bin "uv-$arch-unknown-linux-gnu"/{uv,uvx}
    check_version
fi
