#!/usr/bin/env bash
set -eu -o pipefail

# shellcheck disable=SC2154 # expect this to run as NPM script
: "${npm_package_version}"

git commit -am "shared: Bump version to ${npm_package_version}"
git tag "shared-${npm_package_version}"
