#!/usr/bin/env bash

# See https://zulip.readthedocs.io/en/latest/translating/internationalization.html
# for background on this subsystem.

set -e
set -x

./manage.py makemessages --locale=en
tx push -s -r zulip.djangopo,zulip.translationsjson
