#!/usr/bin/env bash

# See https://zulip.readthedocs.io/en/latest/translating/internationalization.html
# for background on this subsystem.

set -e
set -x

./manage.py makemessages
tx pull -a -f --mode=onlytranslated --minimum-perc=5
./manage.py compilemessages
./tools/i18n/process-mobile-i18n
