#!/bin/sh
if [ "$(hostname)" = "staging.zulip.net" ]; then
    site="https://staging.zulip.com"
else
    site="https://api.zulip.com"
fi
/usr/lib/nagios/plugins/zulip_app_frontend/check_send_receive_time --munin "$1" --site="$site"
