#!/usr/bin/env -S uv run --frozen --no-config --only-group=prod --preview-features=target-workspace-discovery --script  # -*-python-*-

from scripts.lib.check_rabbitmq_queue import check_rabbitmq_queues

if __name__ == "__main__":
    check_rabbitmq_queues()
