"use strict";

exports.server_supported_permission_settings = {
    stream: {
        can_add_subscribers_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:nobody",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_administer_channel_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "channel_creator",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_create_topic_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:everyone",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_delete_any_message_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:nobody",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_delete_own_message_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:nobody",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_move_messages_out_of_channel_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:nobody",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_move_messages_within_channel_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:nobody",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_remove_subscribers_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: false,
            allow_everyone_group: true,
            default_group_name: "role:administrators",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_resolve_topics_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:nobody",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_send_message_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:everyone",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_subscribe_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:nobody",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
    },
    realm: {
        can_access_all_users_group: {
            require_system_group: true,
            allow_internet_group: false,
            allow_nobody_group: false,
            allow_everyone_group: true,
            default_group_name: "role:everyone",
            default_for_system_groups: null,
            allowed_system_groups: ["role:everyone", "role:members"],
        },
        can_add_custom_emoji_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:members",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_add_subscribers_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:members",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_create_bots_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:members",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_create_groups: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:members",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_create_private_channel_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:members",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_create_public_channel_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:members",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_create_web_public_channel_group: {
            require_system_group: true,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:owners",
            default_for_system_groups: null,
            allowed_system_groups: [
                "role:moderators",
                "role:administrators",
                "role:owners",
                "role:nobody",
            ],
        },
        can_create_write_only_bots_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:members",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_delete_any_message_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:administrators",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_delete_own_message_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:everyone",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_invite_users_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:members",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_manage_all_groups: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: false,
            allow_everyone_group: false,
            default_group_name: "role:owners",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_manage_billing_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: false,
            allow_everyone_group: false,
            default_group_name: "role:administrators",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_mention_many_users_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:administrators",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_move_messages_between_channels_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:members",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_move_messages_between_topics_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:everyone",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_resolve_topics_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:everyone",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_set_delete_message_policy_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:moderators",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_set_topics_policy_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:members",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        can_summarize_topics_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:everyone",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        create_multiuse_invite_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:administrators",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        direct_message_initiator_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:everyone",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
        direct_message_permission_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:everyone",
            default_for_system_groups: null,
            allowed_system_groups: [],
        },
    },
    group: {
        can_add_members_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "group_creator",
            default_for_system_groups: "role:nobody",
            allowed_system_groups: [],
        },
        can_join_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:nobody",
            default_for_system_groups: "role:nobody",
            allowed_system_groups: [],
        },
        can_leave_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:everyone",
            default_for_system_groups: "role:nobody",
            allowed_system_groups: [],
        },
        can_manage_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "group_creator",
            default_for_system_groups: "role:nobody",
            allowed_system_groups: [],
        },
        can_mention_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: true,
            default_group_name: "role:everyone",
            default_for_system_groups: "role:nobody",
            allowed_system_groups: [],
        },
        can_remove_members_group: {
            require_system_group: false,
            allow_internet_group: false,
            allow_nobody_group: true,
            allow_everyone_group: false,
            default_group_name: "role:nobody",
            default_for_system_groups: "role:nobody",
            allowed_system_groups: [],
        },
    },
};
