#!/usr/bin/env -S uv run --no-sync --only-group=prod --script  # -*-python-*-
import os
import sys

from django.conf import settings

os.environ["DJANGO_SETTINGS_MODULE"] = "zproject.settings"

print(getattr(settings, sys.argv[1]))
