#!/bin/sh
# Two quick API tests using curl
curl --digest -u tabbott:xxxxxxxxxxxxxxxxx https://app.humbughq.com/api/v1/send_message -d "api-key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -d "email=tabbott@humbughq.com" -d "type=personal" -d "content=test" -d "recipient=tabbott@humbughq.com"
curl --digest -u "tabbott:xxxxxxxxxxxxxxxxx" https://app.humbughq.com/api/v1/get_messages -d "api-key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -d "email=tabbott@humbughq.com"

# Replace '--digest -u tabbott:xxxxxxxxxxxxxxxxx https://app.humbughq.com'
# with "http://127.0.0.1:8000" for local testing
