#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright © 2012 Humbug, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import sys
from os import path
import optparse

usage = """list-subscriptions --user=<email address> [options]

Prints out a list of the user's subscriptions.

Example: list-subscriptions --user=tabbott@humbughq.com --site=https://zephyr.humbughq.com
"""
parser = optparse.OptionParser(usage=usage)
parser.add_option('--site', default='https://humbughq.com')
parser.add_option('--api-key')
parser.add_option('--user')
(options, args) = parser.parse_args()

sys.path.append(path.join(path.dirname(__file__), '..'))
import humbug
client = humbug.Client(
    email=options.user,
    api_key=options.api_key,
    verbose=True,
    site=options.site)

print client.list_subscriptions()
