#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright © 2012 Humbug, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import sys
from os import path
import optparse

usage = """print-next-message --user=<email address> [--stream=<stream>] [options]

Prints out the next message received by the indicated user, or on the indicated public stream.

Example: print-next-messages --user=tabbott@humbughq.com --site=https://zephyr.humbughq.com
"""
sys.path.append(path.join(path.dirname(__file__), '..'))
import humbug

parser = optparse.OptionParser(usage=usage)
parser.add_option_group(humbug.generate_option_group(parser))
parser.add_option('--stream', default=None)
(options, args) = parser.parse_args()

client = humbug.init_from_options(options)

get_messages_options = {}
if options.stream is not None:
    get_messages_options['stream_name'] = options.stream
print client.get_messages(get_messages_options)
