#!/usr/bin/python
import sys
import os
import optparse

usage = """subscribe --user=<email address> [options] --streams=<streams>

Ensures the user is subscribed to the listed streams.

Example: subscribe --user=tabbott@humbughq.com --site=http://127.0.0.1:8000
"""
parser = optparse.OptionParser(usage=usage)
parser.add_option('--site',
                  dest='site',
                  default="https://humbughq.com",
                  action='store')
parser.add_option('--api-key',
                  dest='api_key',
                  default=None,
                  action='store')
parser.add_option('--streams',
                  dest='streams',
                  default="",
                  action='store')
parser.add_option('--user',
                  dest='user',
                  action='store')
(options, args) = parser.parse_args()

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
import api.common
client = api.common.HumbugAPI(email=options.user,
                              api_key=options.api_key,
                              verbose=True,
                              site=options.site)

if options.streams == "":
    print >>sys.stderr, "Usage:", parser.usage
    sys.exit(1)

print client.add_subscriptions(options.streams.split())
