#!/usr/bin/env bash
# This tests upgrading PostgreSQL
set -e
set -x

cd /home/github/zulip

su zulip -c ./scripts/stop-server
./scripts/setup/upgrade-postgresql
su zulip -c ./scripts/start-server

echo "Upgrade of PostgreSQL complete!"
exit 0
