#!/usr/bin/env bash
set -x
set -e

# These services are no longer running when WSL is restarted
# and hence they have to be manually started.
sudo service rabbitmq-server start
sudo service memcached start
sudo service redis-server start
sudo service postgresql start
