#!/usr/bin/env python

"""
Nagios plugin to check that none of our queue workers have reported errors.
"""
from __future__ import print_function

import sys
sys.path.append('/home/zulip/deployments/current')
import scripts.lib.setup_path_on_import

from zproject import settings

import glob
import os

wildcard = os.path.join(settings.QUEUE_ERROR_DIR, '*.errors')
clean = True
for fn in glob.glob(wildcard):
    print('WARNING: Queue errors logged in %s' % (fn,))
    clean = False

if not clean:
    sys.exit(1)

sys.exit(0)
