#!/usr/bin/env bash
# Checks for any Zulip queue workers that are leaking memory and thus have a high vsize
datafile=$(mktemp)

# We expect other Nagios checks to monitor for whether no queue
# workers are running, so we give that condition a pass
processes=$(pgrep -f '^python.* /home/zulip/deployments/current/manage.py process_queue')
if [ -z "$processes" ]; then
    echo "No workers running"
    exit 0
fi
mapfile -t processes <<< "$processes"
ps -o vsize,size,pid,user,command --sort -vsize "${processes[@]}" > "$datafile"
cat "$datafile"
top_worker=$(head -n2 "$datafile" | tail -n1)
top_worker_memory_usage=$(echo "$top_worker" | cut -f1 -d" ")
rm -f "$datafile"
if [ "$top_worker_memory_usage" -gt 800000 ]; then
   exit 2
elif [ "$top_worker_memory_usage" -gt 600000 ]; then
   exit 1
else
   exit 0
fi
