#!/bin/bash

if [ -z "$1" ]; then
    deployment="staging"
else
    deployment=$1
fi

case $deployment in
    staging)
        host=staging.zulip.net
        ;;
    prod)
        host=prod0.zulip.net
        ;;
    *)
        echo "Unknown deployment: $deployment"
        exit 1
esac

exec ssh zulip@"$host" 'mkdir deployments/lock'
