#!/bin/sh -ex

GITID=$(git rev-parse HEAD)

TMPDIR=$(mktemp -d)
DIR=$TMPDIR/zulip-server/
TARBALL=$TMPDIR/zulip-server.tar.gz

git checkout-index -f -a --prefix $DIR

cd $DIR

# update-prod-static generates the prod-static directory.
# See COLLECTSTATIC in settings.py
./tools/update-prod-static

xargs rm -r <<EOF
analytics
assets
bots
corporate
static
tools
zilencer
.gitignore
templates/.gitignore
templates/analytics
templates/corporate
puppet/zulip_internal
zproject/local_settings.py
EOF

echo $GITID > version_id
mv update-prod-static.log ..

cd ..
tar -czf $TARBALL zulip-server

rm -r zulip-server
echo "Generated $TARBALL"
