#!/usr/bin/env python3

# check for the venv
from lib import sanity_check

sanity_check.check_venv(__file__)

import os
import sys

ZULIP_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(ZULIP_PATH)
from scripts.lib.zulip_tools import run


def main() -> None:
    path = os.path.join(ZULIP_PATH, "docs")
    run(["make", "clean", "html", "-C", path])


if __name__ == "__main__":
    main()
