#!/usr/bin/env -S uv run --frozen --no-config --preview-features=target-workspace-discovery --script  # -*-python-*-

import argparse
import os

from scripts.lib.zulip_tools import ENDC, WARNING, run

ZULIP_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--clean", action="store_true")
    args = parser.parse_args()

    path = os.path.join(ZULIP_PATH, "docs")
    if not args.clean:
        run(["make", "html", "-C", path])
        print(
            WARNING
            + "tools/build-docs --clean is necessary for the navigation/left sidebar to update."
            + ENDC
        )
        return

    run(["make", "clean", "html", "-C", path])


if __name__ == "__main__":
    main()
