#!/usr/bin/env python3
import argparse
import os
import sys

tools_dir = os.path.dirname(os.path.abspath(__file__))
root_dir = os.path.dirname(tools_dir)
sys.path.insert(0, root_dir)

from tools.lib.test_script import assert_provisioning_status_ok


def run() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--force',
                        action="store_true",
                        help='Run tests despite possible problems.')
    options = parser.parse_args()

    assert_provisioning_status_ok(options.force)

if __name__ == '__main__':
    run()
