#!/usr/bin/env bash
set -e

# Remove .pyc files without corresponding .py files
# to prevent loading stale code.
#
# You can run it automatically on checkout:
#
#     echo ./tools/clean-repo > .git/hooks/post-checkout
#     chmod +x .git/hooks/post-checkout

cd "$(dirname "$0")/.."
pycfiles=(`find . -name "*.pyc"`)
for i in "${pycfiles[@]}"
do
  pyfile="`basename $i .pyc`.py"
  if [ ! -e "$pyfile" ]; then
    rm $i;
  fi
done
find . -name "__pycache__" -prune -exec rm -rf {} \;
