#!/usr/bin/env python
from __future__ import absolute_import

import os
import glob
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
os.environ['DJANGO_SETTINGS_MODULE'] = 'zproject.settings'
from django.conf import settings

os.chdir(settings.DEPLOY_ROOT)
STATIC_PATH = 'static/'

def run():
    subprocess.check_call(['tools/node', 'node_modules/.bin/handlebars']
        + glob.glob(os.path.join(STATIC_PATH, 'templates/*.handlebars'))
        + ['--output', os.path.join(STATIC_PATH, 'templates/compiled.js'),
           '--known', 'if,unless,each,with'])

if __name__ == '__main__':
    run()
