#!/usr/bin/env bash
set -e

export NVM_DIR="/srv/zulip/.nvm"

if ! [ -s "$NVM_DIR/nvm.sh" ]
 then
    wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
fi

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

NODE_VERSION=6.6.0

nvm install "$NODE_VERSION" && nvm use "$NODE_VERSION"



