#!/usr/bin/env python3
import os
import subprocess
import sys

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
os.chdir(os.path.dirname(TOOLS_DIR))
sys.path.insert(0, os.path.dirname(TOOLS_DIR))

from zerver.lib.markdown import merge_api_changelogs

if __name__ == "__main__":
    ZULIP_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(ZULIP_PATH)

    changelogs = merge_api_changelogs.get_unmerged_changelogs()
    if changelogs:
        new_feature_level = merge_api_changelogs.get_feature_level()
        merge_api_changelogs.merge_changelogs(changelogs, new_feature_level)
        merge_api_changelogs.update_feature_level_in_api_docs(new_feature_level)
        merge_api_changelogs.remove_unmerged_changelog_files()

        commit_message = f"api: Increment API feature level to {new_feature_level}."

        try:
            subprocess.run(["git", "add", "-u"], check=True)
            subprocess.run(["git", "commit", "-m", commit_message], check=True)
        except subprocess.CalledProcessError as e:
            print(e)
            sys.exit(1)
