#!/usr/bin/env python3

# Minifies JavaScripts, creating source maps


import os
import subprocess
import argparse
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from typing import Any, Dict, Optional, Set

os.environ['DJANGO_SETTINGS_MODULE'] = 'zproject.settings'
from django.conf import settings

os.chdir(settings.DEPLOY_ROOT)

# Compile Handlebars templates
subprocess.check_call(['tools/compile-handlebars-templates'])

# Create webpack bundle
subprocess.check_call(['tools/webpack'])
