#!/bin/bash -e

# Wrapper for node which finds the right binary.

if which nodejs >/dev/null 2>&1; then
    # Name used by Debian etc.
    exec nodejs "$@"
else
    # Name used by upstream
    exec node "$@"
fi
