#!/usr/bin/python
#
# Humbug's post-receive hook.  Deploy it by symlinking it to
# /srv/git/humbug.git/hooks/post-receive
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for a sample

import os
import sys
import subprocess

args = sys.stdin.read()
oldrev, newrev, refname = args.split()

if refname in ["refs/heads/master", "refs/heads/test-post-receive"]:
    subprocess.check_call(["env", "-u", "GIT_DIR", "/home/humbug/humbug/tools/update-deployment",
                           oldrev, newrev, refname])
