#!/usr/bin/env python
import os
import sys
import pwd
import subprocess
import logging
import time
from zulip_tools import ENDC, OKGREEN, DEPLOYMENTS_DIR

logging.basicConfig(format="%(asctime)s restart-server: %(message)s",
                    level=logging.INFO)

deploy_path = os.path.realpath(os.path.join(os.path.dirname(__file__), '..'))
os.chdir(deploy_path)

if os.path.exists("/etc/humbug-server"):
    with open("/etc/humbug-machinetype") as mtf:
        if pwd.getpwuid(os.getuid())[0] != "zulip":
            logging.error("Must be run as user 'zulip'.")
            sys.exit(1)

# Send a statsd event on restarting the server
subprocess.check_call(["python", "./manage.py", "send_stats", "incr", "events.server_restart", str(int(time.time()))])

logging.info("Filling memcached caches")
subprocess.check_call(["python", "./manage.py", "fill_memcached_caches"])

# Restart the FastCGI and related processes via supervisorctl.
logging.info("Killing daemons")
subprocess.check_call(["supervisorctl", "stop", "humbug-workers:* humbug-django humbug-tornado"])
subprocess.check_call(["ln", '-nsf', deploy_path, os.path.join(DEPLOYMENTS_DIR, "current")])
subprocess.check_call(["supervisorctl", "start", "humbug-tornado humbug-django humbug-workers:*"])

logging.info("Done!")
print OKGREEN + "Application restarted successfully!" + ENDC
