#!/bin/bash

if ! [ -d ".git/hooks/" ]; then
    echo "Error: Could not find .git/hooks directory"
    echo "Please re-run this script from the root of your zulip.git checkout"
    exit 1
fi

for hook in pre-commit; do
    ln -snf ../../tools/"$hook" .git/hooks/
done
