#!/bin/bash
set -ex
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
/srv/zulip/tools/provision --compose
/srv/zulip/scripts/setup/configure-rabbitmq
/srv/zulip/tools/run-dev.py --interface=''
