#!/bin/bash -e

target='zerver'

case "$1" in
    zerver*)
      target="$1"
      shift
      ;;
esac

cd "$(dirname "$0")"/..
./tools/generate-fixtures
# "-u" uses unbuffered IO, which is important when wrapping it in subprocess
/usr/bin/env python2.7 -u ./manage.py test "$target" --settings=zproject.test_settings "$@"
