#!/bin/bash

sudo service rabbitmq-server restart
sudo service postgresql restart
sudo service redis-server restart
sudo service memcached restart
source /home/zulip/.bash_profile
/srv/zulip/tools/test-all
