#!/bin/bash -e

cd "$(dirname "$0")"/../zephyr/tests/frontend/node

NODEJS=$(which nodejs)
if [ ! -x "$NODEJS" ]; then
    NODEJS=$(which node)
fi

$NODEJS message_tour.js
$NODEJS unread.js
$NODEJS search.js
