#!/usr/bin/env bash

set -ev

wget https://github.com/houstondatavis/slack-export/archive/master.zip
mv master.zip slack-export-master.zip
./manage.py convert_slack_data $PWD/slack-export-master.zip "realm_name" --output zulip_data
./manage.py import --destroy-rebuild-database $PWD/zulip_data
