#!/usr/bin/env bash

set -ev
export DJANGO_SETTINGS_MODULE="zproject.slack_importer_test_settings"

psql -h localhost postgres zulip_test <<EOF
DROP DATABASE IF EXISTS zulip_slack_importer_test;
CREATE DATABASE zulip_slack_importer_test TEMPLATE zulip_test_template;
EOF

./manage.py migrate --noinput
./manage.py convert_slack_data ~/zulip/zerver/fixtures/slack_fixtures/test_slack_importer.zip "slack-importer-test-realm" --token ""xoxp-202525716848-302126526821-306710441015-afb69ff5ee9bf51577f88fa621107c9f"" --output /tmp/slack_importer_test_data
./manage.py import --import-into-nonempty /tmp/slack_importer_test_data
