#!/usr/bin/env bash

sudo service rabbitmq-server restart
sudo service postgresql restart
sudo service redis-server restart
# shellcheck source=/dev/null
source /home/zulip/.bash_profile
/srv/zulip/tools/test-all
