#!/usr/bin/env python3
"""
Check that tools/update-locked-requirements was executed
after editing of any requirements/*.in file
"""

import sys
import subprocess


def main():
    # type: () -> None
    """Run pip-compile-multi verify and provide guidance on error"""
    try:
        subprocess.check_call(['pip-compile-multi', 'verify'])
    except subprocess.CalledProcessError:
        sys.stderr.write(
            "It looks like you have updated some python dependencies but haven't\n"
            "updated locked requirements files.\n"
            "Please update them by running tools/update-locked-requirements.\n"
            "For more information please refer to requirements/README.md.\n"
        )
        sys.exit(1)
    sys.exit(0)


if __name__ == '__main__':
    main()
