#!/bin/bash -e

# Update static files in production.

cd "$(dirname "$0")"/..

# Redirect output to a log file (most recent run only)
exec >update-prod-static.log

# Compile Handlebars templates
./tools/node node_modules/.bin/handlebars zephyr/static/templates/*.handlebars \
    --output ./zephyr/static/templates/compiled.js \
    --known if,unless,each,with

# Collect the files that we're going to serve
rm -rf prod-static/source-map
mkdir -p prod-static/source-map
./manage.py collectstatic --noinput

