name: Check feature level updated

on:
  push:
    branches: [main]
    paths:
      - "api_docs/**"
  workflow_dispatch:

jobs:
  check-feature-level-updated:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Add required permissions
        run: chmod +x ./tools/check-feature-level-updated

      - name: Run tools/check-feature-level-updated
        id: run_check
        run: ./tools/check-feature-level-updated >> $GITHUB_OUTPUT

      - name: Report status to CZO
        if: ${{ steps.run_check.outputs.fail == 'true' && github.repository == 'zulip/zulip'}}
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_BOT_KEY }}
          email: "github-actions-bot@chat.zulip.org"
          organization-url: "https://chat.zulip.org"
          to: "automated testing"
          topic: ${{ steps.run_check.outputs.topic }}
          type: "stream"
          content: ${{ steps.run_check.outputs.content }}

      - name: Fail job if feature level not updated in API docs
        if: ${{ steps.run_check.outputs.fail == 'true' }}
        run: exit 1
