name: Sync Fork

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync main with upstream
        run: |
          git remote add upstream https://github.com/zulip/zulip.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main